/* compiler: ee-gcc2.96-no-strict-aliasing */
/* Settings lookup chain: after the parent's version (if any) declines, looks up each setting by name in
   the table a1 (func_0020FD38(a1, &name, &cb)) with a callback object (vtable + target pointer: a field
   of a0, or a local copied into a0 on success; its destructor resets the vtable and calls the base dtor
   MReaderBase__structor_0(&cb, 0)), returning 1 at the first success, else 0. Each block's locals are one struct
   of a union laid out as in the original frame; bastring.h's (const char *) ctor and dtor as inline
   helpers. Generated by build/auto/str_mid2/chain.py. */
typedef unsigned int u32;
typedef int s32;

struct Rep { u32 len; u32 res; u32 ref; u32 selfish; };
struct Str { char *dat; };
struct Heap { const char *name; };
extern Rep D_00659FA8;
extern "C" char *func_005C2560(Rep *r);
extern "C" u32 func_0057F260(const char *s);
extern "C" Heap *func_005C11A8(void);
extern "C" void func_00326798(void *p, u32 n, u32 align, const char *name);
extern "C" Str *func_005C2630(Str *self, u32 pos, u32 n1, const char *s, u32 n2);

static inline char *grab(Rep *r) {
    if (r->selfish)
        return func_005C2560(r);
    ++r->ref;
    return (char *)(r + 1);
}
static inline Str &assign(Str *str, const char *s, u32 n) { return *func_005C2630(str, 0, (u32)-1, s, n); }
static inline Str &assign(Str *str, const char *s) { return assign(str, s, func_0057F260(s)); }
static inline void construct(Str *str, const char *s) { str->dat = grab(&D_00659FA8); assign(str, s); }
static inline void construct(Str *str) { str->dat = grab(&D_00659FA8); }
static inline Rep *rep(const Str *str) { return (Rep *)str->dat - 1; }
static inline void deallocate(void *p, u32 n) { func_00326798(p, n, 4, func_005C11A8()->name); }
static inline void rep_delete(void *ptr) { deallocate(ptr, sizeof(Rep) + ((Rep *)ptr)->res); }
static inline void release(Rep *r) { if (--r->ref == 0) rep_delete(r); }
static inline void destroy(Str *str) { release(rep(str)); }

struct Cb { void **vtbl; void *p; };
extern "C" s32 func_0020FD38(void *a, Str *s, void *cb);
extern "C" void MReaderBase__structor_0(Cb *cb, s32 flags);
struct L0 { Str t; s32 pad0[7]; Cb cb; };
struct L1 { Cb cb; s32 pad0[10]; s32 v; s32 pad1[3]; Str t; };
struct L2 { Cb cb; s32 pad0[14]; Str t; };
extern char D_0069CE30[];
extern char D_0069CE40[];
extern char D_0069CE50[];
extern void *MfloatReader__vtable[];
extern void *MboolReader__vtable[];
extern void *MintReader__vtable[];
extern "C" s32 MfloatReader__structor_11(char *a0, void *a1);

extern "C" s32 MboolReader__structor_17(char *a0, void *a1)
{
    if (MfloatReader__structor_11(a0, a1))
        return 1;
    union { L0 l0; L1 l1; L2 l2; } u;
    {
        construct(&u.l0.t, D_0069CE30);
        char *p = (char *)(a0 + 0xD4);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MfloatReader__vtable;
        *(char **)((char *)pcb + 4) = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MfloatReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            return 1;
        }
    }
    {
        construct(&u.l1.t, D_0069CE40);
        char *p = (char *)(&u.l1.v);
        Cb *pcb = &u.l1.cb;
        pcb->vtbl = MintReader__vtable;
        *(char **)((char *)pcb + 4) = p;
        s32 r = func_0020FD38(a1, &u.l1.t, pcb);
        pcb->vtbl = MintReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l1.t);
        if (r) {
            *(s32 *)(a0 + 0xD8) = u.l1.v;
            return 1;
        }
    }
    {
        construct(&u.l2.t, D_0069CE50);
        char *p = (char *)(a0 + 0xDC);
        Cb *pcb = &u.l2.cb;
        pcb->vtbl = MboolReader__vtable;
        *(char **)((char *)pcb + 4) = p;
        s32 r = func_0020FD38(a1, &u.l2.t, pcb);
        pcb->vtbl = MboolReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l2.t);
        if (r) {
            return 1;
        }
    }
    return 0;
}
