/* gt4/__attr_type_info.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class __attr_type_info : type_info
 * type_info 0x008A20E0, type_info function 0x00616970, structors 0x005C0E98, 0x00616908
 * vtable 0x0068A388: 1 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4___attr_type_info_H
#define GT4___attr_type_info_H

#include "types.h"

struct __attr_type_info {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00616908
 */

#endif /* GT4___attr_type_info_H */
