/* gt4/__pointer_type_info.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class __pointer_type_info : type_info
 * type_info 0x008A2110, type_info function 0x006168B8, structors 0x005C0E78, 0x00616850
 * vtable 0x0068A3A0: 1 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4___pointer_type_info_H
#define GT4___pointer_type_info_H

#include "types.h"

struct __pointer_type_info {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00616850  __cxxabiv1::__pointer_type_info::~__pointer_type_info() [high]
 */

#endif /* GT4___pointer_type_info_H */
