/* gt4/__ptmf_type_info.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class __ptmf_type_info : type_info
 * type_info 0x008A20F0, type_info function 0x00616B98, structors 0x005C0EE0, 0x00616B30
 * vtable 0x0068A340: 1 slots
 * size: not known; the fields seen reach 0x8
 * C++ (GT4_CXX): size 0x8 (not known: up to the last field seen), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4___ptmf_type_info_H
#define GT4___ptmf_type_info_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/type_info.h"

class __ptmf_type_info : public type_info {
public:
};
#else
struct __ptmf_type_info {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00616B30
 */

#endif /* GT4___ptmf_type_info_H */
