/* gt4/__user_type_info.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class __user_type_info : type_info
 * type_info 0x008A20A0, type_info function 0x00616588, structors 0x005BFB88, 0x00616520, 0x006165D8, 0x006166A8, 0x00616778
 * vtable 0x0068A288: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4___user_type_info_H
#define GT4___user_type_info_H

#include "types.h"

struct __user_type_info {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00616520
 *   1: 0x005BFD68
 *   2: 0x005BFDC8
 *   3: 0x005BFE60
 */

#endif /* GT4___user_type_info_H */
