/* gt4/_Rb_tree_node_base.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class _Rb_tree_node_base
 * type_info 0x006D5E60, type_info function 0x005CB130
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4__Rb_tree_node_base_H
#define GT4__Rb_tree_node_base_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class _Rb_tree_node_base {
public:
};
#else
struct _Rb_tree_node_base;
#endif

#endif /* GT4__Rb_tree_node_base_H */
