/* gt4/_UnitArenaBase.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class _UnitArenaBase
 * type_info 0x006D6120, type_info function 0x00604E80, structors 0x00463790, 0x004637F0, 0x00463818
 * vtable 0x006888A8: 2 slots
 * size: not known; the fields seen reach 0x1C
 */
#ifndef GT4__UnitArenaBase_H
#define GT4__UnitArenaBase_H

#include "types.h"

struct _UnitArenaBase {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    s32 unkC;
    s32 unk10;
    s32 unk14;
    void *unk18;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00463790  _UnitArenaBase::~_UnitArenaBase() [high]
 *   1: 0x005BC5C0
 */

#endif /* GT4__UnitArenaBase_H */
