/* gt4/bad_typeid.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class bad_typeid : exception
 * type_info 0x008A2080, type_info function 0x00616488, structors 0x005C1C00, 0x006164D8
 * vtable 0x0068A2B8: 2 slots
 * C++ (GT4_CXX): size 0x4 (not known: up to the last field seen), vptr at 0x0
 */
#ifndef GT4_bad_typeid_H
#define GT4_bad_typeid_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/exception.h"

class bad_typeid : public exception {
public:
};
#else
struct bad_typeid;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x006164E8  std::bad_typeid::~bad_typeid() [high]
 *   1: 0x005C1CA0
 */

#endif /* GT4_bad_typeid_H */
