/* gt4/bad_exception.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class bad_exception : exception
 * type_info 0x008A2150, type_info function 0x00616E88, structors 0x005C19D0, 0x00616ED8
 * vtable 0x0068A3D8: 2 slots
 * C++ (GT4_CXX): size 0x4 (not known: up to the last field seen), vptr at 0x0
 */
#ifndef GT4_bad_exception_H
#define GT4_bad_exception_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/exception.h"

class bad_exception : public exception {
public:
};
#else
struct bad_exception;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00616EE8  std::bad_exception::~bad_exception() [high]
 *   1: 0x005C1CA0
 */

#endif /* GT4_bad_exception_H */
