/* gt4/CarIconMaker.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class CarIconMaker
 * type_info 0x0088F2E0, type_info function 0x005F7198, structors 0x00393A48, 0x00394A98, 0x005F7130
 * vtable 0x0067E140: 17 slots
 * size: not known; the fields seen reach 0x6C
 */
#ifndef GT4_CarIconMaker_H
#define GT4_CarIconMaker_H

#include "types.h"

struct CarIconMaker {
    char pad0[0x5C];
    s32 unk5C;
    s32 unk60;
    void *unk64;
    s32 unk68;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F7130  CarIconMaker::~CarIconMaker() [high]
 *   1: 0x001010E0  GranTurismo4::GameObjectPS3::start() [high]
 *   2: 0x001097A8  GranTurismo4::GameObjectBase::stop() [high]
 *   3: 0x001097E8  GranTurismo4::GameObjectBase::sync() [high]
 *   4: 0x00109830  GranTurismo4::GameObjectBase::controlFetch() [high]
 *   5: 0x00109868  GranTurismo4::GameObjectBase::controlFeedback() [high]
 *   6: 0x00393B30  CarIconMaker::update() [medium]
 *   7: 0x00101148  GranTurismo4::GameObjectPS3::render() [high]
 *   8: 0x001012C8  GranTurismo4::GameObjectPS3::terminate() [high]
 *   9: 0x001099A8  GranTurismo4::GameObjectBase::startHook() [high]
 *  10: 0x001099E8  GranTurismo4::GameObjectBase::terminateHook() [high]
 *  11: 0x00101308  GranTurismo4::GameObjectPS3::internal_update() [high]
 *  12: 0x001013D0  GranTurismo4::GameObjectPS3::internal_render() [high]
 *  13: 0x00101140  GranTurismo4::GameObjectPS3::update(float) [high]
 *  14: 0x00101288  GranTurismo4::GameObjectPS3::render(GranTurismo4::RenderContext&) [high]
 *  15: 0x00393B70  CarIconMaker::render(GSBuffer&) [high]
 *  16: 0x001012C0  GranTurismo4::GameObjectPS3::idle() [high]
 */

#endif /* GT4_CarIconMaker_H */
