/* gt4/ComputeDriverPostureCaller.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ComputeDriverPostureCaller
 * type_info 0x006D5F68, type_info function 0x005F3968
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4_ComputeDriverPostureCaller_H
#define GT4_ComputeDriverPostureCaller_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class ComputeDriverPostureCaller {
public:
};
#else
struct ComputeDriverPostureCaller;
#endif

#endif /* GT4_ComputeDriverPostureCaller_H */
