/* gt4/ConcourseCallback.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ConcourseCallback
 * type_info 0x0088FA50, type_info function 0x005FF430, structors 0x00409898, 0x005FF3C8, 0x005FF480
 * vtable 0x00686328: 5 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_ConcourseCallback_H
#define GT4_ConcourseCallback_H

#include "types.h"

struct ConcourseCallback {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FF3C8  ConcourseCallback::~ConcourseCallback() [high]
 *   1: 0x004574D8  ModelSet2::Callback::callback(int) [high]
 *   2: 0x00407D20  ConcourseCallback::LOD(float) [high]
 *   3: 0x004574F8  ModelSet2::Callback::usr(int, ModelSet2::RegisterVal*) [high]
 *   4: 0x00457500  ModelSet2::Callback::usrf(int, ModelSet2::RegisterVal*) [high]
 */

#endif /* GT4_ConcourseCallback_H */
