/* gt4/Concourse.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class Concourse : ScenePack
 * type_info 0x0088FA70, type_info function 0x005FF2F8, structors 0x00407FE0, 0x00408018
 * vtable 0x00686380: 2 slots
 * size: not known; the fields seen reach 0x14
 */
#ifndef GT4_Concourse_H
#define GT4_Concourse_H

#include "types.h"

struct Concourse {
    char pad0[0x8];
    s32 unk8;
    s32 unkC;
    s32 unk10;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x004080B0  Concourse::getSkinningBuffer() [high]
 *   1: 0x00408018  Concourse::~Concourse() [high]
 */

#endif /* GT4_Concourse_H */
