/* gt4/DevelopCamera.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DevelopCamera
 * type_info 0x0088F7F0, type_info function 0x005FD9A0, structors 0x003C8220, 0x003C8480, 0x005FD938, 0x005FD9F0
 * vtable 0x006827E0: 57 slots
 * size: not known; the fields seen reach 0xC22
 */
#ifndef GT4_DevelopCamera_H
#define GT4_DevelopCamera_H

#include "types.h"

struct DevelopCamera {
    char pad0[0x9C0];
    f32 unk9C0;
    char pad9C4[0x10];
    f32 unk9D4;
    char pad9D8[0xE8];
    f32 unkAC0;
    f32 unkAC4;
    u8 unkAC8;
    u8 unkAC9;
    char padACA[0x133];
    u8 unkBFD;
    char padBFE[0x23];
    u8 unkC21;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FD938
 *   1: 0x003C8BF8
 *   2: 0x003C8CC8
 *   3: 0x003C8D20
 *   4: 0x003C8D50
 *   5: 0x003C8D80
 *   6: 0x0044F210
 *   7: 0x0044F280
 *   8: 0x0044F2F0
 *   9: 0x003C8DB0
 *  10: 0x003C8DE0
 *  11: 0x003C8E10
 *  12: 0x00371CA8
 *  13: 0x00371CF8
 *  14: 0x00371D18
 *  15: 0x003C8E40
 *  16: 0x003C8E70
 *  17: 0x00371EA8
 *  18: 0x00373630
 *  19: 0x00373698
 *  20: 0x00372970
 *  21: 0x00372DF8
 *  22: 0x00373420
 *  23: 0x00371F38
 *  24: 0x00371F88
 *  25: 0x00372018
 *  26: 0x00373700
 *  27: 0x00373850
 *  28: 0x003738C0
 *  29: 0x00373930
 *  30: 0x003739A0
 *  31: 0x003739F0
 *  32: 0x00373AA0
 *  33: 0x00373AF8
 *  34: 0x00373B50
 *  35: 0x00373BA8
 *  36: 0x00373C00
 *  37: 0x00373C78
 *  38: 0x00373C68
 *  39: 0x00373C80
 *  40: 0x00373C88
 *  41: 0x00373D08
 *  42: 0x00373D38
 *  43: 0x00373DC0
 *  44: 0x00373DD8
 *  45: 0x00373E00
 *  46: 0x00373E08
 *  47: 0x00373E10
 *  48: 0x00373E18
 *  49: 0x00373E20
 *  50: 0x00373E28
 *  51: 0x00373E30
 *  52: 0x005FDA38
 *  53: 0x00373EF8
 *  54: 0x00373F18
 *  55: 0x003741F8
 *  56: 0x00374E88
 */

#endif /* GT4_DevelopCamera_H */
