/* gt4/DynamicsConductorFreePractice.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorFreePractice : DynamicsConductor
 * type_info 0x0088F9D0, type_info function 0x005FECA8, structors 0x003B93C8, 0x003F4EB8, 0x005FEC38
 * vtable 0x006856E0: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorFreePractice_H
#define GT4_DynamicsConductorFreePractice_H

#include "types.h"

struct DynamicsConductorFreePractice {
    char pad0[0x10140];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductorFreePractice__getStartingFormat(struct DynamicsConductorFreePractice *);
void DynamicsConductorFreePractice__getEachEntrantInfo(struct DynamicsConductorFreePractice *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductorFreePractice__virtual_29(struct DynamicsConductorFreePractice *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductorFreePractice__GetNumberOfLaps(struct DynamicsConductorFreePractice *);
s32 DynamicsConductorFreePractice__CurrentLapTime(struct DynamicsConductorFreePractice *, void *);
s32 DynamicsConductorFreePractice__ProcessCheckPoint(struct DynamicsConductorFreePractice *, s32, s32, s32, u32, u32, u32);
s32 DynamicsConductorFreePractice__ProcessLap0ControlLine(struct DynamicsConductorFreePractice *, s32, f32, u32, u32);
void DynamicsConductorFreePractice__ProcessControlLine(struct DynamicsConductorFreePractice *, s32, s32, u32, u32, u32, f32, u32);
s32 DynamicsConductorFreePractice__SetTireWearParameters(struct DynamicsConductorFreePractice *, void *);
s32 DynamicsConductorFreePractice__SetSlowCarBoostParameters(struct DynamicsConductorFreePractice *, void *);
s32 DynamicsConductorFreePractice__processCollision(struct DynamicsConductorFreePractice *);
s32 DynamicsConductorFreePractice__InitializeStandings(struct DynamicsConductorFreePractice *);
s32 DynamicsConductorFreePractice__ComputeStandings(struct DynamicsConductorFreePractice *);
s32 DynamicsConductorFreePractice__getCrashability(struct DynamicsConductorFreePractice *);
s32 DynamicsConductorFreePractice__EveryTimePitStop(struct DynamicsConductorFreePractice *);
void DynamicsConductorFreePractice__chargePenaltyBySurface(struct DynamicsConductorFreePractice *, void *, s32, s32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00359230
 *   1: 0x003F5270  DynamicsConductorFreePractice::InitializeStandings() [high]
 *   2: 0x003F5350  DynamicsConductorFreePractice::ComputeStandings() [high]
 *   3: 0x00365790
 *   4: 0x005FEC38  DynamicsConductorFreePractice::~DynamicsConductorFreePractice() [high]
 *   5: 0x00358248
 *   6: 0x00358250
 *   7: 0x00358258
 *   8: 0x00359B58
 *   9: 0x003F4EF0  DynamicsConductorFreePractice::getStartingFormat() [high]
 *  10: 0x003F5240  DynamicsConductorFreePractice::SetTireWearParameters(_GtbRaceParameterSource&) [high]
 *  11: 0x003F5248  DynamicsConductorFreePractice::SetSlowCarBoostParameters(_GtbRaceParameterSource&) [high]
 *  12: 0x003F5250  DynamicsConductorFreePractice::processCollision_() [high]
 *  13: 0x00357E00
 *  14: 0x00357E80
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x00357B08
 *  18: 0x003F5028  DynamicsConductorFreePractice::ProcessCheckPoint(int, int, int, unsigned int, unsigned int, unsigned int) [high]
 *  19: 0x003F50F0  DynamicsConductorFreePractice::ProcessLap0ControlLine(int, float, unsigned int, unsigned int) [high]
 *  20: 0x003F5150  DynamicsConductorFreePractice::ProcessControlLine(int, int, unsigned int, unsigned int, unsigned int, float, unsigned int) [high]
 *  21: 0x00357CF8
 *  22: 0x00357D00
 *  23: 0x0034E968
 *  24: 0x00349FC8
 *  25: 0x0034CA20
 *  26: 0x003F4F60  DynamicsConductorFreePractice::SetupGlobalStatusPost(int) [medium]
 *  27: 0x0034D490
 *  28: 0x003F4EF8  DynamicsConductorFreePractice::getEachEntrantInfo_(int, int*, int*, int*, int*) [high]
 *  29: 0x003F4F10
 *  30: 0x0034D328
 *  31: 0x0034E970
 *  32: 0x003585F0
 *  33: 0x003F5010  DynamicsConductorFreePractice::CurrentLapTime(Automobile&) [high]
 *  34: 0x0034D030
 *  35: 0x0034D048
 *  36: 0x003F5008  DynamicsConductorFreePractice::GetNumberOfLaps() [high]
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x00365478
 *  40: 0x0034DA58
 *  41: 0x0034C250
 *  42: 0x0034C288
 *  43: 0x003F54C8  DynamicsConductorFreePractice::getCrashability() [high]
 *  44: 0x0035FA30
 *  45: 0x0035FA38
 *  46: 0x0035FA40
 *  47: 0x0035FA48
 *  48: 0x003F54D8  DynamicsConductorFreePractice::chargePenaltyBySurface(Automobile&, int, int) [high]
 *  49: 0x0035FCC8
 *  50: 0x003F54D0  DynamicsConductorFreePractice::EveryTimePitStop() [high]
 *  51: 0x0034C098
 */

#endif /* GT4_DynamicsConductorFreePractice_H */
