/* gt4/DynamicsConductorBattle2P.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorBattle2P : DynamicsConductor
 * type_info 0x0088F060, type_info function 0x005F4C58, structors 0x0032F238, 0x003470B0, 0x005F4BE8
 * vtable 0x00679988: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorBattle2P_H
#define GT4_DynamicsConductorBattle2P_H

#include "types.h"

struct DynamicsConductorBattle2P {
    s32 unk0;
    char pad4[0xCBD4];
    s32 unkCBD8;
    char padCBDC[0x2C5E];
    u8 unkF83A;
    char padF83B[0x5D];
    s32 unkF898;
    char padF89C[0x24];
    s32 unkF8C0;
    char padF8C4[0x87C];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductorBattle2P__getEachEntrantInfo(struct DynamicsConductorBattle2P *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductorBattle2P__getSpecialStart(struct DynamicsConductorBattle2P *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductorBattle2P__GetNumberOfLaps(struct DynamicsConductorBattle2P *);
s32 DynamicsConductorBattle2P__SetSlowCarBoostParameters(struct DynamicsConductorBattle2P *, void *);
s32 DynamicsConductorBattle2P__SetTireWearParameters(struct DynamicsConductorBattle2P *, void *);
s32 DynamicsConductorBattle2P__getSlowCarBoostType(struct DynamicsConductorBattle2P *);
s32 DynamicsConductorBattle2P__processCollision(struct DynamicsConductorBattle2P *);
s32 DynamicsConductorBattle2P__IssuePassingGate(struct DynamicsConductorBattle2P *, s32, s32, s32, u32, u32);
void DynamicsConductorBattle2P__ProcessLapTimeCommonPost(struct DynamicsConductorBattle2P *);
void DynamicsConductorBattle2P__ProcessControlLine(struct DynamicsConductorBattle2P *, s32, s32, u32, u32, u32, f32, u32);
s32 DynamicsConductorBattle2P__ReportTimeDifference(struct DynamicsConductorBattle2P *);
s32 DynamicsConductorBattle2P__getCrashability(struct DynamicsConductorBattle2P *);
void DynamicsConductorBattle2P__chargePenaltyBySurface(struct DynamicsConductorBattle2P *, void *, s32, s32);
void DynamicsConductor__recordOneLapGhostControl(struct DynamicsConductorBattle2P *, struct RaceInput *, void *);
s32 DynamicsConductor__isRandomSkillAvailable(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__getStartingFormat(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__GetNumberOfSplits(struct DynamicsConductorBattle2P *);
f32 DynamicsConductor__GetCheckPointVabs(struct DynamicsConductorBattle2P *, s32);
void DynamicsConductor__GetStartV(struct DynamicsConductorBattle2P *);
void DynamicsConductor__GetGoalV(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__SetupGlobalStatusPre(struct DynamicsConductorBattle2P *, s32);
s32 DynamicsConductor__getStartPosition(struct DynamicsConductorBattle2P *, s32);
s32 DynamicsConductor__getLaunchSpeed(struct DynamicsConductorBattle2P *, s32);
s32 DynamicsConductor__getSpecialStart_RollingStart(struct DynamicsConductorBattle2P *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductor__initialize(struct DynamicsConductorBattle2P *, s32);
s32 DynamicsConductor__IsDelayStart(struct DynamicsConductorBattle2P *);
void DynamicsConductor__RunTimeJudgement(struct DynamicsConductorBattle2P *, s32, s32);
void DynamicsConductor__terminate(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__CurrentLapTime(struct DynamicsConductorBattle2P *, void *);
s32 DynamicsConductor__ProcessCheckPoint(struct DynamicsConductorBattle2P *, s32, s32, s32, u32, u32, u32);
void DynamicsConductor__ProcessLap0ControlLine(struct DynamicsConductorBattle2P *, s32, f32, u32, u32);
void DynamicsConductor__ProcessStartLine(struct DynamicsConductorBattle2P *, s32, f32, u32, u32);
s32 DynamicsConductor__ProcessGoalLine(struct DynamicsConductorBattle2P *, s32, s32, u32, u32, u32);
s32 DynamicsConductor__ProcessLapTimeCommonPre(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__isDataLoggerSupported(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__isDataLoggerStandingStart(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__isDataLoggerMultiLap(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__GetLapTimeCorrection(struct DynamicsConductorBattle2P *, s32);
void DynamicsConductor__SetLapTimeCorrection(struct DynamicsConductorBattle2P *, s32, s32);
void DynamicsConductor__getCourseV(struct DynamicsConductorBattle2P *, void *);
s32 DynamicsConductor__getDataLoggerSection(struct DynamicsConductorBattle2P *, void *, s32);
s32 DynamicsConductor__EveryTimePitStop(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__issueCrashEvent(struct DynamicsConductorBattle2P *, void *, s32, s32, f32);
f32 DynamicsConductor__ControlEnemySpeed(struct DynamicsConductorBattle2P *, void *, void *, f32);
s32 DynamicsConductor__ComputeStandings(struct DynamicsConductorBattle2P *);
s32 DynamicsConductor__InitializeStandings(struct DynamicsConductorBattle2P *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00347350  DynamicsConductorBattle2P::ReportTimeDifference() [high]
 *   1: 0x00365D80
 *   2: 0x00365BC0
 *   3: 0x00365790
 *   4: 0x005F4BE8  DynamicsConductorBattle2P::~DynamicsConductorBattle2P() [high]
 *   5: 0x00358248
 *   6: 0x00358250
 *   7: 0x00358258
 *   8: 0x00359B58
 *   9: 0x0034C1B0
 *  10: 0x003471A8  DynamicsConductorBattle2P::SetTireWearParameters(_GtbRaceParameterSource&) [high]
 *  11: 0x00347188  DynamicsConductorBattle2P::SetSlowCarBoostParameters(_GtbRaceParameterSource&) [high]
 *  12: 0x003471D8  DynamicsConductorBattle2P::processCollision_() [high]
 *  13: 0x00357E00
 *  14: 0x00347218  DynamicsConductorBattle2P::ProcessLapTimeCommonPost() [high]
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x003471F8  DynamicsConductorBattle2P::IssuePassingGate(int, int, int, unsigned int, unsigned int) [high]
 *  18: 0x00357B10
 *  19: 0x00357B90
 *  20: 0x00347230  DynamicsConductorBattle2P::ProcessControlLine(int, int, unsigned int, unsigned int, unsigned int, float, unsigned int) [high]
 *  21: 0x00357CF8
 *  22: 0x00357D00
 *  23: 0x0034E968
 *  24: 0x00349FC8
 *  25: 0x0034CA20
 *  26: 0x0034CD60
 *  27: 0x0034D490
 *  28: 0x003470E8  DynamicsConductorBattle2P::getEachEntrantInfo_(int, int*, int*, int*, int*) [high]
 *  29: 0x00347108  DynamicsConductorBattle2P::getSpecialStart(int, int*, int*, int*) [high]
 *  30: 0x0034D328
 *  31: 0x0034E970
 *  32: 0x003585F0
 *  33: 0x00357898
 *  34: 0x0034D030
 *  35: 0x0034D048
 *  36: 0x00347178  DynamicsConductorBattle2P::GetNumberOfLaps() [high]
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x003471C8  DynamicsConductorBattle2P::getSlowCarBoostType_() [high]
 *  40: 0x0034DA58
 *  41: 0x0034C250
 *  42: 0x0034C288
 *  43: 0x00347370  DynamicsConductorBattle2P::getCrashability() [high]
 *  44: 0x0035FA30
 *  45: 0x0035FA38
 *  46: 0x0035FA40
 *  47: 0x0035FA48
 *  48: 0x00347378  DynamicsConductorBattle2P::chargePenaltyBySurface(Automobile&, int, int) [high]
 *  49: 0x0035FCC8
 *  50: 0x0035AF10
 *  51: 0x0034C098
 */

#endif /* GT4_DynamicsConductorBattle2P_H */
