/* gt4/DynamicsConductorLicense.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorLicense : DynamicsConductor
 * type_info 0x0088F9F0, type_info function 0x005FEE28, structors 0x003BC0C0, 0x003BF7D8, 0x003ED388, 0x003F5F68, 0x005FEDB8, 0x005FEF38, 0x005FEFF8
 * vtable 0x00685A40: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorLicense_H
#define GT4_DynamicsConductorLicense_H

#include "types.h"

struct DynamicsConductorLicense {
    char pad0[0xF81A];
    u8 unkF81A;
    char padF81B[0x4B];
    u8 unkF866;
    char padF867[0x5];
    s16 unkF86C;
    char padF86E[0x8D2];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00359230
 *   1: 0x00365D80
 *   2: 0x00365BC0
 *   3: 0x00365790
 *   4: 0x005FEDB8  DynamicsConductorLicense::~DynamicsConductorLicense() [high]
 *   5: 0x003F5FA0  DynamicsConductorLicense::isDataLoggerSupported() [high]
 *   6: 0x003F60F8  DynamicsConductorLicense::isDataLoggerStandingStart() [high]
 *   7: 0x003F6110  DynamicsConductorLicense::isDataLoggerMultiLap() [high]
 *   8: 0x003F6140  DynamicsConductorLicense::getDataLoggerSection(Automobile&, bool) [high]
 *   9: 0x003F6090  DynamicsConductorLicense::getStartingFormat() [high]
 *  10: 0x0034D488
 *  11: 0x00365470
 *  12: 0x0034DB10
 *  13: 0x003F6878  DynamicsConductorLicense::ProcessLapTimeCommonPre() [high]
 *  14: 0x003F6880  DynamicsConductorLicense::ProcessLapTimeCommonPost() [high]
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x00357B08
 *  18: 0x003F63A0  DynamicsConductorLicense::ProcessCheckPoint(int, int, int, unsigned int, unsigned int, unsigned int) [high]
 *  19: 0x003F64D0  DynamicsConductorLicense::ProcessLap0ControlLine(int, float, unsigned int, unsigned int) [high]
 *  20: 0x003F6588  DynamicsConductorLicense::ProcessControlLine(int, int, unsigned int, unsigned int, unsigned int, float, unsigned int) [high]
 *  21: 0x003F6760  DynamicsConductorLicense::ProcessStartLine(int, float, unsigned int, unsigned int) [high]
 *  22: 0x003F67E8  DynamicsConductorLicense::ProcessGoalLine(int, int, unsigned int, unsigned int, unsigned int) [high]
 *  23: 0x0034E968
 *  24: 0x00349FC8
 *  25: 0x0034CA20
 *  26: 0x0034CD60
 *  27: 0x003F5FA8
 *  28: 0x003F6050  DynamicsConductorLicense::getEachEntrantInfo_(int, int*, int*, int*, int*) [high]
 *  29: 0x003F6278  DynamicsConductorLicense::getSpecialStart(int, int*, int*, int*) [high]
 *  30: 0x0034D328
 *  31: 0x003F5FF0  DynamicsConductorLicense::terminate() [high]
 *  32: 0x003585F0
 *  33: 0x003F61F8  DynamicsConductorLicense::CurrentLapTime(Automobile&) [high]
 *  34: 0x003F6070  DynamicsConductorLicense::getStartPosition(int) [high]
 *  35: 0x003F6080  DynamicsConductorLicense::getLaunchSpeed(int) [high]
 *  36: 0x003F60D0  DynamicsConductorLicense::GetNumberOfLaps() [high]
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x00365478
 *  40: 0x0034DA58
 *  41: 0x0034C250
 *  42: 0x0034C288
 *  43: 0x003F68F8  DynamicsConductorLicense::getCrashability() [high]
 *  44: 0x003F6900  DynamicsConductorLicense::getPenaltyAreaPenaltyType() [medium]
 *  45: 0x003F6908  DynamicsConductorLicense::getPitSurfacePenaltyType() [medium]
 *  46: 0x003F6910  DynamicsConductorLicense::getPitLanePenaltyType() [medium]
 *  47: 0x003F6930  DynamicsConductorLicense::isPitControlled() [medium]
 *  48: 0x0035FA98
 *  49: 0x003F6938  DynamicsConductorLicense::issueCrashEvent(Automobile&, int, int, float) [high]
 *  50: 0x0035AF10
 *  51: 0x0034C098
 */

#endif /* GT4_DynamicsConductorLicense_H */
