/* gt4/DynamicsConductor.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductor
 * type_info 0x006D5F80, type_info function 0x005F4E28, structors 0x0034BF28, 0x0034C020
 * vtable 0x00679E98: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductor_H
#define GT4_DynamicsConductor_H

#include "types.h"

struct DynamicsConductor {
    char pad0[0x10140];
    s32 unk10140;
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductor__SetupSlowCarBoost(struct DynamicsConductor *, s32);
s32 DynamicsConductor__getLimitTime(struct DynamicsConductor *);
s32 DynamicsConductor__GetCountDown(struct DynamicsConductor *, s32);
f32 DynamicsConductor__GetCourseLength(struct DynamicsConductor *);
s32 DynamicsConductor__IsExistStartV(struct DynamicsConductor *);
s32 DynamicsConductor__GetStartVOffsetBySectionSet(struct DynamicsConductor *);
s32 DynamicsConductor__getCourseType(struct DynamicsConductor *);
s32 DynamicsConductor__getEachEntrantInfo_TypicalRace(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductor__getEachEntrantInfo_TypicalTT(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductor__getEachEntrantInfo(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *, s32 *);
void DynamicsConductor__getSpecialStart_Handicap(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductor__getSpecialStart_Launch(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductor__getSpecialStart_Rolling_ByBalance(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductor__getSpecialStart_Rolling_ByCourse(struct DynamicsConductor *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductor__SetTireWearParameters(struct DynamicsConductor *, void *);
s32 DynamicsConductor__processCollision_Race(struct DynamicsConductor *);
s32 DynamicsConductor__processCollision_Solitaire(struct DynamicsConductor *, s32);
s32 DynamicsConductor__processCollision(struct DynamicsConductor *);
s32 DynamicsConductor__CurrentLapTime_Normal(struct DynamicsConductor *, void *);
s32 DynamicsConductor__IssuePassingGate_Race(struct DynamicsConductor *, s32, s32, s32, u32, u32);
void DynamicsConductor__IssuePassingGate(struct DynamicsConductor *, s32, s32, s32, u32, u32);
s32 DynamicsConductor__updateSolitaire_atTermination(struct DynamicsConductor *);
s32 DynamicsConductor__BSpecCommand(struct DynamicsConductor *, s32, s32, s32);
s32 DynamicsConductor__CurrentTotalTime(struct DynamicsConductor *);
s32 DynamicsConductor__getCourseVbyNose(struct DynamicsConductor *, void *);
s32 DynamicsConductor__getCourseVbyCenter(struct DynamicsConductor *, void *);
void DynamicsConductor__ReportTimeDifference(struct DynamicsConductor *);
s32 DynamicsConductor__ReportTimeDifference_Race(struct DynamicsConductor *);
s32 DynamicsConductor__getNumberOfLoggerSections(struct DynamicsConductor *);
void DynamicsConductor__playbackOneLapReplay(struct DynamicsConductor *, s32);
s32 DynamicsConductor__GetNumberOfPylonsToBeTouched(struct DynamicsConductor *);
s32 DynamicsConductor__GetNumberOfPylonsTouched(struct DynamicsConductor *);
void DynamicsConductor__ReportDifferenceFromRecord(struct DynamicsConductor *, s32, u32);
s32 DynamicsConductor__getCrashability(struct DynamicsConductor *);
s32 DynamicsConductor__chargePenaltyBySurface(struct DynamicsConductor *, void *, s32, s32);
s32 DynamicsConductor__issueCrashEvent_Exam(struct DynamicsConductor *, void *, s32, s32, f32);
s32 DynamicsConductor__SetSlowCarBoostParameters(struct DynamicsConductor *, void *);
s32 DynamicsConductor__getSlowCarBoostType(struct DynamicsConductor *);
s32 DynamicsConductor__GetStandings(struct DynamicsConductor *, s32);
void DynamicsConductor__ComputeDifference(struct DynamicsConductor *, const void *, const void *, s32 *, f32 *);
void DynamicsConductor__Update(struct DynamicsConductor *, s32);
s32 DynamicsConductor__IsBSpecRace(struct DynamicsConductor *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00359230  DynamicsConductor::ReportTimeDifference() [high]
 *   1: 0x00365D80  DynamicsConductor::InitializeStandings() [high]
 *   2: 0x00365BC0  DynamicsConductor::ComputeStandings() [high]
 *   3: 0x00365790  DynamicsConductor::ControlEnemySpeed(_CarStatus*, _CarStatus*, float) [high]
 *   4: 0x0034C020  DynamicsConductor::~DynamicsConductor() [high]
 *   5: 0x00358248  DynamicsConductor::isDataLoggerSupported() [high]
 *   6: 0x00358250  DynamicsConductor::isDataLoggerStandingStart() [high]
 *   7: 0x00358258  DynamicsConductor::isDataLoggerMultiLap() [high]
 *   8: 0x00359B58  DynamicsConductor::getDataLoggerSection(Automobile&, bool) [high]
 *   9: 0x0034C1B0  DynamicsConductor::getStartingFormat() [high]
 *  10: 0x0034D488  DynamicsConductor::SetTireWearParameters(_GtbRaceParameterSource&) [high]
 *  11: 0x00365470  DynamicsConductor::SetSlowCarBoostParameters(_GtbRaceParameterSource&) [high]
 *  12: 0x0034DB10  DynamicsConductor::processCollision_() [high]
 *  13: 0x00357E00  DynamicsConductor::ProcessLapTimeCommonPre() [high]
 *  14: 0x00357E80  DynamicsConductor::ProcessLapTimeCommonPost() [high]
 *  15: 0x00358260  DynamicsConductor::GetLapTimeCorrection(int) [high]
 *  16: 0x00358268  DynamicsConductor::SetLapTimeCorrection(int, int) [high]
 *  17: 0x00357B08  DynamicsConductor::IssuePassingGate(int, int, int, unsigned int, unsigned int) [high]
 *  18: 0x00357B10  DynamicsConductor::ProcessCheckPoint(int, int, int, unsigned int, unsigned int, unsigned int) [high]
 *  19: 0x00357B90  DynamicsConductor::ProcessLap0ControlLine(int, float, unsigned int, unsigned int) [high]
 *  20: 0x00357B98  DynamicsConductor::ProcessControlLine(int, int, unsigned int, unsigned int, unsigned int, float, unsigned int) [high]
 *  21: 0x00357CF8  DynamicsConductor::ProcessStartLine(int, float, unsigned int, unsigned int) [high]
 *  22: 0x00357D00  DynamicsConductor::ProcessGoalLine(int, int, unsigned int, unsigned int, unsigned int) [high]
 *  23: 0x0034E968  DynamicsConductor::RunTimeJudgement(int, int) [high]
 *  24: 0x00349FC8  DynamicsConductor::recordOneLapGhostControl(RaceInput*, _AutomobileControl&) [high]
 *  25: 0x0034CA20  DynamicsConductor::SetupGlobalStatusPre(int) [high]
 *  26: 0x0034CD60  DynamicsConductor::SetupGlobalStatusPost(int) [medium]
 *  27: 0x0034D490  DynamicsConductor::initialize(int) [high]
 *  28: 0x0034D010  DynamicsConductor::getEachEntrantInfo_(int, int*, int*, int*, int*) [high]
 *  29: 0x0034D150  DynamicsConductor::getSpecialStart(int, int*, int*, int*) [high]
 *  30: 0x0034D328  DynamicsConductor::getSpecialStart_RollingStart(int, int*, int*, int*) [high]
 *  31: 0x0034E970  DynamicsConductor::terminate() [high]
 *  32: 0x003585F0  DynamicsConductor::getCourseV(Automobile&) [high]
 *  33: 0x00357898  DynamicsConductor::CurrentLapTime(Automobile&) [high]
 *  34: 0x0034D030  DynamicsConductor::getStartPosition(int) [high]
 *  35: 0x0034D048  DynamicsConductor::getLaunchSpeed(int) [high]
 *  36: 0x003577F0  DynamicsConductor::GetNumberOfLaps() [high]
 *  37: 0x0034C318  DynamicsConductor::GetStartV() [high]
 *  38: 0x0034C450  DynamicsConductor::GetGoalV() [high]
 *  39: 0x00365478  DynamicsConductor::getSlowCarBoostType_() [high]
 *  40: 0x0034DA58  DynamicsConductor::IsDelayStart() [high]
 *  41: 0x0034C250  DynamicsConductor::GetNumberOfSplits() [high]
 *  42: 0x0034C288  DynamicsConductor::GetCheckPointVabs(int) [high]
 *  43: 0x0035FA28  DynamicsConductor::getCrashability() [high]
 *  44: 0x0035FA30  DynamicsConductor::getPenaltyAreaPenaltyType() [medium]
 *  45: 0x0035FA38  DynamicsConductor::getPitSurfacePenaltyType() [medium]
 *  46: 0x0035FA40  DynamicsConductor::getPitLanePenaltyType() [medium]
 *  47: 0x0035FA48  DynamicsConductor::isPitControlled() [medium]
 *  48: 0x0035FA98  DynamicsConductor::chargePenaltyBySurface(Automobile&, int, int) [high]
 *  49: 0x0035FCC8  DynamicsConductor::issueCrashEvent(Automobile&, int, int, float) [high]
 *  50: 0x0035AF10  DynamicsConductor::EveryTimePitStop() [high]
 *  51: 0x0034C098  DynamicsConductor::isRandomSkillAvailable() [high]
 */

#endif /* GT4_DynamicsConductor_H */
