/* gt4/DynamicsConductorSinglePlayer.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorSinglePlayer : DynamicsConductor
 * type_info 0x0088F080, type_info function 0x005F4DD8, structors 0x003394F8, 0x003474C0, 0x00386F78, 0x003C6E08, 0x003C8480, 0x003EDFC8, 0x003EF620, 0x005F4D68
 * vtable 0x00679CE8: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorSinglePlayer_H
#define GT4_DynamicsConductorSinglePlayer_H

#include "types.h"

struct DynamicsConductorSinglePlayer {
    s32 unk0;
    char pad4[0xCBE0];
    s8 unkCBE4;
    char padCBE5[0x2C55];
    u8 unkF83A;
    char padF83B[0x49];
    s16 unkF884;
    u8 unkF886;
    u8 unkF887;
    char padF888[0x8B8];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductorSinglePlayer__isRandomSkillAvailable(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__getStartingFormat(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__getSpecialStart(struct DynamicsConductorSinglePlayer *, s32, s32 *, s32 *, s32 *);
s32 DynamicsConductorSinglePlayer__getEachEntrantInfo(struct DynamicsConductorSinglePlayer *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductorSinglePlayer__SetTireWearParameters(struct DynamicsConductorSinglePlayer *, void *);
s32 DynamicsConductorSinglePlayer__SetSlowCarBoostParameters(struct DynamicsConductorSinglePlayer *, void *);
s32 DynamicsConductorSinglePlayer__getSlowCarBoostType(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__processCollision(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__IssuePassingGate(struct DynamicsConductorSinglePlayer *, s32, s32, s32, u32, u32);
void DynamicsConductorSinglePlayer__ProcessLapTimeCommonPre(struct DynamicsConductorSinglePlayer *);
void DynamicsConductorSinglePlayer__ProcessLapTimeCommonPost(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__ProcessLap0ControlLine(struct DynamicsConductorSinglePlayer *, s32, f32, u32, u32);
void DynamicsConductorSinglePlayer__ProcessGoalLine(struct DynamicsConductorSinglePlayer *, s32, s32, u32, u32, u32);
s32 DynamicsConductorSinglePlayer__ReportTimeDifference(struct DynamicsConductorSinglePlayer *);
s32 DynamicsConductorSinglePlayer__getCrashability(struct DynamicsConductorSinglePlayer *);
void DynamicsConductorSinglePlayer__chargePenaltyBySurface(struct DynamicsConductorSinglePlayer *, void *, s32, s32);
s32 DynamicsConductor__GetNumberOfLaps(struct DynamicsConductorSinglePlayer *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003479D0  DynamicsConductorSinglePlayer::ReportTimeDifference() [high]
 *   1: 0x00365D80
 *   2: 0x00365BC0
 *   3: 0x00365790
 *   4: 0x005F4D68  DynamicsConductorSinglePlayer::~DynamicsConductorSinglePlayer() [high]
 *   5: 0x00358248
 *   6: 0x00358250
 *   7: 0x00358258
 *   8: 0x00359B58
 *   9: 0x003475B8  DynamicsConductorSinglePlayer::getStartingFormat() [high]
 *  10: 0x00347858  DynamicsConductorSinglePlayer::SetTireWearParameters(_GtbRaceParameterSource&) [high]
 *  11: 0x003478B0  DynamicsConductorSinglePlayer::SetSlowCarBoostParameters(_GtbRaceParameterSource&) [high]
 *  12: 0x003478C8  DynamicsConductorSinglePlayer::processCollision_() [high]
 *  13: 0x00347908  DynamicsConductorSinglePlayer::ProcessLapTimeCommonPre() [high]
 *  14: 0x00347910  DynamicsConductorSinglePlayer::ProcessLapTimeCommonPost() [high]
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x003478E8  DynamicsConductorSinglePlayer::IssuePassingGate(int, int, int, unsigned int, unsigned int) [high]
 *  18: 0x00357B10
 *  19: 0x00347928  DynamicsConductorSinglePlayer::ProcessLap0ControlLine(int, float, unsigned int, unsigned int) [high]
 *  20: 0x00357B98
 *  21: 0x00357CF8
 *  22: 0x003479B8  DynamicsConductorSinglePlayer::ProcessGoalLine(int, int, unsigned int, unsigned int, unsigned int) [high]
 *  23: 0x0034E968
 *  24: 0x00349FC8
 *  25: 0x0034CA20
 *  26: 0x003477C8  DynamicsConductorSinglePlayer::SetupGlobalStatusPost(int) [medium]
 *  27: 0x0034D490
 *  28: 0x00347838  DynamicsConductorSinglePlayer::getEachEntrantInfo_(int, int*, int*, int*, int*) [high]
 *  29: 0x00347618  DynamicsConductorSinglePlayer::getSpecialStart(int, int*, int*, int*) [high]
 *  30: 0x0034D328
 *  31: 0x0034E970
 *  32: 0x003585F0
 *  33: 0x00357898
 *  34: 0x0034D030
 *  35: 0x0034D048
 *  36: 0x003577F0
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x003478B8  DynamicsConductorSinglePlayer::getSlowCarBoostType_() [high]
 *  40: 0x0034DA58
 *  41: 0x0034C250
 *  42: 0x0034C288
 *  43: 0x003479F0  DynamicsConductorSinglePlayer::getCrashability() [high]
 *  44: 0x0035FA30
 *  45: 0x0035FA38
 *  46: 0x0035FA40
 *  47: 0x0035FA48
 *  48: 0x003479F8  DynamicsConductorSinglePlayer::chargePenaltyBySurface(Automobile&, int, int) [high]
 *  49: 0x0035FCC8
 *  50: 0x0035AF10
 *  51: 0x003475B0  DynamicsConductorSinglePlayer::isRandomSkillAvailable() [high]
 */

#endif /* GT4_DynamicsConductorSinglePlayer_H */
