/* gt4/DynamicsConductorMission.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorMission : DynamicsConductorTraining
 * type_info 0x0088FA10, type_info function 0x005FEFA8, structors 0x003BF6E8
 * vtable 0x00685DA0: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorMission_H
#define GT4_DynamicsConductorMission_H

#include "types.h"

struct DynamicsConductorMission {
    char pad0[0xF81A];
    u8 unkF81A;
    char padF81B[0x1F];
    u8 unkF83A;
    char padF83B[0x2B];
    u8 unkF866;
    char padF867[0x5];
    s16 unkF86C;
    char padF86E[0x8D2];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductorMission__GetNumberOfSplits(struct DynamicsConductorMission *);
f32 DynamicsConductorMission__GetCheckPointVabs(struct DynamicsConductorMission *, s32);
s32 DynamicsConductorMission__ReportTimeDifference(struct DynamicsConductorMission *);
s32 DynamicsConductorMission__ProcessLap0ControlLine(struct DynamicsConductorMission *, s32, f32, u32, u32);
s32 DynamicsConductorMission__CurrentLapTime(struct DynamicsConductorMission *, void *);
s32 DynamicsConductorMission__RunTimeJudgement(struct DynamicsConductorMission *, s32, s32);
s32 DynamicsConductorMission__getCrashability(struct DynamicsConductorMission *);
s32 DynamicsConductorMission__issueCrashEvent(struct DynamicsConductorMission *, void *, s32, s32, f32);
s32 DynamicsConductorTraining__isDataLoggerSupported(struct DynamicsConductorMission *);
void DynamicsConductorTraining__SetupGlobalStatusPre(struct DynamicsConductorMission *, s32);
void DynamicsConductorTraining__getEachEntrantInfo(struct DynamicsConductorMission *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductorTraining__getStartPosition(struct DynamicsConductorMission *, s32);
s32 DynamicsConductorTraining__getLaunchSpeed(struct DynamicsConductorMission *, s32);
s32 DynamicsConductorTraining__SetSlowCarBoostParameters(struct DynamicsConductorMission *, void *);
s32 DynamicsConductorTraining__getSlowCarBoostType(struct DynamicsConductorMission *);
s32 DynamicsConductorTraining__processCollision(struct DynamicsConductorMission *);
s32 DynamicsConductorTraining__IssuePassingGate(struct DynamicsConductorMission *, s32, s32, s32, u32, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003F6E30  DynamicsConductorMission::ReportTimeDifference() [high]
 *   1: 0x00365D80
 *   2: 0x00365BC0
 *   3: 0x00365790
 *   4: 0x005FEF38  DynamicsConductorMission::~DynamicsConductorMission() [high]
 *   5: 0x003F7050
 *   6: 0x003F60F8
 *   7: 0x003F6110
 *   8: 0x003F6140
 *   9: 0x003F6090
 *  10: 0x0034D488
 *  11: 0x003F70D0
 *  12: 0x003F7108
 *  13: 0x003F6878
 *  14: 0x003F6880
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x003F7128
 *  18: 0x003F63A0
 *  19: 0x003F6E50  DynamicsConductorMission::ProcessLap0ControlLine(int, float, unsigned int, unsigned int) [high]
 *  20: 0x003F6588
 *  21: 0x003F6760
 *  22: 0x003F67E8
 *  23: 0x003F6EE8  DynamicsConductorMission::RunTimeJudgement(int, int) [high]
 *  24: 0x00349FC8
 *  25: 0x003F7058
 *  26: 0x0034CD60
 *  27: 0x003F5FA8
 *  28: 0x003F7078
 *  29: 0x003F6278
 *  30: 0x0034D328
 *  31: 0x003F5FF0
 *  32: 0x003585F0
 *  33: 0x003F6ED0  DynamicsConductorMission::CurrentLapTime(Automobile&) [high]
 *  34: 0x003F7090
 *  35: 0x003F70A8
 *  36: 0x003F60D0
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x003F70D8
 *  40: 0x0034DA58
 *  41: 0x003F6E00  DynamicsConductorMission::GetNumberOfSplits() [high]
 *  42: 0x003F6E18  DynamicsConductorMission::GetCheckPointVabs(int) [high]
 *  43: 0x003F7010  DynamicsConductorMission::getCrashability() [high]
 *  44: 0x003F7018  DynamicsConductorMission::getPenaltyAreaPenaltyType() [medium]
 *  45: 0x003F7020  DynamicsConductorMission::getPitSurfacePenaltyType() [medium]
 *  46: 0x003F7028
 *  47: 0x003F7030  DynamicsConductorMission::isPitControlled() [medium]
 *  48: 0x0035FA98
 *  49: 0x003F7038  DynamicsConductorMission::issueCrashEvent(Automobile&, int, int, float) [high]
 *  50: 0x0035AF10
 *  51: 0x0034C098
 */

#endif /* GT4_DynamicsConductorMission_H */
