/* gt4/DynamicsConductorBattleMP.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class DynamicsConductorBattleMP : DynamicsConductor
 * type_info 0x0088F070, type_info function 0x005F4D18, structors 0x00336718, 0x00338B80, 0x00347380, 0x005F4CA8
 * vtable 0x00679B38: 52 slots
 * size: not known; the fields seen reach 0x10144
 */
#ifndef GT4_DynamicsConductorBattleMP_H
#define GT4_DynamicsConductorBattleMP_H

#include "types.h"

struct DynamicsConductorBattleMP {
    char pad0[0xF83A];
    u8 unkF83A;
    char padF83B[0x905];
    union {
        void *unk10140;
        s32 unk10140_s32;
    };
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 DynamicsConductorBattleMP__virtual_28(struct DynamicsConductorBattleMP *, s32, s32 *, s32 *, s32 *, s32 *);
s32 DynamicsConductorBattleMP__virtual_36(struct DynamicsConductorBattleMP *);
s32 DynamicsConductorBattleMP__virtual_11(struct DynamicsConductorBattleMP *, void *);
s32 DynamicsConductorBattleMP__virtual_10(struct DynamicsConductorBattleMP *, void *);
s32 DynamicsConductorBattleMP__virtual_39(struct DynamicsConductorBattleMP *);
f32 DynamicsConductorBattleMP__virtual_03(struct DynamicsConductorBattleMP *, void *, void *, f32);
s32 DynamicsConductorBattleMP__virtual_12(struct DynamicsConductorBattleMP *);
s32 DynamicsConductorBattleMP__virtual_17(struct DynamicsConductorBattleMP *, s32, s32, s32, u32, u32);
s32 DynamicsConductorBattleMP__virtual_00(struct DynamicsConductorBattleMP *);
s32 DynamicsConductorBattleMP__virtual_43(struct DynamicsConductorBattleMP *);
void DynamicsConductorBattleMP__virtual_48(struct DynamicsConductorBattleMP *, void *, s32, s32);
void DynamicsConductor__getSpecialStart(struct DynamicsConductorBattleMP *, s32, s32 *, s32 *, s32 *);
void DynamicsConductor__ProcessControlLine(struct DynamicsConductorBattleMP *, s32, s32, u32, u32, u32, f32, u32);
s32 DynamicsConductor__ProcessLapTimeCommonPost(struct DynamicsConductorBattleMP *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00347490
 *   1: 0x00365D80
 *   2: 0x00365BC0
 *   3: 0x00347438
 *   4: 0x005F4CA8
 *   5: 0x00358248
 *   6: 0x00358250
 *   7: 0x00358258
 *   8: 0x00359B58
 *   9: 0x0034C1B0
 *  10: 0x00347408
 *  11: 0x003473E8
 *  12: 0x00347450
 *  13: 0x00357E00
 *  14: 0x00357E80
 *  15: 0x00358260
 *  16: 0x00358268
 *  17: 0x00347470
 *  18: 0x00357B10
 *  19: 0x00357B90
 *  20: 0x00357B98
 *  21: 0x00357CF8
 *  22: 0x00357D00
 *  23: 0x0034E968
 *  24: 0x00349FC8
 *  25: 0x0034CA20
 *  26: 0x0034CD60
 *  27: 0x0034D490
 *  28: 0x003473B8
 *  29: 0x0034D150
 *  30: 0x0034D328
 *  31: 0x0034E970
 *  32: 0x003585F0
 *  33: 0x00357898
 *  34: 0x0034D030
 *  35: 0x0034D048
 *  36: 0x003473D8
 *  37: 0x0034C318
 *  38: 0x0034C450
 *  39: 0x00347428
 *  40: 0x0034DA58
 *  41: 0x0034C250
 *  42: 0x0034C288
 *  43: 0x003474B0
 *  44: 0x0035FA30
 *  45: 0x0035FA38
 *  46: 0x0035FA40
 *  47: 0x0035FA48
 *  48: 0x003474B8
 *  49: 0x0035FCC8
 *  50: 0x0035AF10
 *  51: 0x0034C098
 */

#endif /* GT4_DynamicsConductorBattleMP_H */
