/* gt4/EnemyLineProcessorOld.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class EnemyLineProcessorOld
 * type_info 0x006D6128, type_info function 0x00604ED8, structors 0x0046A000, 0x0046A018
 * vtable 0x006888C8: 1 slots
 * C++ (GT4_CXX): size 0x1C (not known: up to the last field seen), vptr at 0x18 (introduced here)
 */
#ifndef GT4_EnemyLineProcessorOld_H
#define GT4_EnemyLineProcessorOld_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class EnemyLineProcessorOld {
public:
    char pad0[0x18];
    virtual ~EnemyLineProcessorOld();  /* 0: EnemyLineProcessorOld::~EnemyLineProcessorOld() */
};
#else
struct EnemyLineProcessorOld;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0046A018  EnemyLineProcessorOld::~EnemyLineProcessorOld() [high]
 */

#endif /* GT4_EnemyLineProcessorOld_H */
