/* gt4/filebuf.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class filebuf : streambuf
 * type_info 0x008A1C20, type_info function 0x00615960, structors 0x00596FC0, 0x00597028, 0x005970A0, 0x00597140
 * vtable 0x0068A018: 17 slots
 * size: not known; the fields seen reach 0x54
 */
#ifndef GT4_filebuf_H
#define GT4_filebuf_H

#include "types.h"

struct filebuf {
    s32 unk0;
    char pad4[0xC];
    s32 unk10;
    s32 unk14;
    char pad18[0x20];
    s32 unk38;
    char pad3C[0x14];
    void *unk50;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00597140
 *   1: 0x005973A0
 *   2: 0x005973B8
 *   3: 0x00593E70
 *   4: 0x00593F80
 *   5: 0x005974A8
 *   6: 0x005974D8
 *   7: 0x005973E8
 *   8: 0x00594078
 *   9: 0x00597370
 *  10: 0x005973D0
 *  11: 0x00597388
 *  12: 0x00597430
 *  13: 0x00597460
 *  14: 0x00597448
 *  15: 0x00597490
 *  16: 0x00597478
 */

#endif /* GT4_filebuf_H */
