/* gt4/GTSOUNDINSTRUMENTJAM.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class GTSOUNDINSTRUMENTJAM : GTSOUNDINSTRUMENT
 * type_info 0x0088FE90, type_info function 0x00604DB0, structors 0x004611F8, 0x004628C8, 0x00604D48
 * vtable 0x00688868: 2 slots
 * size: not known; the fields seen reach 0x24
 * C++ (GT4_CXX): size 0x24 (not known: up to the last field seen), vptr at 0x1C, fields left out (overlap, or in the base's part): 0x0, 0x4, 0x8, 0xC, 0x10, 0x14, 0x18, 0x1C
 */
#ifndef GT4_GTSOUNDINSTRUMENTJAM_H
#define GT4_GTSOUNDINSTRUMENTJAM_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/GTSOUNDINSTRUMENT.h"

class GTSOUNDINSTRUMENTJAM : public GTSOUNDINSTRUMENT {
public:
    s32 unk20;
    s32 getJam();  /* 0x00462998 */
};
#else
struct GTSOUNDINSTRUMENTJAM {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
    union {
        s32 unkC;
        void *unkC_pvoid;
    };
    union {
        s32 unk10;
        void *unk10_pvoid;
    };
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    union {
        s32 unk18;
        void *unk18_pvoid;
    };
    union {
        s32 unk1C;
        void * unk1C_pvoid;
        void *unk1C_pvoid_2;
    };
    s32 unk20;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
void GTSOUNDINSTRUMENT__AttachCallback(struct GTSOUNDINSTRUMENTJAM *);
s32 GTSOUNDINSTRUMENTJAM__getJam(struct GTSOUNDINSTRUMENTJAM *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00604D48  GTSOUNDINSTRUMENTJAM::~GTSOUNDINSTRUMENTJAM() [high]
 *   1: 0x00462668
 */

#endif /* GT4_GTSOUNDINSTRUMENTJAM_H */
