/* gt4/GTSOUNDINSTRUMENT.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class GTSOUNDINSTRUMENT
 * type_info 0x006D6118, type_info function 0x00604E00, structors 0x00462500, 0x00462530
 * vtable 0x00688888: 2 slots
 * size: not known; the fields seen reach 0x20
 */
#ifndef GT4_GTSOUNDINSTRUMENT_H
#define GT4_GTSOUNDINSTRUMENT_H

#include "types.h"

struct GTSOUNDINSTRUMENT {
    char pad0[0x4];
    void *unk4;
    void *unk8;
    void *unkC;
    void *unk10;
    void *unk14;
    void *unk18;
    void *unk1C;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00462530  GTSOUNDINSTRUMENT::~GTSOUNDINSTRUMENT() [high]
 *   1: 0x00462668  GTSOUNDINSTRUMENT::AttachCallback() [high]
 */

#endif /* GT4_GTSOUNDINSTRUMENT_H */
