/* gt4/hADHOC.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hADHOC : RefCounter
 * type_info 0x0088E9E0, type_info function 0x005EC108, structors 0x002ECA48, 0x002ECBD8
 * vtable 0x006732E8: 8 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_hADHOC_H
#define GT4_hADHOC_H

#include "types.h"

struct hADHOC {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002ECBD8  hADHOC::~hADHOC() [high]
 *   1: 0x002EC6E0  hADHOC::cleanup() [high]
 *   2: 0x00328508
 *   3: 0x002EA548  hADHOC::rc_class() const [high]
 *   4: 0x002EA558  hADHOC::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 */

#endif /* GT4_hADHOC_H */
