/* gt4/hArray.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hArray : hObject
 * type_info 0x0088EA00, type_info function 0x005ED8F0, structors 0x002EF6A0, 0x002EF6E8, 0x002EF800, 0x002EF8E8
 * vtable 0x00673358: 49 slots
 * size: not known; the fields seen reach 0x18
 * C++ (GT4_CXX): size 0x24 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x8
 */
#ifndef GT4_hArray_H
#define GT4_hArray_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"

class hArray : public hObject {
public:
    char pad10[0x4];
    s32 unk14;
    char pad18[0xC];
    static s32 GetClassID();  /* 0x002ED768 */
    s32 size() const;  /* 0x002EF9B0 */
};
#else
struct hArray {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    s32 unk14;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 hArray__rc_class(struct hArray *);
s32 hArray__rc_size(struct hArray *);
s32 hArray__GetClassID(void);
s32 hArray__getClassID(struct hArray *);
s32 hArray__cleanup(struct hArray *);
s32 hArray__size(struct hArray *);
s32 hArray__setElement(struct hArray *, u32, const struct HObject *);
s32 hArray__deepCopy(struct hArray *, const struct hObject *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002EF800  hArray::~hArray() [high]
 *   1: 0x002EEFC8  hArray::cleanup() [high]
 *   2: 0x002EEA88  hArray::toString() const [high]
 *   3: 0x002ED6F0  hArray::rc_class() const [high]
 *   4: 0x002ED700  hArray::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x002F04A8  hArray::deepCopy(hObject const*) [high]
 *   9: 0x002ED778  hArray::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x002EFA98  hArray::getElement(unsigned int) const [medium]
 *  13: 0x002EFAF8  hArray::getElement(unsigned int) [medium]
 *  14: 0x002EFB58  hArray::setElement(unsigned int, HObject const&) [high]
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x002EE9F0
 */

#endif /* GT4_hArray_H */
