/* gt4/hBuiltinMethod.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hBuiltinMethod : hMethodValue
 * type_info 0x0088EEF0, type_info function 0x005F2858, structors 0x0032DC08, 0x0032DC48
 * vtable 0x00676B38: 16 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x10 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_hBuiltinMethod_H
#define GT4_hBuiltinMethod_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hMethodValue.h"

class hBuiltinMethod : public hMethodValue {
public:
    union {
        s32 (*unkC)(s32, s32, s32, s32);
        void *unkC_pvoid;
    };
};
#else
struct hBuiltinMethod {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    union {
        s32 (*unkC)(s32, s32, s32, s32);
        void *unkC_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 hBuiltinMethod__rc_class(struct hBuiltinMethod *);
s32 hBuiltinMethod__rc_size(struct hBuiltinMethod *);
s32 hBuiltinMethod__call_const(struct hBuiltinMethod *, struct HObject *, const struct HObject *, s32, const struct HObject *);
s32 hBuiltinMethod__call_const_2(struct hBuiltinMethod *, void *, const struct HObject *, s32, const struct HObject *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0032DC48  hBuiltinMethod::~hBuiltinMethod() [high]
 *   1: 0x00328500
 *   2: 0x0032DB10  hBuiltinMethod::toString() const [high]
 *   3: 0x0032D9F8  hBuiltinMethod::rc_class() const [high]
 *   4: 0x0032DA08  hBuiltinMethod::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x003039F8
 *   9: 0x00303A70
 *  10: 0x00303A80
 *  11: 0x00303A78
 *  12: 0x00323CF8
 *  13: 0x00323D00
 *  14: 0x0032DA40  hBuiltinMethod::call(HThread&, HObject const&, int, HObject const*) const [high]
 *  15: 0x0032DA10  hBuiltinMethod::call(HObject&, HObject const&, int, HObject const*) const [high]
 */

#endif /* GT4_hBuiltinMethod_H */
