/* gt4/hBuiltinFunction.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hBuiltinFunction : hFunctionValue
 * type_info 0x0088EEE0, type_info function 0x005F2808, structors 0x0032D160, 0x0032D1A0
 * vtable 0x00676AA8: 16 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_hBuiltinFunction_H
#define GT4_hBuiltinFunction_H

#include "types.h"

struct hBuiltinFunction {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    void *unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0032D1A0  hBuiltinFunction::~hBuiltinFunction() [high]
 *   1: 0x00328500
 *   2: 0x0032D068  hBuiltinFunction::toString() const [high]
 *   3: 0x0032CF68  hBuiltinFunction::rc_class() const [high]
 *   4: 0x0032CF78  hBuiltinFunction::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x002FA940
 *   9: 0x002FA9B8
 *  10: 0x002FA9C8
 *  11: 0x002FA9C0
 *  12: 0x00323CF8
 *  13: 0x00323D00
 *  14: 0x0032CFA8  hBuiltinFunction::call(HThread&, int, HObject const*) const [high]
 *  15: 0x0032CF80  hBuiltinFunction::call(HObject&, int, HObject const*) const [high]
 */

#endif /* GT4_hBuiltinFunction_H */
