/* gt4/hFloat.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hFloat : hObject
 * type_info 0x0088EA90, type_info function 0x005EE6B0, structors 0x002F91F8, 0x002F9238, 0x002F92C8
 * vtable 0x00673D60: 49 slots
 * size: not known; the fields seen reach 0x14
 */
#ifndef GT4_hFloat_H
#define GT4_hFloat_H

#include "types.h"

struct hFloat {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    f32 unk10;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002F92C8  hFloat::~hFloat() [high]
 *   1: 0x0030B7C8
 *   2: 0x002F90B0
 *   3: 0x002F7C98  hFloat::rc_class() const [high]
 *   4: 0x002F7CA8  hFloat::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x002F7D20  hFloat::getClassID() const [high]
 *  10: 0x002F9340  hFloat::toInt() const [high]
 *  11: 0x002F9358  hFloat::toFloat() const [high]
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x002F9168  hFloat::copyPrimitive() const [high]
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x002F7D48
 *  22: 0x002F7DE0
 *  23: 0x002F7E78
 *  24: 0x002F7F10
 *  25: 0x002F7FD8
 *  26: 0x002F80A0
 *  27: 0x002F8140
 *  28: 0x002F81E8
 *  29: 0x002F8290  hFloat::op_ge(HObject&, HObject const&, int, HObject const*) [medium]
 *  30: 0x002F8338  hFloat::op_gt(HObject&, HObject const&, int, HObject const*) [medium]
 *  31: 0x002F83E0  hFloat::op_le(HObject&, HObject const&, int, HObject const*) [medium]
 *  32: 0x002F8488  hFloat::op_lt(HObject&, HObject const&, int, HObject const*) [medium]
 *  33: 0x002F8530  hFloat::op_mod(HObject&, HObject const&, int, HObject const*) [medium]
 *  34: 0x002F85B0  hFloat::op_mul(HObject&, HObject const&, int, HObject const*) [medium]
 *  35: 0x002F8668  hFloat::op_not(HObject&, HObject const&, int, HObject const*) [medium]
 *  36: 0x002F8720
 *  37: 0x002F8798
 *  38: 0x002F8808
 *  39: 0x002F8878
 *  40: 0x002F88E8
 *  41: 0x002F8970
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 */

#endif /* GT4_hFloat_H */
