/* gt4/HFrame.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class HFrame
 * type_info 0x006D5F40, type_info function 0x005F1A58, structors 0x005F0540, 0x005F0738, 0x005F07E8, 0x005F1A98
 * vtable 0x00676580: 3 slots
 * C++ (GT4_CXX): size 0x4 (not known: up to the last field seen), vptr at 0x0 (introduced here)
 */
#ifndef GT4_HFrame_H
#define GT4_HFrame_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
class hThread;

class HFrame {
public:
    virtual ~HFrame();  /* 0: HFrame::~HFrame() */
    virtual s32 getType() const;  /* 1: HTryCatchFrame::getType() const */
    virtual s32 end(hThread *);  /* 2: HTryCatchFrame::end(hThread*) */
};
#else
struct HFrame;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F1A98  HFrame::~HFrame() [high]
 *   1: 0x005BC5C0  HTryCatchFrame::getType() const [high]
 *   2: 0x005BC5C0  HTryCatchFrame::end(hThread*) [high]
 */

#endif /* GT4_HFrame_H */
