/* gt4/hFunctionValue.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hFunctionValue : hValue
 * type_info 0x0088EAB0, type_info function 0x005EE750, structors 0x002FA9D0, 0x002FAA00
 * vtable 0x00674090: 16 slots
 * size: not known; the fields seen reach 0xC
 * C++ (GT4_CXX): size 0xC (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_hFunctionValue_H
#define GT4_hFunctionValue_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hValue.h"
class HObject;

class hFunctionValue : public hValue {
public:
    virtual s32 call(void *, s32, const HObject *) const;  /* 14: hBuiltinFunction::call(HThread&, int, HObject const*) const */
    virtual s32 call(HObject &, s32, const HObject *) const;  /* 15: hBuiltinFunction::call(HObject&, int, HObject const*) const */
};
#else
struct hFunctionValue {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 hFunctionValue__rc_class(struct hFunctionValue *);
s32 hFunctionValue__rc_size(struct hFunctionValue *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002FAA00  hFunctionValue::~hFunctionValue() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x002FA928  hFunctionValue::rc_class() const [high]
 *   4: 0x002FA938  hFunctionValue::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x002FA940
 *   9: 0x002FA9B8
 *  10: 0x002FA9C8
 *  11: 0x002FA9C0
 *  12: 0x00323CF8
 *  13: 0x00323D00
 *  14: 0x005BC5C0  hBuiltinFunction::call(HThread&, int, HObject const*) const [high]
 *  15: 0x005BC5C0  hBuiltinFunction::call(HObject&, int, HObject const*) const [high]
 */

#endif /* GT4_hFunctionValue_H */
