/* gt4/hFunctionValue.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hFunctionValue : hValue
 * type_info 0x0088EAB0, type_info function 0x005EE750, structors 0x002FA9D0, 0x002FAA00
 * vtable 0x00674090: 16 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_hFunctionValue_H
#define GT4_hFunctionValue_H

#include "types.h"

struct hFunctionValue {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002FAA00  hFunctionValue::~hFunctionValue() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x002FA928  hFunctionValue::rc_class() const [high]
 *   4: 0x002FA938  hFunctionValue::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x002FA940
 *   9: 0x002FA9B8
 *  10: 0x002FA9C8
 *  11: 0x002FA9C0
 *  12: 0x00323CF8
 *  13: 0x00323D00
 *  14: 0x005BC5C0  hBuiltinFunction::call(HThread&, int, HObject const*) const [high]
 *  15: 0x005BC5C0  hBuiltinFunction::call(HObject&, int, HObject const*) const [high]
 */

#endif /* GT4_hFunctionValue_H */
