/* gt4/hInt.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hInt : hObject
 * type_info 0x0088EAD0, type_info function 0x005EE8B0, structors 0x002FE108, 0x002FE148, 0x002FE1D8
 * vtable 0x00674188: 49 slots
 * size: not known; the fields seen reach 0x14
 */
#ifndef GT4_hInt_H
#define GT4_hInt_H

#include "types.h"

struct hInt {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    union {
        s32 unk10;
        void *unk10_pvoid;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002FE1D8  hInt::~hInt() [high]
 *   1: 0x0030B7C8
 *   2: 0x002FDFB0  hInt::toString() const [high]
 *   3: 0x002FC9A0  hInt::rc_class() const [high]
 *   4: 0x002FC9B0  hInt::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x002FCA28  hInt::getClassID() const [high]
 *  10: 0x002FE260  hInt::toInt() const [high]
 *  11: 0x002FE268  hInt::toFloat() const [high]
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x002FE078  hInt::copyPrimitive() const [high]
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x002FCA50
 *  22: 0x002FCAE8
 *  23: 0x002FCB80
 *  24: 0x002FCC18
 *  25: 0x002FCCE0
 *  26: 0x002FCDA8
 *  27: 0x002FCE50
 *  28: 0x002FCEE8
 *  29: 0x002FCF80  hInt::op_ge(HObject&, HObject const&, int, HObject const*) [medium]
 *  30: 0x002FD018  hInt::op_gt(HObject&, HObject const&, int, HObject const*) [medium]
 *  31: 0x002FD0B0  hInt::op_le(HObject&, HObject const&, int, HObject const*) [medium]
 *  32: 0x002FD148  hInt::op_lt(HObject&, HObject const&, int, HObject const*) [medium]
 *  33: 0x002FD1E0  hInt::op_mod(HObject&, HObject const&, int, HObject const*) [medium]
 *  34: 0x002FD258  hInt::op_mul(HObject&, HObject const&, int, HObject const*) [medium]
 *  35: 0x002FD300  hInt::op_not(HObject&, HObject const&, int, HObject const*) [medium]
 *  36: 0x002FD398
 *  37: 0x002FD410
 *  38: 0x002FD468
 *  39: 0x002FD4D0
 *  40: 0x002FD538
 *  41: 0x002FD5B8
 *  42: 0x002FD638
 *  43: 0x002FD6D0
 *  44: 0x002FD768
 *  45: 0x002FD800
 *  46: 0x002FD898
 *  47: 0x002FD930
 *  48: 0x0030B278
 */

#endif /* GT4_hInt_H */
