/* gt4/hObject.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hObject : RefCounter
 * type_info 0x0088EB70, type_info function 0x005EFF90, structors 0x0030A678, 0x0030A6B0, 0x0030A908
 * vtable 0x00674F30: 49 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_hObject_H
#define GT4_hObject_H

#include "types.h"

struct hObject {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0030A908  hObject::~hObject() [high]
 *   1: 0x0030B7C8  hObject::cleanup() [high]
 *   2: 0x0030AA70  hObject::toString() const [high]
 *   3: 0x003093D0  hObject::rc_class() const [high]
 *   4: 0x003093E0  hObject::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888  hObject::deepCopy(hObject const*) [high]
 *   9: 0x00309CD0  hObject::getClassID() const [high]
 *  10: 0x0030B3F8  hObject::toInt() const [high]
 *  11: 0x0030B400  hObject::toFloat() const [high]
 *  12: 0x0030ACC8  hObject::getElement(unsigned int) const [medium]
 *  13: 0x0030AD30  hObject::getElement(unsigned int) [medium]
 *  14: 0x0030AD98  hObject::setElement(unsigned int, HObject const&) [high]
 *  15: 0x0030B2A0  hObject::copyPrimitive() const [high]
 *  16: 0x0030B2D0  hObject::evaluate(HObject&) const [high]
 *  17: 0x0030B348  hObject::assign(HObject const&) [high]
 *  18: 0x0030B350  hObject::isValid() const [high]
 *  19: 0x0030ABF8  hObject::call(HThread&, int, HObject const*) const [high]
 *  20: 0x0030ACC0  hObject::call(HObject&, int, HObject const*) const [high]
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80  hObject::op_ge(HObject&, HObject const&, int, HObject const*) [medium]
 *  30: 0x0030AFA8  hObject::op_gt(HObject&, HObject const&, int, HObject const*) [medium]
 *  31: 0x0030AFD0  hObject::op_le(HObject&, HObject const&, int, HObject const*) [medium]
 *  32: 0x0030AFF8  hObject::op_lt(HObject&, HObject const&, int, HObject const*) [medium]
 *  33: 0x0030B020  hObject::op_mod(HObject&, HObject const&, int, HObject const*) [medium]
 *  34: 0x0030B048  hObject::op_mul(HObject&, HObject const&, int, HObject const*) [medium]
 *  35: 0x0030B070  hObject::op_not(HObject&, HObject const&, int, HObject const*) [medium]
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 */

#endif /* GT4_hObject_H */
