/* gt4/hString.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class hString : hObject
 * type_info 0x0088EBB0, type_info function 0x005F0188, structors 0x003147D8, 0x00314858
 * vtable 0x00675268: 49 slots
 * size: not known; the fields seen reach 0x14
 * C++ (GT4_CXX): size 0x14 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x0, 0x4, 0x8, 0xC
 */
#ifndef GT4_hString_H
#define GT4_hString_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"
class hClass;

class hString : public hObject {
public:
    void * unk10;
    static s32 GetClassID();  /* 0x003124C0 */
    static s32 InitClass(hClass *);  /* 0x00313FF0 */
};
#else
struct hString {
    s32 unk0;
    union {
        void * unk4;
        void *unk4_pvoid;
        s32 unk4_s32;
    };
    s32 unk8;
    union {
        void * unkC;
        s32 unkC_s32;
    };
    void * unk10;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 hString__rc_class(struct hString *);
s32 hString__rc_size(struct hString *);
s32 hString__GetClassID(void);
s32 hString__getClassID(struct hString *);
s32 hString__InitClass(struct hClass *);
s32 hString__toInt(struct hString *);
f32 hString__toFloat(struct hString *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00314858  hString::~hString() [high]
 *   1: 0x0030B7C8
 *   2: 0x003149E0  hString::toString() const [high]
 *   3: 0x00312448  hString::rc_class() const [high]
 *   4: 0x00312458  hString::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x003124D0  hString::getClassID() const [high]
 *  10: 0x00314A40  hString::toInt() const [high]
 *  11: 0x00314A88  hString::toFloat() const [high]
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x003124F8
 *  22: 0x00312740
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x003128F8
 *  28: 0x00312A48
 *  29: 0x00312B98  hString::op_ge(HObject&, HObject const&, int, HObject const*) [medium]
 *  30: 0x00312CE8  hString::op_gt(HObject&, HObject const&, int, HObject const*) [medium]
 *  31: 0x00312E40  hString::op_le(HObject&, HObject const&, int, HObject const*) [medium]
 *  32: 0x00312F90  hString::op_lt(HObject&, HObject const&, int, HObject const*) [medium]
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 */

#endif /* GT4_hString_H */
