/* gt4/HSymID.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class HSymID
 * type_info 0x006D5E00, type_info function 0x005DBC00
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4_HSymID_H
#define GT4_HSymID_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class HSymID {
public:
    s32 GetID(const void *);  /* 0x003166B8 */
    s32 GetName(u32);  /* 0x003166D8 */
};
#else
struct HSymID;
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 HSymID__GetID(struct HSymID *, const void *);
s32 HSymID__GetName(struct HSymID *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

#endif /* GT4_HSymID_H */
