/* gt4/IfRootEvent.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class IfRootEvent : MEventFilter
 * type_info 0x0088E1F0, type_info function 0x005DB568, structors 0x0022F400
 * vtable 0x00665120: 2 slots
 * C++ (GT4_CXX): size 0x4 (not known: up to the last field seen), vptr at 0x0
 */
#ifndef GT4_IfRootEvent_H
#define GT4_IfRootEvent_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/MEventFilter.h"

class IfRootEvent : public MEventFilter {
public:
};
#else
struct IfRootEvent;
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 IfRootEvent__virtual_01(struct IfRootEvent *, void *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DB530
 *   1: 0x005DB5B8
 */

#endif /* GT4_IfRootEvent_H */
