/* gt4/LicenseConcourse.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class LicenseConcourse : Concourse
 * type_info 0x0088FA60, type_info function 0x005FF348, structors 0x00408948, 0x004089A8
 * vtable 0x00686360: 2 slots
 * size: not known; the fields seen reach 0x84
 */
#ifndef GT4_LicenseConcourse_H
#define GT4_LicenseConcourse_H

#include "types.h"

struct LicenseConcourse {
    char pad0[0x8];
    s32 unk8;
    s32 unkC;
    s32 unk10;
    char pad14[0x6C];
    s32 unk80;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00408DB0  LicenseConcourse::getSkinningBuffer() [high]
 *   1: 0x004089A8  LicenseConcourse::~LicenseConcourse() [high]
 */

#endif /* GT4_LicenseConcourse_H */
