/* gt4/mArrayPush.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mArrayPush : hInst
 * type_info 0x0088EE70, type_info function 0x005F0E68, structors 0x00319670
 * vtable 0x00676238: 11 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_mArrayPush_H
#define GT4_mArrayPush_H

#include "types.h"

struct mArrayPush {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    void *unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003196B0  mArrayPush::~mArrayPush() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x003195D0  mArrayPush::rc_class() const [high]
 *   4: 0x003195E0  mArrayPush::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x00319728  mArrayPush::execute(hThread*) [high]
 *   9: 0x00319830  mArrayPush::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mArrayPush_H */
