/* gt4/MboolReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MboolReader : MReaderBase
 * type_info 0x0088E310, type_info function 0x005DCF60, structors 0x0012A8D8, 0x0013B308, 0x00207590, 0x00210988, 0x00220A38, 0x00233E38, 0x002390E8, 0x00247768, 0x00261D38, 0x0027C3F8, 0x00292F18, 0x002A29F0, 0x002B3D50, 0x002BD568, 0x002C9DB0, 0x002D3A00, 0x002D75F0, 0x002DB4E8, 0x002DFA60, 0x005DCEF8, 0x005DCFB0
 * vtable 0x00666D50: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MboolReader_H
#define GT4_MboolReader_H

#include "types.h"

struct MboolReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DCEF8
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x0024DE80
 */

#endif /* GT4_MboolReader_H */
