/* gt4/mCarModel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mCarModel : hObject
 * type_info 0x0088DB40, type_info function 0x005CA210, structors 0x00151960, 0x00151A58
 * vtable 0x0065B5C0: 60 slots
 * size: not known; the fields seen reach 0x58
 * C++ (GT4_CXX): size 0x9C (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x8
 */
#ifndef GT4_mCarModel_H
#define GT4_mCarModel_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"
class hClass;

class mCarModel : public hObject {
public:
    char pad10[0x44];
    s32 unk54;
    char pad58[0x44];
    virtual s32 virtual_49(s32, s32, s32);  /* 49: parameters from the code */
    virtual s32 virtual_50(s32);  /* 50: parameters from the code */
    virtual s32 virtual_51(s32);  /* 51: parameters from the code */
    virtual s32 virtual_52();  /* 52: parameters from the code */
    virtual void virtual_53(s32);  /* 53: parameters from the code */
    virtual s32 virtual_54();  /* 54: parameters from the code */
    virtual f32 virtual_55();  /* 55: parameters from the code */
    virtual s32 virtual_56(s32);  /* 56: parameters from the code */
    virtual s32 virtual_57(s32, s32, s32, s32, s32, s32, s32);  /* 57: parameters from the code */
    virtual s32 virtual_58();  /* 58: parameters from the code */
    virtual void virtual_59(s32);  /* 59: parameters from the code */
    static s32 GetClassID();  /* 0x001517C8 */
    static s32 InitClass(hClass *);  /* 0x00152C50 */
};
#else
struct mCarModel {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x44];
    s32 unk54;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mCarModel__rc_class(struct mCarModel *);
s32 mCarModel__rc_size(struct mCarModel *);
s32 mCarModel__GetClassID(void);
s32 mCarModel__getClassID(struct mCarModel *);
s32 mCarModel__InitClass(struct hClass *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00151A58  mCarModel::~mCarModel() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x00151750  mCarModel::rc_class() const [high]
 *   4: 0x00151760  mCarModel::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x001517D8  mCarModel::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x005BC5C0
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x005BC5C0
 *  50: 0x005BC5C0
 *  51: 0x005BC5C0
 *  52: 0x005BC5C0
 *  53: 0x005CA308
 *  54: 0x005CA310
 *  55: 0x005BC5C0
 *  56: 0x005BC5C0
 *  57: 0x005BC5C0
 *  58: 0x005BC5C0
 *  59: 0x005BC5C0
 */

#endif /* GT4_mCarModel_H */
