/* gt4/mClassDefine.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mClassDefine : hInst
 * type_info 0x0088ED80, type_info function 0x005F1098, structors 0x0031B1F8, 0x0031B258
 * vtable 0x00675F60: 11 slots
 * size: not known; the fields seen reach 0x20
 * C++ (GT4_CXX): size 0x20 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mClassDefine_H
#define GT4_mClassDefine_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mClassDefine : public hInst {
public:
    s32 unk8;
    char padC[0x10];
    s32 unk1C;
};
#else
struct mClassDefine {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    s32 unk8;
    char padC[0x10];
    s32 unk1C;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mClassDefine__rc_class(struct mClassDefine *);
s32 mClassDefine__rc_size(struct mClassDefine *);
s32 mClassDefine__execute(struct mClassDefine *, struct hThread *);
s32 mClassDefine__read(struct mClassDefine *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031B258  mClassDefine::~mClassDefine() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031AD58  mClassDefine::rc_class() const [high]
 *   4: 0x0031AD68  mClassDefine::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031ADF8  mClassDefine::execute(hThread*) [high]
 *   9: 0x0031B110  mClassDefine::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mClassDefine_H */
