/* gt4/MColorReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MColorReader : MReaderBase
 * type_info 0x0088E040, type_info function 0x005D5660, structors 0x00203188, 0x002031A0
 * vtable 0x00662D30: 4 slots
 * size: not known; the fields seen reach 0x8
 * C++ (GT4_CXX): size 0x8 (not known: up to the last field seen), vptr at 0x0, fields left out (overlap, or in the base's part): 0x0
 */
#ifndef GT4_MColorReader_H
#define GT4_MColorReader_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/MReaderBase.h"

class MColorReader : public MReaderBase {
public:
    s32 unk4;
};
#else
struct MColorReader {
    s32 unk0;
    s32 unk4;
};
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002031A0
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x00203208
 */

#endif /* GT4_MColorReader_H */
