/* gt4/mDefine.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mDefine : hInst
 * type_info 0x0088EDF0, type_info function 0x005F0DF0, structors 0x003194F0
 * vtable 0x006762A0: 11 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_mDefine_H
#define GT4_mDefine_H

#include "types.h"

struct mDefine {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    s32 unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00319538  mDefine::~mDefine() [high]
 *   1: 0x00328500
 *   2: 0x00319420  mDefine::toString() const [high]
 *   3: 0x003192C0  mDefine::rc_class() const [high]
 *   4: 0x003192D0  mDefine::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x005BC5C0
 *   9: 0x00319360  mDefine::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mDefine_H */
