/* gt4/mDnas.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mDnas : hObject
 * type_info 0x0088E5E0, type_info function 0x005E57B0, structors 0x0028BF30, 0x0028BF68
 * vtable 0x0066AA40: 49 slots
 * size: not known; the fields seen reach 0x38
 * C++ (GT4_CXX): size 0x38 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8
 */
#ifndef GT4_mDnas_H
#define GT4_mDnas_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"

class mDnas : public hObject {
public:
    s32 unk10;
    char pad14[0x20];
    s32 unk34;
};
#else
struct mDnas {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    s32 unk8;
    s32 unkC;
    s32 unk10;
    char pad14[0x20];
    s32 unk34;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mDnas__virtual_03(struct mDnas *);
s32 mDnas__virtual_04(struct mDnas *);
s32 mDnas__virtual_09(struct mDnas *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0028BF68
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x0028BE80
 *   4: 0x0028BE90
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x0028BF08
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 */

#endif /* GT4_mDnas_H */
