/* gt4/mEval.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mEval : hInst
 * type_info 0x0088EC30, type_info function 0x005F10E8, structors 0x0031B470, 0x0031B5B8
 * vtable 0x00675EF8: 11 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_mEval_H
#define GT4_mEval_H

#include "types.h"

struct mEval {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031B470  mEval::~mEval() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031B378  mEval::rc_class() const [high]
 *   4: 0x0031B388  mEval::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031B418  mEval::execute(hThread*) [high]
 *   9: 0x0031B468  mEval::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mEval_H */
