/* gt4/mEyetoyPS2.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mEyetoyPS2 : mEyetoy
 * type_info 0x0088DE00, type_info function 0x005D08F0, structors 0x001BEF50, 0x001BEF90
 * vtable 0x006605C0: 86 slots
 * size: not known; the fields seen reach 0x20
 * C++ (GT4_CXX): size 0x20 (allocation, 1 site), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mEyetoyPS2_H
#define GT4_mEyetoyPS2_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/mEyetoy.h"

class mEyetoyPS2 : public mEyetoy {
public:
    union {
        s32 unk10;
        void *unk10_pvoid;
    };
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    union {
        s32 unk18;
        void *unk18_pvoid;
    };
    union {
        s32 unk1C;
        void *unk1C_pvoid;
    };
};
#else
struct mEyetoyPS2 {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    union {
        s32 unk10;
        void *unk10_pvoid;
    };
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    union {
        s32 unk18;
        void *unk18_pvoid;
    };
    union {
        s32 unk1C;
        void *unk1C_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mEyetoyPS2__virtual_49(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_50(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_51(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_52(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_53(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_54(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_55(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_56(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_57(struct mEyetoyPS2 *);
void mEyetoyPS2__virtual_58(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_59(struct mEyetoyPS2 *, const void *);
s32 mEyetoyPS2__virtual_60(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_61(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_62(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_63(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_64(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_65(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_66(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_67(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_68(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_69(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_70(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_71(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_72(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_73(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_74(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_75(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_76(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_77(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_78(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_79(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_80(struct mEyetoyPS2 *, s32);
s32 mEyetoyPS2__virtual_81(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_82(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_83(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_84(struct mEyetoyPS2 *);
s32 mEyetoyPS2__virtual_85(struct mEyetoyPS2 *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x001BEF90
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x001B6890
 *   4: 0x001B68A0
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x001B6918
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x001BF010
 *  50: 0x001BF058
 *  51: 0x001BF0A8
 *  52: 0x001BF0D0
 *  53: 0x001BF0F8
 *  54: 0x001BF120
 *  55: 0x001BF140
 *  56: 0x001BF158
 *  57: 0x001BF170
 *  58: 0x001BF188
 *  59: 0x001BF190
 *  60: 0x001BF1F8
 *  61: 0x001BF230
 *  62: 0x001BF258
 *  63: 0x001BF280
 *  64: 0x001BF2A8
 *  65: 0x001BF2D0
 *  66: 0x001BF2F8
 *  67: 0x001BF320
 *  68: 0x001BF348
 *  69: 0x001BF370
 *  70: 0x001BF398
 *  71: 0x001BF3C0
 *  72: 0x001BF3E0
 *  73: 0x001BF400
 *  74: 0x001BF428
 *  75: 0x001BF448
 *  76: 0x001BF468
 *  77: 0x001BF490
 *  78: 0x001BF4B0
 *  79: 0x001BF4D0
 *  80: 0x001BF4F8
 *  81: 0x001BF5F0
 *  82: 0x001BF5F8
 *  83: 0x001BF600
 *  84: 0x001BF618
 *  85: 0x001BF690
 */

#endif /* GT4_mEyetoyPS2_H */
