/* gt4/mEyetoy.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mEyetoy : hObject
 * type_info 0x0088DD90, type_info function 0x005CF248, structors 0x001B6940, 0x001B6970
 * vtable 0x0065F290: 86 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x10 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8
 */
#ifndef GT4_mEyetoy_H
#define GT4_mEyetoy_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"

class mEyetoy : public hObject {
public:
    virtual s32 initialize();  /* 49: mEyetoy::initialize() */
    virtual s32 finalize();  /* 50: mEyetoy::finalize() */
    virtual void start();  /* 51: mEyetoy::start() */
    virtual void stop();  /* 52: mEyetoy::stop() */
    virtual void update();  /* 53: mEyetoy::update() */
    virtual s32 isConnected() const;  /* 54: mEyetoy::isConnected() const */
    virtual s32 isCaptured() const;  /* 55: mEyetoy::isCaptured() const */
    virtual s32 getWidth() const;  /* 56: mEyetoy::getWidth() const */
    virtual s32 getHeight() const;  /* 57: mEyetoy::getHeight() const */
    virtual void setCamera(s32);  /* 58: mEyetoy::setCamera(int) */
    virtual void setResolution(const void *);  /* 59: mEyetoy::setResolution(std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&) */
    virtual void setSamplingSpeed(s32);  /* 60: mEyetoy::setSamplingSpeed(int) */
    virtual void setAutoBrightness(bool);  /* 61: mEyetoy::setAutoBrightness(bool) */
    virtual void setAutoExposure(bool);  /* 62: mEyetoy::setAutoExposure(bool) */
    virtual void setAutoGain(bool);  /* 63: mEyetoy::setAutoGain(bool) */
    virtual void setAudioGain(s32);  /* 64: mEyetoy::setAudioGain(int) */
    virtual void setAutoWhiteBalance(bool);  /* 65: mEyetoy::setAutoWhiteBalance(bool) */
    virtual void setBackLightComp(bool);  /* 66: mEyetoy::setBackLightComp(bool) */
    virtual void setBrightness(s32);  /* 67: mEyetoy::setBrightness(int) */
    virtual void setExposure(s32);  /* 68: mEyetoy::setExposure(int) */
    virtual void setGain(s32);  /* 69: mEyetoy::setGain(int) */
    virtual void setJpeg(bool);  /* 70: mEyetoy::setJpeg(bool) */
    virtual void setLedOn(s32);  /* 71: mEyetoy::setLedOn(int) */
    virtual void setLedOff(s32);  /* 72: mEyetoy::setLedOff(int) */
    virtual void setMirror(bool);  /* 73: mEyetoy::setMirror(bool) */
    virtual void setNzcLuminance(s32);  /* 74: mEyetoy::setNzcLuminance(int) */
    virtual void setNzcChrominance(s32);  /* 75: mEyetoy::setNzcChrominance(int) */
    virtual void setQS(s32);  /* 76: mEyetoy::setQS(int) */
    virtual void setRedGain(s32);  /* 77: mEyetoy::setRedGain(int) */
    virtual void setBlueGain(s32);  /* 78: mEyetoy::setBlueGain(int) */
    virtual void setSaturation(s32);  /* 79: mEyetoy::setSaturation(int) */
    virtual void setYUV(bool);  /* 80: mEyetoy::setYUV(bool) */
    virtual s32 getDecodeBuffer() const;  /* 81: mEyetoy::getDecodeBuffer() const */
    virtual s32 getFrameBuffer() const;  /* 82: mEyetoy::getFrameBuffer() const */
    virtual s32 getFrameNumber() const;  /* 83: mEyetoy::getFrameNumber() const */
    virtual void allocateBuffer();  /* 84: mEyetoy::allocateBuffer() */
    virtual void freeBuffer();  /* 85: mEyetoy::freeBuffer() */
    static s32 GetClassID();  /* 0x001B6908 */
};
#else
struct mEyetoy {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mEyetoy__rc_class(struct mEyetoy *);
s32 mEyetoy__rc_size(struct mEyetoy *);
s32 mEyetoy__GetClassID(void);
s32 mEyetoy__getClassID(struct mEyetoy *);
void mEyetoy__initialize(struct mEyetoy *);
void mEyetoy__finalize(struct mEyetoy *);
void mEyetoy__start(struct mEyetoy *);
void mEyetoy__stop(struct mEyetoy *);
void mEyetoy__update(struct mEyetoy *);
s32 mEyetoy__isConnected(struct mEyetoy *);
s32 mEyetoy__isCaptured(struct mEyetoy *);
s32 mEyetoy__getWidth(struct mEyetoy *);
s32 mEyetoy__getHeight(struct mEyetoy *);
void mEyetoy__setCamera(struct mEyetoy *, s32);
void mEyetoy__setResolution(struct mEyetoy *, const void *);
void mEyetoy__setSamplingSpeed(struct mEyetoy *, s32);
void mEyetoy__setAutoBrightness(struct mEyetoy *, s32);
void mEyetoy__setAutoExposure(struct mEyetoy *, s32);
void mEyetoy__setAutoGain(struct mEyetoy *, s32);
void mEyetoy__setAudioGain(struct mEyetoy *, s32);
void mEyetoy__setAutoWhiteBalance(struct mEyetoy *, s32);
void mEyetoy__setBackLightComp(struct mEyetoy *, s32);
void mEyetoy__setBrightness(struct mEyetoy *, s32);
void mEyetoy__setExposure(struct mEyetoy *, s32);
void mEyetoy__setGain(struct mEyetoy *, s32);
void mEyetoy__setJpeg(struct mEyetoy *, s32);
void mEyetoy__setLedOn(struct mEyetoy *, s32);
void mEyetoy__setLedOff(struct mEyetoy *, s32);
void mEyetoy__setMirror(struct mEyetoy *, s32);
void mEyetoy__setNzcLuminance(struct mEyetoy *, s32);
void mEyetoy__setNzcChrominance(struct mEyetoy *, s32);
void mEyetoy__setQS(struct mEyetoy *, s32);
void mEyetoy__setRedGain(struct mEyetoy *, s32);
void mEyetoy__setBlueGain(struct mEyetoy *, s32);
void mEyetoy__setSaturation(struct mEyetoy *, s32);
void mEyetoy__setYUV(struct mEyetoy *, s32);
s32 mEyetoy__getDecodeBuffer(struct mEyetoy *);
s32 mEyetoy__getFrameBuffer(struct mEyetoy *);
s32 mEyetoy__getFrameNumber(struct mEyetoy *);
void mEyetoy__allocateBuffer(struct mEyetoy *);
void mEyetoy__freeBuffer(struct mEyetoy *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x001B6970  mEyetoy::~mEyetoy() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x001B6890  mEyetoy::rc_class() const [high]
 *   4: 0x001B68A0  mEyetoy::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x001B6918  mEyetoy::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x001B69E8  mEyetoy::initialize() [high]
 *  50: 0x001B69F0  mEyetoy::finalize() [high]
 *  51: 0x001B69F8  mEyetoy::start() [high]
 *  52: 0x001B6A00  mEyetoy::stop() [high]
 *  53: 0x001B6A08  mEyetoy::update() [high]
 *  54: 0x001B6A10  mEyetoy::isConnected() const [high]
 *  55: 0x001B6A18  mEyetoy::isCaptured() const [high]
 *  56: 0x001B6A20  mEyetoy::getWidth() const [high]
 *  57: 0x001B6A28  mEyetoy::getHeight() const [high]
 *  58: 0x001B6A30  mEyetoy::setCamera(int) [high]
 *  59: 0x001B6A38  mEyetoy::setResolution(std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&) [high]
 *  60: 0x001B6A40  mEyetoy::setSamplingSpeed(int) [high]
 *  61: 0x001B6A48  mEyetoy::setAutoBrightness(bool) [high]
 *  62: 0x001B6A50  mEyetoy::setAutoExposure(bool) [high]
 *  63: 0x001B6A58  mEyetoy::setAutoGain(bool) [high]
 *  64: 0x001B6A60  mEyetoy::setAudioGain(int) [high]
 *  65: 0x001B6A68  mEyetoy::setAutoWhiteBalance(bool) [high]
 *  66: 0x001B6A70  mEyetoy::setBackLightComp(bool) [high]
 *  67: 0x001B6A78  mEyetoy::setBrightness(int) [high]
 *  68: 0x001B6A80  mEyetoy::setExposure(int) [high]
 *  69: 0x001B6A88  mEyetoy::setGain(int) [high]
 *  70: 0x001B6A90  mEyetoy::setJpeg(bool) [high]
 *  71: 0x001B6A98  mEyetoy::setLedOn(int) [high]
 *  72: 0x001B6AA0  mEyetoy::setLedOff(int) [high]
 *  73: 0x001B6AA8  mEyetoy::setMirror(bool) [high]
 *  74: 0x001B6AB0  mEyetoy::setNzcLuminance(int) [high]
 *  75: 0x001B6AB8  mEyetoy::setNzcChrominance(int) [high]
 *  76: 0x001B6AC0  mEyetoy::setQS(int) [high]
 *  77: 0x001B6AC8  mEyetoy::setRedGain(int) [high]
 *  78: 0x001B6AD0  mEyetoy::setBlueGain(int) [high]
 *  79: 0x001B6AD8  mEyetoy::setSaturation(int) [high]
 *  80: 0x001B6AE0  mEyetoy::setYUV(bool) [high]
 *  81: 0x001B6AE8  mEyetoy::getDecodeBuffer() const [high]
 *  82: 0x001B6AF0  mEyetoy::getFrameBuffer() const [high]
 *  83: 0x001B6AF8  mEyetoy::getFrameNumber() const [high]
 *  84: 0x001B6B00  mEyetoy::allocateBuffer() [high]
 *  85: 0x001B6B08  mEyetoy::freeBuffer() [high]
 */

#endif /* GT4_mEyetoy_H */
