/* gt4/mFunctionDefine.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mFunctionDefine : mDefine
 * type_info 0x0088ED70, type_info function 0x005F1188, structors 0x0031BAB8, 0x0031BB00
 * vtable 0x00675E28: 11 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_mFunctionDefine_H
#define GT4_mFunctionDefine_H

#include "types.h"

struct mFunctionDefine {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031BB00  mFunctionDefine::~mFunctionDefine() [high]
 *   1: 0x00328500
 *   2: 0x00319420
 *   3: 0x0031B868  mFunctionDefine::rc_class() const [high]
 *   4: 0x0031B878  mFunctionDefine::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031B908  mFunctionDefine::execute(hThread*) [high]
 *   9: 0x0031B978  mFunctionDefine::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mFunctionDefine_H */
