/* gt4/mGTShirt.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mGTShirt : mEyetoyImageProcessor
 * type_info 0x0088DDC0, type_info function 0x005D0248, structors 0x001BA528, 0x001BA558
 * vtable 0x0065FA28: 77 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x10 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8
 */
#ifndef GT4_mGTShirt_H
#define GT4_mGTShirt_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/mEyetoyImageProcessor.h"
class HObject;
class hClass;

class mGTShirt : public mEyetoyImageProcessor {
public:
    virtual s32 clear();  /* 55: mGTShirt::clear() */
    virtual s32 getThreshold() const;  /* 56: mGTShirt::getThreshold() const */
    virtual void setThreshold(s32);  /* 57: mGTShirt::setThreshold(int) */
    virtual s32 getThresholdCr() const;  /* 58: mGTShirt::getThresholdCr() const */
    virtual void setThresholdCr(s32);  /* 59: mGTShirt::setThresholdCr(int) */
    virtual f32 getThresholdLScanBase() const;  /* 60: mGTShirt::getThresholdLScanBase() const */
    virtual void setThresholdLScanBase(f32);  /* 61: mGTShirt::setThresholdLScanBase(float) */
    virtual f32 getThresholdLScanStep() const;  /* 62: mGTShirt::getThresholdLScanStep() const */
    virtual void setThresholdLScanStep(f32);  /* 63: mGTShirt::setThresholdLScanStep(float) */
    virtual f32 getThresholdPatternBase() const;  /* 64: mGTShirt::getThresholdPatternBase() const */
    virtual void setThresholdPatternBase(f32);  /* 65: mGTShirt::setThresholdPatternBase(float) */
    virtual f32 getThresholdPatternStep() const;  /* 66: mGTShirt::getThresholdPatternStep() const */
    virtual void setThresholdPatternStep(f32);  /* 67: mGTShirt::setThresholdPatternStep(float) */
    virtual f32 setLedStartDelay(f32);  /* 68: mGTShirt::setLedStartDelay(float) */
    virtual f32 setLedInterval(f32);  /* 69: mGTShirt::setLedInterval(float) */
    virtual void setRefrectCount(s32);  /* 70: mGTShirt::setRefrectCount(int) */
    virtual void setFocusWidget(const HObject &);  /* 71: mGTShirt::setFocusWidget(HObject const&) */
    virtual s32 getRecognizing() const;  /* 72: mGTShirt::getRecognizing() const */
    virtual void setRecognizing(bool);  /* 73: mGTShirt::setRecognizing(bool) */
    virtual s32 getFound() const;  /* 74: mGTShirt::getFound() const */
    virtual s32 getRecognized() const;  /* 75: mGTShirt::getRecognized() const */
    virtual void setDebug(s32);  /* 76: mGTShirt::setDebug(int) */
    static s32 GetClassID();  /* 0x001BA4F0 */
    static s32 InitClass(hClass *);  /* 0x001BA6A0 */
};
#else
struct mGTShirt {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mGTShirt__rc_class(struct mGTShirt *);
s32 mGTShirt__rc_size(struct mGTShirt *);
s32 mGTShirt__GetClassID(void);
s32 mGTShirt__getClassID(struct mGTShirt *);
void mGTShirt__clear(struct mGTShirt *);
s32 mGTShirt__getThreshold(struct mGTShirt *);
void mGTShirt__setThreshold(struct mGTShirt *, s32);
s32 mGTShirt__getThresholdCr(struct mGTShirt *);
void mGTShirt__setThresholdCr(struct mGTShirt *, s32);
f32 mGTShirt__getThresholdLScanBase(struct mGTShirt *);
void mGTShirt__setThresholdLScanBase(struct mGTShirt *, f32);
f32 mGTShirt__getThresholdLScanStep(struct mGTShirt *);
void mGTShirt__setThresholdLScanStep(struct mGTShirt *, f32);
f32 mGTShirt__getThresholdPatternBase(struct mGTShirt *);
void mGTShirt__setThresholdPatternBase(struct mGTShirt *, f32);
f32 mGTShirt__getThresholdPatternStep(struct mGTShirt *);
void mGTShirt__setThresholdPatternStep(struct mGTShirt *, f32);
void mGTShirt__setLedStartDelay(struct mGTShirt *, f32);
void mGTShirt__setLedInterval(struct mGTShirt *, f32);
void mGTShirt__setRefrectCount(struct mGTShirt *, s32);
void mGTShirt__setFocusWidget(struct mGTShirt *, const struct HObject *);
s32 mGTShirt__getRecognizing(struct mGTShirt *);
void mGTShirt__setRecognizing(struct mGTShirt *, s32);
s32 mGTShirt__getFound(struct mGTShirt *);
s32 mGTShirt__getRecognized(struct mGTShirt *);
void mGTShirt__setDebug(struct mGTShirt *, s32);
s32 mGTShirt__InitClass(struct hClass *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x001BA558  mGTShirt::~mGTShirt() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x001BA478  mGTShirt::rc_class() const [high]
 *   4: 0x001BA488  mGTShirt::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x001BA500  mGTShirt::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x001B9A50
 *  50: 0x001B9A58
 *  51: 0x001B9A60
 *  52: 0x001B9A68
 *  53: 0x001B9A70
 *  54: 0x001B9A78
 *  55: 0x001BA5D0  mGTShirt::clear() [high]
 *  56: 0x001BA5D8  mGTShirt::getThreshold() const [high]
 *  57: 0x001BA5E0  mGTShirt::setThreshold(int) [high]
 *  58: 0x001BA5E8  mGTShirt::getThresholdCr() const [high]
 *  59: 0x001BA5F0  mGTShirt::setThresholdCr(int) [high]
 *  60: 0x001BA5F8  mGTShirt::getThresholdLScanBase() const [high]
 *  61: 0x001BA608  mGTShirt::setThresholdLScanBase(float) [high]
 *  62: 0x001BA610  mGTShirt::getThresholdLScanStep() const [high]
 *  63: 0x001BA620  mGTShirt::setThresholdLScanStep(float) [high]
 *  64: 0x001BA628  mGTShirt::getThresholdPatternBase() const [high]
 *  65: 0x001BA638  mGTShirt::setThresholdPatternBase(float) [high]
 *  66: 0x001BA640  mGTShirt::getThresholdPatternStep() const [high]
 *  67: 0x001BA650  mGTShirt::setThresholdPatternStep(float) [high]
 *  68: 0x001BA658  mGTShirt::setLedStartDelay(float) [high]
 *  69: 0x001BA660  mGTShirt::setLedInterval(float) [high]
 *  70: 0x001BA668  mGTShirt::setRefrectCount(int) [high]
 *  71: 0x001BA670  mGTShirt::setFocusWidget(HObject const&) [high]
 *  72: 0x001BA678  mGTShirt::getRecognizing() const [high]
 *  73: 0x001BA680  mGTShirt::setRecognizing(bool) [high]
 *  74: 0x001BA688  mGTShirt::getFound() const [high]
 *  75: 0x001BA690  mGTShirt::getRecognized() const [high]
 *  76: 0x001BA698  mGTShirt::setDebug(int) [high]
 */

#endif /* GT4_mGTShirt_H */
