/* gt4/mImport.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mImport : hInst
 * type_info 0x0088EC00, type_info function 0x005F11D8, structors 0x0031BE10, 0x0031BE70
 * vtable 0x00675DC0: 11 slots
 * size: not known; the fields seen reach 0x1C
 * C++ (GT4_CXX): size 0x1C (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mImport_H
#define GT4_mImport_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mImport : public hInst {
public:
    char pad8[0x10];
    s32 unk18;
};
#else
struct mImport {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    char pad8[0x10];
    s32 unk18;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mImport__rc_class(struct mImport *);
s32 mImport__rc_size(struct mImport *);
s32 mImport__execute(struct mImport *, struct hThread *);
s32 mImport__read(struct mImport *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031BE70  mImport::~mImport() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031BC00  mImport::rc_class() const [high]
 *   4: 0x0031BC10  mImport::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031BCA0  mImport::execute(hThread*) [high]
 *   9: 0x0031BD40  mImport::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mImport_H */
