/* gt4/mImport.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mImport : hInst
 * type_info 0x0088EC00, type_info function 0x005F11D8, structors 0x0031BE10, 0x0031BE70
 * vtable 0x00675DC0: 11 slots
 * size: not known; the fields seen reach 0x1C
 */
#ifndef GT4_mImport_H
#define GT4_mImport_H

#include "types.h"

struct mImport {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    char pad8[0x10];
    s32 unk18;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031BE70  mImport::~mImport() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031BC00  mImport::rc_class() const [high]
 *   4: 0x0031BC10  mImport::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031BCA0  mImport::execute(hThread*) [high]
 *   9: 0x0031BD40  mImport::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mImport_H */
