/* gt4/MintReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MintReader : MReaderBase
 * type_info 0x0088E300, type_info function 0x005DCE90, structors 0x0013B308, 0x0021B848, 0x00220A38, 0x002390E8, 0x002463A0, 0x00247768, 0x00261DA0, 0x00285CC8, 0x00288988, 0x0029F7E8, 0x002A8568, 0x002AD1D8, 0x002B3D50, 0x002B8CA0, 0x002BD568, 0x002D4990, 0x002D75F0, 0x002DB4E8, 0x002DFA60, 0x005DCE28, 0x005DCEE0, 0x005E72A0, 0x005E72F8
 * vtable 0x00666D80: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MintReader_H
#define GT4_MintReader_H

#include "types.h"

struct MintReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DCE28
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x0024DD40
 */

#endif /* GT4_MintReader_H */
