/* gt4/mJump.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mJump : hInst
 * type_info 0x0088EC60, type_info function 0x005F1278, structors 0x0031C2F8
 * vtable 0x00675CF0: 11 slots
 * size: not known; the fields seen reach 0xC
 * C++ (GT4_CXX): size 0xC (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mJump_H
#define GT4_mJump_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mJump : public hInst {
public:
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
};
#else
struct mJump {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mJump__rc_class(struct mJump *);
s32 mJump__rc_size(struct mJump *);
s32 mJump__execute(struct mJump *, struct hThread *);
s32 mJump__read(struct mJump *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031C338  mJump::~mJump() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031C200  mJump::rc_class() const [high]
 *   4: 0x0031C210  mJump::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031C2A0  mJump::execute(hThread*) [high]
 *   9: 0x0031C2D0  mJump::read(HIO&, unsigned int) [high]
 *  10: 0x005F12C8
 */

#endif /* GT4_mJump_H */
