/* gt4/mJumpZero.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mJumpZero : hInst
 * type_info 0x0088ECE0, type_info function 0x005F1338, structors 0x0031C738
 * vtable 0x00675C20: 11 slots
 * size: not known; the fields seen reach 0xC
 * C++ (GT4_CXX): size 0xC (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mJumpZero_H
#define GT4_mJumpZero_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mJumpZero : public hInst {
public:
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
};
#else
struct mJumpZero {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mJumpZero__rc_class(struct mJumpZero *);
s32 mJumpZero__rc_size(struct mJumpZero *);
s32 mJumpZero__execute(struct mJumpZero *, struct hThread *);
s32 mJumpZero__read(struct mJumpZero *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031C778  mJumpZero::~mJumpZero() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031C698  mJumpZero::rc_class() const [high]
 *   4: 0x0031C6A8  mJumpZero::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031C858  mJumpZero::execute(hThread*) [high]
 *   9: 0x0031C8F0  mJumpZero::read(HIO&, unsigned int) [high]
 *  10: 0x005F1388
 */

#endif /* GT4_mJumpZero_H */
