/* gt4/mLocalizedText.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mLocalizedText : RefCounter
 * type_info 0x0088E7E0, type_info function 0x005E8650, structors 0x002B6F00, 0x002B6FB8
 * vtable 0x0066E840: 9 slots
 * size: not known; the fields seen reach 0x8
 * C++ (GT4_CXX): size 0x10 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mLocalizedText_H
#define GT4_mLocalizedText_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RefCounter.h"

class mLocalizedText : public RefCounter {
public:
    char pad8[0x8];
    virtual s32 virtual_8(s32);  /* 8: GT HD (medium): mLocalizedText::deepCopy(mLocalizedText const*); parameters from the code */
};
#else
struct mLocalizedText {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mLocalizedText__rc_class(struct mLocalizedText *);
s32 mLocalizedText__rc_size(struct mLocalizedText *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002B6FB8  mLocalizedText::~mLocalizedText() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x002B6E60  mLocalizedText::rc_class() const [high]
 *   4: 0x002B6E70  mLocalizedText::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x002B7878  mLocalizedText::deepCopy(mLocalizedText const*) [medium]
 */

#endif /* GT4_mLocalizedText_H */
