/* gt4/MModel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MModel
 * type_info 0x006D5EB8, type_info function 0x005DA320, structors 0x0021A6B8, 0x0021A728
 * vtable 0x00664040: 9 slots
 * C++ (GT4_CXX): size 0x4C (not known: up to the last field seen), vptr at 0x48 (introduced here)
 */
#ifndef GT4_MModel_H
#define GT4_MModel_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
class mRenderContext;

class MModel {
public:
    char pad0[0x48];
    virtual ~MModel();  /* 0: MModel::~MModel() */
    virtual s32 virtual_1(s32);  /* 1: GT HD (medium): MModel::applyLightSetting(bool); parameters from the code */
    virtual s32 virtual_2();  /* 2: GT HD (medium): MModel::applyCameraSetting(); parameters from the code */
    virtual s32 virtual_3();  /* 3: GT HD (medium): MModel::applyTransform(); parameters from the code */
    virtual s32 virtual_4(s32);  /* 4: GT HD (medium): MModel::applyRender(bool); parameters from the code */
    virtual void initialize(mRenderContext *);  /* 5: MModel::initialize(mRenderContext*) */
    virtual void finalize(mRenderContext *);  /* 6: MModel::finalize(mRenderContext*) */
    virtual void update(mRenderContext *);  /* 7: MModel::update(mRenderContext*) */
    virtual s32 render(mRenderContext *);  /* 8: MModel::render(mRenderContext*) */
};
#else
struct MModel;
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 MModel__render(struct MModel *, struct mRenderContext *);
void MModel__initialize(struct MModel *, struct mRenderContext *);
void MModel__finalize(struct MModel *, struct mRenderContext *);
void MModel__update(struct MModel *, struct mRenderContext *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0021A728  MModel::~MModel() [high]
 *   1: 0x0021A878  MModel::applyLightSetting(bool) [medium]
 *   2: 0x0021AA30  MModel::applyCameraSetting() [medium]
 *   3: 0x0021AB38  MModel::applyTransform() [medium]
 *   4: 0x0021ABA0  MModel::applyRender(bool) [medium]
 *   5: 0x005DA360  MModel::initialize(mRenderContext*) [high]
 *   6: 0x005DA368  MModel::finalize(mRenderContext*) [high]
 *   7: 0x005DA370  MModel::update(mRenderContext*) [high]
 *   8: 0x0021ABE0  MModel::render(mRenderContext*) [high]
 */

#endif /* GT4_MModel_H */
