/* gt4/mModuleDefine.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mModuleDefine : hInst
 * type_info 0x0088ED40, type_info function 0x005F1548, structors 0x0031DF88, 0x0031DFD8
 * vtable 0x006759B0: 11 slots
 * size: not known; the fields seen reach 0x1C
 */
#ifndef GT4_mModuleDefine_H
#define GT4_mModuleDefine_H

#include "types.h"

struct mModuleDefine {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    char pad8[0x10];
    s32 unk18;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031DFD8  mModuleDefine::~mModuleDefine() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031DC70  mModuleDefine::rc_class() const [high]
 *   4: 0x0031DC80  mModuleDefine::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031DD10  mModuleDefine::execute(hThread*) [high]
 *   9: 0x0031DF68  mModuleDefine::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mModuleDefine_H */
