/* gt4/mMovie.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mMovie : RefCounter
 * type_info 0x0088E170, type_info function 0x005DA4B8, structors 0x0021D880, 0x0021D8B0
 * vtable 0x006642E8: 20 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_mMovie_H
#define GT4_mMovie_H

#include "types.h"

struct mMovie {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0021D8B0  mMovie::~mMovie() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0021D7E0  mMovie::rc_class() const [high]
 *   4: 0x0021D7F0  mMovie::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x005BC5C0
 *   9: 0x005BC5C0
 *  10: 0x005BC5C0
 *  11: 0x005BC5C0
 *  12: 0x005BC5C0
 *  13: 0x005BC5C0
 *  14: 0x005BC5C0
 *  15: 0x005BC5C0
 *  16: 0x005BC5C0
 *  17: 0x005BC5C0
 *  18: 0x005BC5C0
 *  19: 0x005BC5C0
 */

#endif /* GT4_mMovie_H */
