/* gt4/mNetConf.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mNetConf : hObject
 * type_info 0x0088E190, type_info function 0x005DA840, structors 0x00221CB0, 0x00221CE8, 0x00221E00
 * vtable 0x006646A0: 104 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x268 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8
 */
#ifndef GT4_mNetConf_H
#define GT4_mNetConf_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"

class mNetConf : public hObject {
public:
    char pad10[0x258];
    virtual s32 virtual_49();  /* 49: parameters from the code */
    virtual void virtual_50(s32);  /* 50: parameters from the code */
    virtual s32 virtual_51();  /* 51: parameters from the code */
    virtual void virtual_52(s32);  /* 52: parameters from the code */
    virtual s32 virtual_53();  /* 53: parameters from the code */
    virtual void virtual_54(s32);  /* 54: parameters from the code */
    virtual s32 virtual_55();  /* 55: parameters from the code */
    virtual void virtual_56(s32);  /* 56: parameters from the code */
    virtual s32 virtual_57();  /* 57: parameters from the code */
    virtual void virtual_58(s32);  /* 58: parameters from the code */
    virtual s32 virtual_59();  /* 59: parameters from the code */
    virtual void virtual_60(s32);  /* 60: parameters from the code */
    virtual s32 virtual_61();  /* 61: parameters from the code */
    virtual s32 virtual_62();  /* 62: parameters from the code */
    virtual s32 virtual_63();  /* 63: parameters from the code */
    virtual s32 virtual_64();  /* 64: parameters from the code */
    virtual s32 virtual_65();  /* 65: parameters from the code */
    virtual s32 virtual_66();  /* 66: parameters from the code */
    virtual s32 virtual_67();  /* 67: parameters from the code */
    virtual s32 virtual_68();  /* 68: parameters from the code */
    virtual s32 virtual_69();  /* 69: parameters from the code */
    virtual s32 virtual_70();  /* 70: parameters from the code */
    virtual s32 virtual_71();  /* 71: parameters from the code */
    virtual s32 virtual_72();  /* 72: parameters from the code */
    virtual s32 virtual_73();  /* 73: parameters from the code */
    virtual s32 virtual_74();  /* 74: parameters from the code */
    virtual s32 virtual_75();  /* 75: parameters from the code */
    virtual s32 virtual_76();  /* 76: parameters from the code */
    virtual s32 virtual_77();  /* 77: parameters from the code */
    virtual s32 virtual_78();  /* 78: parameters from the code */
    virtual s32 virtual_79();  /* 79: parameters from the code */
    virtual void virtual_80(s32);  /* 80: parameters from the code */
    virtual s32 virtual_81();  /* 81: parameters from the code */
    virtual s32 virtual_82(s32, s32);  /* 82: parameters from the code */
    virtual s32 virtual_83();  /* 83: parameters from the code */
    virtual s32 virtual_84(s32, s32);  /* 84: parameters from the code */
    virtual s32 virtual_85(s32, s32);  /* 85: parameters from the code */
    virtual s32 virtual_86(s32, s32);  /* 86: parameters from the code */
    virtual s32 virtual_87(s32, s32);  /* 87: parameters from the code */
    virtual s32 virtual_88(s32, s32);  /* 88: parameters from the code */
    virtual s32 virtual_89(s32, s32);  /* 89: parameters from the code */
    virtual s32 virtual_90(s32, s32);  /* 90: parameters from the code */
    virtual s32 virtual_91(s32);  /* 91: parameters from the code */
    virtual s32 virtual_92(s32);  /* 92: parameters from the code */
    virtual s32 virtual_93(s32, s32, s32);  /* 93: parameters from the code */
    virtual s32 virtual_94(s32, s32, s32, s32);  /* 94: parameters from the code */
    virtual s32 virtual_95(s32, s32, s32);  /* 95: parameters from the code */
    virtual s32 virtual_96(s32, s32);  /* 96: parameters from the code */
    virtual s32 virtual_97(s32);  /* 97: parameters from the code */
    virtual s32 virtual_98();  /* 98: parameters from the code */
    virtual s32 virtual_99();  /* 99: parameters from the code */
    virtual s32 virtual_100(s32, s32);  /* 100: parameters from the code */
    virtual s32 virtual_101(s32, s32);  /* 101: parameters from the code */
    virtual s32 virtual_102(s32, s32);  /* 102: parameters from the code */
    virtual s32 virtual_103();  /* 103: parameters from the code */
    static s32 GetClassID();  /* 0x00221C78 */
};
#else
struct mNetConf {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mNetConf__rc_class(struct mNetConf *);
s32 mNetConf__rc_size(struct mNetConf *);
s32 mNetConf__GetClassID(void);
s32 mNetConf__getClassID(struct mNetConf *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00221E00  mNetConf::~mNetConf() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x00221C00  mNetConf::rc_class() const [high]
 *   4: 0x00221C10  mNetConf::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x00221C88  mNetConf::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x005BC5C0
 *  50: 0x005BC5C0
 *  51: 0x005BC5C0
 *  52: 0x005BC5C0
 *  53: 0x005BC5C0
 *  54: 0x005BC5C0
 *  55: 0x005BC5C0
 *  56: 0x005BC5C0
 *  57: 0x005BC5C0
 *  58: 0x005BC5C0
 *  59: 0x005BC5C0
 *  60: 0x005BC5C0
 *  61: 0x005BC5C0
 *  62: 0x005BC5C0
 *  63: 0x005BC5C0
 *  64: 0x005BC5C0
 *  65: 0x005BC5C0
 *  66: 0x005BC5C0
 *  67: 0x005BC5C0
 *  68: 0x005BC5C0
 *  69: 0x005BC5C0
 *  70: 0x005BC5C0
 *  71: 0x005BC5C0
 *  72: 0x005BC5C0
 *  73: 0x005BC5C0
 *  74: 0x005BC5C0
 *  75: 0x005BC5C0
 *  76: 0x005BC5C0
 *  77: 0x005BC5C0
 *  78: 0x005BC5C0
 *  79: 0x005BC5C0
 *  80: 0x005BC5C0
 *  81: 0x005BC5C0
 *  82: 0x005BC5C0
 *  83: 0x005BC5C0
 *  84: 0x005BC5C0
 *  85: 0x005BC5C0
 *  86: 0x005BC5C0
 *  87: 0x005BC5C0
 *  88: 0x005BC5C0
 *  89: 0x005BC5C0
 *  90: 0x005BC5C0
 *  91: 0x005BC5C0
 *  92: 0x005BC5C0
 *  93: 0x005BC5C0
 *  94: 0x005BC5C0
 *  95: 0x005BC5C0
 *  96: 0x005BC5C0
 *  97: 0x005BC5C0
 *  98: 0x005BC5C0
 *  99: 0x005BC5C0
 * 100: 0x005BC5C0
 * 101: 0x005BC5C0
 * 102: 0x005BC5C0
 * 103: 0x005BC5C0
 */

#endif /* GT4_mNetConf_H */
