/* gt4/mNetConf.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mNetConf : hObject
 * type_info 0x0088E190, type_info function 0x005DA840, structors 0x00221CB0, 0x00221CE8, 0x00221E00
 * vtable 0x006646A0: 104 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_mNetConf_H
#define GT4_mNetConf_H

#include "types.h"

struct mNetConf {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00221E00  mNetConf::~mNetConf() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x00221C00  mNetConf::rc_class() const [high]
 *   4: 0x00221C10  mNetConf::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x00221C88  mNetConf::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x005BC5C0
 *  50: 0x005BC5C0
 *  51: 0x005BC5C0
 *  52: 0x005BC5C0
 *  53: 0x005BC5C0
 *  54: 0x005BC5C0
 *  55: 0x005BC5C0
 *  56: 0x005BC5C0
 *  57: 0x005BC5C0
 *  58: 0x005BC5C0
 *  59: 0x005BC5C0
 *  60: 0x005BC5C0
 *  61: 0x005BC5C0
 *  62: 0x005BC5C0
 *  63: 0x005BC5C0
 *  64: 0x005BC5C0
 *  65: 0x005BC5C0
 *  66: 0x005BC5C0
 *  67: 0x005BC5C0
 *  68: 0x005BC5C0
 *  69: 0x005BC5C0
 *  70: 0x005BC5C0
 *  71: 0x005BC5C0
 *  72: 0x005BC5C0
 *  73: 0x005BC5C0
 *  74: 0x005BC5C0
 *  75: 0x005BC5C0
 *  76: 0x005BC5C0
 *  77: 0x005BC5C0
 *  78: 0x005BC5C0
 *  79: 0x005BC5C0
 *  80: 0x005BC5C0
 *  81: 0x005BC5C0
 *  82: 0x005BC5C0
 *  83: 0x005BC5C0
 *  84: 0x005BC5C0
 *  85: 0x005BC5C0
 *  86: 0x005BC5C0
 *  87: 0x005BC5C0
 *  88: 0x005BC5C0
 *  89: 0x005BC5C0
 *  90: 0x005BC5C0
 *  91: 0x005BC5C0
 *  92: 0x005BC5C0
 *  93: 0x005BC5C0
 *  94: 0x005BC5C0
 *  95: 0x005BC5C0
 *  96: 0x005BC5C0
 *  97: 0x005BC5C0
 *  98: 0x005BC5C0
 *  99: 0x005BC5C0
 * 100: 0x005BC5C0
 * 101: 0x005BC5C0
 * 102: 0x005BC5C0
 * 103: 0x005BC5C0
 */

#endif /* GT4_mNetConf_H */
