/* gt4/mNilConst.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mNilConst : hInst
 * type_info 0x0088ED50, type_info function 0x005F1598, structors 0x0031E228
 * vtable 0x00675948: 11 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_mNilConst_H
#define GT4_mNilConst_H

#include "types.h"

struct mNilConst {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031E258  mNilConst::~mNilConst() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031E0E8  mNilConst::rc_class() const [high]
 *   4: 0x0031E0F8  mNilConst::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031E188  mNilConst::execute(hThread*) [high]
 *   9: 0x0031E220  mNilConst::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mNilConst_H */
