/* gt4/mPhotoMapWindow.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mPhotoMapWindow : mBox
 * type_info 0x0088DC90, type_info function 0x005CD5E0, structors 0x00192BE0, 0x00192D30
 * vtable 0x0065D480: 103 slots
 * size: not known; the fields seen reach 0xC0
 * C++ (GT4_CXX): size 0x164 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8, 0xAC
 */
#ifndef GT4_mPhotoMapWindow_H
#define GT4_mPhotoMapWindow_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/mBox.h"

class mPhotoMapWindow : public mBox {
public:
    char padC0[0xA4];
    static s32 GetClassID();  /* 0x00192BA8 */
};
#else
struct mPhotoMapWindow {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    void *unk14;
    char pad18[0x14];
    void *unk2C;
    char pad30[0x60];
    void *unk90;
    char pad94[0xC];
    void *unkA0;
    void *unkA4;
    void *unkA8;
    union {
        s32 unkAC;
        void *unkAC_pvoid;
    };
    s32 unkB0;
    s32 unkB4;
    s32 unkB8;
    s32 unkBC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mPhotoMapWindow__rc_class(struct mPhotoMapWindow *);
s32 mPhotoMapWindow__rc_size(struct mPhotoMapWindow *);
s32 mPhotoMapWindow__GetClassID(void);
s32 mPhotoMapWindow__getClassID(struct mPhotoMapWindow *);
void mBox__deepCopy(struct mPhotoMapWindow *, const struct hObject *);
s32 mComposite__isComposite(struct mPhotoMapWindow *);
s32 mComposite__isClipBox(struct mPhotoMapWindow *);
s32 mComposite__doUpdateChildren(struct mPhotoMapWindow *, struct mRenderContext *);
s32 mComposite__doRenderChildren(struct mPhotoMapWindow *, struct mRenderContext *);
s32 mPhotoMapWindow__virtual_01(struct mPhotoMapWindow *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00192D30  mPhotoMapWindow::~mPhotoMapWindow() [high]
 *   1: 0x00207A38
 *   2: 0x00305AE8
 *   3: 0x00192B30  mPhotoMapWindow::rc_class() const [high]
 *   4: 0x00192B40  mPhotoMapWindow::rc_size() const [high]
 *   5: 0x00305518
 *   6: 0x00305528
 *   7: 0x00305540
 *   8: 0x00201700
 *   9: 0x00192BB8  mPhotoMapWindow::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x00304B18
 *  49: 0x0025AD20
 *  50: 0x0025C470
 *  51: 0x0025B2A0
 *  52: 0x00206848
 *  53: 0x00206840
 *  54: 0x00266A18
 *  55: 0x00266A38
 *  56: 0x00266A48
 *  57: 0x00266A78
 *  58: 0x00266A80
 *  59: 0x00266AB0
 *  60: 0x002086F0
 *  61: 0x00201168
 *  62: 0x002079C0
 *  63: 0x00263420
 *  64: 0x00263428
 *  65: 0x002634E0
 *  66: 0x002636C8
 *  67: 0x00192F28
 *  68: 0x00193948
 *  69: 0x00194470
 *  70: 0x00194AD0
 *  71: 0x00263D28
 *  72: 0x00264030
 *  73: 0x00264338
 *  74: 0x00264638
 *  75: 0x00264928
 *  76: 0x00264C48
 *  77: 0x00264920
 *  78: 0x00264F60
 *  79: 0x002652B8
 *  80: 0x00265610
 *  81: 0x00265960
 *  82: 0x00265C70
 *  83: 0x00265C78
 *  84: 0x00265C80
 *  85: 0x00206F18
 *  86: 0x00206F90
 *  87: 0x00207010
 *  88: 0x00207090
 *  89: 0x00207110
 *  90: 0x00207188
 *  91: 0x00195360
 *  92: 0x00195488
 *  93: 0x00268478
 *  94: 0x0025C2A8
 *  95: 0x00207280
 *  96: 0x00207470
 *  97: 0x002084D0
 *  98: 0x00208210
 *  99: 0x00207F10
 * 100: 0x00207F48
 * 101: 0x00208020
 * 102: 0x00208160
 */

#endif /* GT4_mPhotoMapWindow_H */
