/* gt4/mPrint.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mPrint : hInst
 * type_info 0x0088EBC0, type_info function 0x005F1688, structors 0x0031EB98
 * vtable 0x00675810: 11 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_mPrint_H
#define GT4_mPrint_H

#include "types.h"

struct mPrint {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    void *unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031EBD8  mPrint::~mPrint() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031E790  mPrint::rc_class() const [high]
 *   4: 0x0031E7A0  mPrint::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031E830  mPrint::execute(hThread*) [high]
 *   9: 0x0031EB70  mPrint::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mPrint_H */
