/* gt4/mRaceCourseMapFacePS2.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mRaceCourseMapFacePS2 : mRaceCourseMapFace
 * type_info 0x0088DAA0, type_info function 0x005C48E0, structors 0x00128738, 0x00128788
 * vtable 0x0065A448: 98 slots
 * size: not known; the fields seen reach 0xE8
 */
#ifndef GT4_mRaceCourseMapFacePS2_H
#define GT4_mRaceCourseMapFacePS2_H

#include "types.h"

struct mRaceCourseMapFacePS2 {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    void *unk14;
    char pad18[0x14];
    void *unk2C;
    char pad30[0x60];
    void *unk90;
    char pad94[0x34];
    union {
        s32 unkC8;
        void *unkC8_pvoid;
    };
    void *unkCC;
    void *unkD0;
    void *unkD4;
    union {
        f32 unkD8;
        void *unkD8_pvoid;
    };
    union {
        f32 unkDC;
        void *unkDC_pvoid;
    };
    void *unkE0;
    void *unkE4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00128788
 *   1: 0x00306F88
 *   2: 0x00305AE8
 *   3: 0x0012A0D8
 *   4: 0x0012A0E8
 *   5: 0x00305518
 *   6: 0x00305528
 *   7: 0x00305540
 *   8: 0x0012AC88
 *   9: 0x0012A160
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x00304B18
 *  49: 0x0025AD20
 *  50: 0x0025C470
 *  51: 0x0025B2A0
 *  52: 0x0025B2A8
 *  53: 0x0025B298
 *  54: 0x00266A18
 *  55: 0x00266A38
 *  56: 0x00266A48
 *  57: 0x00266A78
 *  58: 0x00266A80
 *  59: 0x00266AB0
 *  60: 0x00267058
 *  61: 0x0012A8D8
 *  62: 0x002633E8
 *  63: 0x00263420
 *  64: 0x00263428
 *  65: 0x002634E0
 *  66: 0x002636C8
 *  67: 0x0012A858
 *  68: 0x0012A878
 *  69: 0x0012A898
 *  70: 0x00128B68
 *  71: 0x00263D28
 *  72: 0x00264030
 *  73: 0x00264338
 *  74: 0x00264638
 *  75: 0x00264928
 *  76: 0x00264C48
 *  77: 0x00264920
 *  78: 0x00264F60
 *  79: 0x002652B8
 *  80: 0x00265610
 *  81: 0x00265960
 *  82: 0x00265C70
 *  83: 0x00265C78
 *  84: 0x00265C80
 *  85: 0x002638E8
 *  86: 0x00263918
 *  87: 0x00263948
 *  88: 0x00263978
 *  89: 0x002639A8
 *  90: 0x00263A08
 *  91: 0x00263A68
 *  92: 0x00263CB0
 *  93: 0x00268478
 *  94: 0x0025C2A8
 *  95: 0x00128800
 *  96: 0x00128938
 *  97: 0x00128B48
 */

#endif /* GT4_mRaceCourseMapFacePS2_H */
