/* gt4/MRectangleReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MRectangleReader : MReaderBase
 * type_info 0x0088E1E0, type_info function 0x005DADB0, structors 0x0022A840, 0x0022A858
 * vtable 0x00665098: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MRectangleReader_H
#define GT4_MRectangleReader_H

#include "types.h"

struct MRectangleReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0022A858
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x0022AA18
 */

#endif /* GT4_MRectangleReader_H */
