/* gt4/MRegion.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MRegion
 * type_info 0x006D5ED8, type_info function 0x005DBC40
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4_MRegion_H
#define GT4_MRegion_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class MRegion {
public:
};
#else
struct MRegion;
#endif

#endif /* GT4_MRegion_H */
