/* gt4/MRegionReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MRegionReader : MReaderBase
 * type_info 0x0088E890, type_info function 0x005E9DD0, structors 0x002CC648, 0x002CC660
 * vtable 0x0066FDD8: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MRegionReader_H
#define GT4_MRegionReader_H

#include "types.h"

struct MRegionReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002CC660
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x002CC6C8
 */

#endif /* GT4_MRegionReader_H */
