/* gt4/mRenderContext.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mRenderContext : hObject
 * type_info 0x0088E220, type_info function 0x005DB1D0, structors 0x0022ADF8, 0x0022B0A0
 * vtable 0x00665160: 77 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x1D5C (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x8
 */
#ifndef GT4_mRenderContext_H
#define GT4_mRenderContext_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hObject.h"
class mRootWindow;

class mRenderContext : public hObject {
public:
    char pad10[0x1D4C];
    virtual s32 virtual_49();  /* 49: parameters from the code */
    virtual s32 virtual_50(s32);  /* 50: parameters from the code */
    virtual s32 virtual_51(f32, f32, f32, f32);  /* 51: parameters from the code */
    virtual s32 virtual_52(f32, f32, f32, f32);  /* 52: parameters from the code */
    virtual s32 virtual_53(s32, s32, s32, s32);  /* 53: parameters from the code */
    virtual s32 virtual_54(s32, s32, s32, s32);  /* 54: parameters from the code */
    virtual s32 virtual_55(s32);  /* 55: parameters from the code */
    virtual s32 virtual_56();  /* 56: parameters from the code */
    virtual s32 virtual_57();  /* 57: parameters from the code */
    virtual void virtual_58();  /* 58: parameters from the code */
    virtual s32 virtual_59();  /* 59: parameters from the code */
    virtual s32 virtual_60();  /* 60: parameters from the code */
    virtual s32 virtual_61(s32);  /* 61: parameters from the code */
    virtual f32 virtual_62(s32, s32);  /* 62: parameters from the code */
    virtual s32 virtual_63(s32, s32);  /* 63: parameters from the code */
    virtual s32 virtual_64(s32, s32);  /* 64: parameters from the code */
    virtual s32 virtual_65(s32);  /* 65: parameters from the code */
    virtual s32 virtual_66(s32, f32);  /* 66: parameters from the code */
    virtual s32 virtual_67(s32, f32);  /* 67: parameters from the code */
    virtual s32 virtual_68();  /* 68: parameters from the code */
    virtual s32 virtual_69();  /* 69: parameters from the code */
    virtual s32 virtual_70();  /* 70: parameters from the code */
    virtual s32 virtual_71();  /* 71: parameters from the code */
    virtual s32 virtual_72();  /* 72: parameters from the code */
    virtual s32 magnifyScreen(f32, f32, f32, f32, u32);  /* 73: mRenderContext::magnifyScreen(float, float, float, float, unsigned int) */
    virtual s32 shotScreen(const char *);  /* 74: mRenderContextPS3::shotScreen(char const*) */
    virtual s32 virtual_75(s32, s32, s32, f32);  /* 75: parameters from the code */
    virtual s32 virtual_76(s32, s32, s32, f32);  /* 76: parameters from the code */
    static s32 GetClassID();  /* 0x0022AC60 */
    void closePage(mRootWindow *);  /* 0x0022FA08 */
    void closeOSKeyboard();  /* 0x002321D0 */
};
#else
struct mRenderContext {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mRenderContext__rc_class(struct mRenderContext *);
s32 mRenderContext__rc_size(struct mRenderContext *);
s32 mRenderContext__GetClassID(void);
s32 mRenderContext__getClassID(struct mRenderContext *);
void mRenderContext__closePage(struct mRenderContext *, struct mRootWindow *);
void mRenderContext__closeOSKeyboard(struct mRenderContext *);
void mRenderContext__magnifyScreen(struct mRenderContext *, f32, f32, f32, f32, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0022B0A0  mRenderContext::~mRenderContext() [high]
 *   1: 0x0030B7C8
 *   2: 0x0030AA70
 *   3: 0x0022ABE8  mRenderContext::rc_class() const [high]
 *   4: 0x0022ABF8  mRenderContext::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0030B888
 *   9: 0x0022AC70  mRenderContext::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x0030B278
 *  49: 0x005BC5C0
 *  50: 0x005BC5C0
 *  51: 0x005BC5C0
 *  52: 0x005BC5C0
 *  53: 0x005BC5C0
 *  54: 0x005BC5C0
 *  55: 0x005BC5C0
 *  56: 0x005BC5C0
 *  57: 0x005BC5C0
 *  58: 0x005BC5C0
 *  59: 0x005BC5C0
 *  60: 0x005BC5C0
 *  61: 0x005BC5C0
 *  62: 0x005BC5C0
 *  63: 0x005BC5C0
 *  64: 0x005BC5C0
 *  65: 0x005BC5C0
 *  66: 0x005BC5C0
 *  67: 0x005BC5C0
 *  68: 0x005BC5C0
 *  69: 0x005BC5C0
 *  70: 0x005BC5C0
 *  71: 0x005BC5C0
 *  72: 0x005BC5C0
 *  73: 0x00232458  mRenderContext::magnifyScreen(float, float, float, float, unsigned int) [high]
 *  74: 0x005BC5C0  mRenderContextPS3::shotScreen(char const*) [high]
 *  75: 0x00232460
 *  76: 0x00232468
 */

#endif /* GT4_mRenderContext_H */
