/* gt4/mScrollable.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mScrollable : mComposite
 * type_info 0x0088E910, type_info function 0x005EA250, structors 0x002D4830, 0x002D4870
 * vtable 0x006711C8: 107 slots
 * size: not known; the fields seen reach 0xBC
 */
#ifndef GT4_mScrollable_H
#define GT4_mScrollable_H

#include "types.h"

struct mScrollable {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    void *unk14;
    char pad18[0x14];
    void *unk2C;
    char pad30[0x60];
    void *unk90;
    char pad94[0xC];
    void *unkA0;
    void *unkA4;
    void *unkA8;
    void *unkAC;
    s32 unkB0;
    s32 unkB4;
    s32 unkB8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002D4870  mScrollable::~mScrollable() [high]
 *   1: 0x00207A38
 *   2: 0x00305AE8
 *   3: 0x002D45F8  mScrollable::rc_class() const [high]
 *   4: 0x002D4608  mScrollable::rc_size() const [high]
 *   5: 0x00305518
 *   6: 0x00305528
 *   7: 0x00305540
 *   8: 0x002D4C88  mScrollable::deepCopy(hObject const*) [high]
 *   9: 0x002D4680  mScrollable::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x00304B18
 *  49: 0x0025AD20
 *  50: 0x0025C470
 *  51: 0x0025B2A0
 *  52: 0x00206848
 *  53: 0x00206840
 *  54: 0x00266A18
 *  55: 0x00266A38
 *  56: 0x00266A48
 *  57: 0x00266A78
 *  58: 0x00266A80
 *  59: 0x00266AB0
 *  60: 0x002086F0
 *  61: 0x002D4990
 *  62: 0x002079C0
 *  63: 0x00263420
 *  64: 0x00263428
 *  65: 0x002634E0
 *  66: 0x002636C8
 *  67: 0x002638B0
 *  68: 0x002638D0
 *  69: 0x002638D8
 *  70: 0x002638E0
 *  71: 0x00263D28
 *  72: 0x00264030
 *  73: 0x00264338
 *  74: 0x00264638
 *  75: 0x00264928
 *  76: 0x00264C48
 *  77: 0x00264920
 *  78: 0x00264F60
 *  79: 0x002652B8
 *  80: 0x00265610
 *  81: 0x00265960
 *  82: 0x00265C70
 *  83: 0x00265C78
 *  84: 0x00265C80
 *  85: 0x00206F18
 *  86: 0x00206F90
 *  87: 0x00207010
 *  88: 0x00207090
 *  89: 0x00207110
 *  90: 0x00207188
 *  91: 0x002072E8
 *  92: 0x002074E8
 *  93: 0x00268478
 *  94: 0x0025C2A8
 *  95: 0x00207280
 *  96: 0x00207470
 *  97: 0x002084D0
 *  98: 0x00208210
 *  99: 0x00207F10
 * 100: 0x00207F48
 * 101: 0x00208020
 * 102: 0x00208160
 * 103: 0x002D4940  mScrollable::getBeginPointRatio() [high]
 * 104: 0x002D4950  mScrollable::getVolumeRatio() [high]
 * 105: 0x002D4960  mScrollable::canIncrement() const [high]
 * 106: 0x002D4968  mScrollable::canDecrement() const [high]
 */

#endif /* GT4_mScrollable_H */
