/* gt4/mSelectBox.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mSelectBox : mScrollable
 * type_info 0x0088E930, type_info function 0x005EA378, structors 0x002D8C90, 0x002D8D38
 * vtable 0x00671898: 107 slots
 * size: not known; the fields seen reach 0xF4
 */
#ifndef GT4_mSelectBox_H
#define GT4_mSelectBox_H

#include "types.h"

struct mSelectBox {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    void *unk14;
    char pad18[0x14];
    void *unk2C;
    char pad30[0x60];
    void *unk90;
    char pad94[0xC];
    void *unkA0;
    void *unkA4;
    void *unkA8;
    void *unkAC;
    s32 unkB0;
    s32 unkB4;
    s32 unkB8;
    char padBC[0x34];
    void *unkF0;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x002D8D38  mSelectBox::~mSelectBox() [high]
 *   1: 0x00207A38
 *   2: 0x00305AE8
 *   3: 0x002D8BE0  mSelectBox::rc_class() const [high]
 *   4: 0x002D8BF0  mSelectBox::rc_size() const [high]
 *   5: 0x00305518
 *   6: 0x00305528
 *   7: 0x00305540
 *   8: 0x002DB7D8  mSelectBox::deepCopy(hObject const*) [high]
 *   9: 0x002D8C68  mSelectBox::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x00304B18
 *  49: 0x0025AD20
 *  50: 0x0025C470
 *  51: 0x0025B2A0
 *  52: 0x00206848
 *  53: 0x00206840
 *  54: 0x00266A18
 *  55: 0x00266A38
 *  56: 0x00266A48
 *  57: 0x00266A78
 *  58: 0x00266A80
 *  59: 0x00266AB0
 *  60: 0x002086F0
 *  61: 0x002DB4E8
 *  62: 0x002079C0
 *  63: 0x002DA400
 *  64: 0x002DA520
 *  65: 0x002634E0
 *  66: 0x002636C8
 *  67: 0x002DA5A0
 *  68: 0x002638D0
 *  69: 0x002DA6F0
 *  70: 0x002DAA10
 *  71: 0x002DAD18  mSelectBox::onKeyPress(mRenderContext*, mKeyPressEvent*) [high]
 *  72: 0x00264030
 *  73: 0x00264338
 *  74: 0x00264638
 *  75: 0x00264928
 *  76: 0x00264C48
 *  77: 0x00264920
 *  78: 0x00264F60
 *  79: 0x002652B8
 *  80: 0x00265610
 *  81: 0x00265960
 *  82: 0x00265C70
 *  83: 0x00265C78
 *  84: 0x00265C80
 *  85: 0x00206F18
 *  86: 0x00206F90
 *  87: 0x00207010
 *  88: 0x00207090
 *  89: 0x00207110
 *  90: 0x00207188
 *  91: 0x002072E8
 *  92: 0x002DA870  mSelectBox::doRender(mRenderContext*) [medium]
 *  93: 0x00268478
 *  94: 0x0025C2A8
 *  95: 0x00207280
 *  96: 0x00207470
 *  97: 0x002084D0
 *  98: 0x002DB870
 *  99: 0x002DB8B8
 * 100: 0x002DB930
 * 101: 0x00208020
 * 102: 0x002DB9B8
 * 103: 0x002DB9E8  mSelectBox::getBeginPointRatio() [high]
 * 104: 0x002DBAD0  mSelectBox::getVolumeRatio() [high]
 * 105: 0x002DBB80  mSelectBox::canIncrement() const [high]
 * 106: 0x002DBC58  mSelectBox::canDecrement() const [high]
 */

#endif /* GT4_mSelectBox_H */
