/* gt4/mSetState.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mSetState : hInst
 * type_info 0x0088EE40, type_info function 0x005F1728, structors 0x0031F2A8
 * vtable 0x00675740: 11 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_mSetState_H
#define GT4_mSetState_H

#include "types.h"

struct mSetState {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    union {
        s32 unk8;
        void *unk8_pvoid;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031F2E8  mSetState::~mSetState() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x0031F1B8  mSetState::rc_class() const [high]
 *   4: 0x0031F1C8  mSetState::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031F258  mSetState::execute(hThread*) [high]
 *   9: 0x0031F278  mSetState::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mSetState_H */
