/* gt4/mStaticDefine.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mStaticDefine : mDefine
 * type_info 0x0088ED00, type_info function 0x005F1778, structors 0x0031F540, 0x0031F578
 * vtable 0x006756D8: 11 slots
 * size: not known; the fields seen reach 0xC
 * C++ (GT4_CXX): size 0x10 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mStaticDefine_H
#define GT4_mStaticDefine_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/mDefine.h"

class mStaticDefine : public mDefine {
public:
    char padC[0x4];
};
#else
struct mStaticDefine {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
void mDefine__read(struct mStaticDefine *, void *, u32);
s32 mStaticDefine__rc_class(struct mStaticDefine *);
s32 mStaticDefine__rc_size(struct mStaticDefine *);
s32 mStaticDefine__execute(struct mStaticDefine *, struct hThread *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0031F578  mStaticDefine::~mStaticDefine() [high]
 *   1: 0x00328500
 *   2: 0x00319420
 *   3: 0x0031F3C8  mStaticDefine::rc_class() const [high]
 *   4: 0x0031F3D8  mStaticDefine::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x0031F468  mStaticDefine::execute(hThread*) [high]
 *   9: 0x00319360
 *  10: 0x005EE8A8
 */

#endif /* GT4_mStaticDefine_H */
