/* gt4/MstringReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MstringReader : MReaderBase
 * type_info 0x0088E320, type_info function 0x005DD100, structors 0x00159D60, 0x0021B848, 0x00220A38, 0x00233E38, 0x002463A0, 0x00247768, 0x00261E70, 0x00292F18, 0x002984C0, 0x002A29F0, 0x002A51D8, 0x002BD568, 0x005DD098, 0x005DD150
 * vtable 0x00666CF0: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MstringReader_H
#define GT4_MstringReader_H

#include "types.h"

struct MstringReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DD098
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x0024E110
 */

#endif /* GT4_MstringReader_H */
