/* gt4/mUnaryOperator.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mUnaryOperator : hInst
 * type_info 0x0088ED30, type_info function 0x005F19B8, structors 0x003209E8
 * vtable 0x00675468: 11 slots
 * size: not known; the fields seen reach 0x8
 * C++ (GT4_CXX): size 0x14 (rc_size), vptr at 0x4
 */
#ifndef GT4_mUnaryOperator_H
#define GT4_mUnaryOperator_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mUnaryOperator : public hInst {
public:
    char pad8[0xC];
};
#else
struct mUnaryOperator {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mUnaryOperator__rc_class(struct mUnaryOperator *);
s32 mUnaryOperator__rc_size(struct mUnaryOperator *);
s32 mUnaryOperator__execute(struct mUnaryOperator *, struct hThread *);
s32 mUnaryOperator__read(struct mUnaryOperator *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00320A48  mUnaryOperator::~mUnaryOperator() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x00320728  mUnaryOperator::rc_class() const [high]
 *   4: 0x00320738  mUnaryOperator::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x003207C8  mUnaryOperator::execute(hThread*) [high]
 *   9: 0x003208E8  mUnaryOperator::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mUnaryOperator_H */
