/* gt4/mUndef.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mUndef : hInst
 * type_info 0x0088ED20, type_info function 0x005F1A08, structors 0x00320C60, 0x00320CA8
 * vtable 0x00675400: 11 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_mUndef_H
#define GT4_mUndef_H

#include "types.h"

struct mUndef {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00320CA8  mUndef::~mUndef() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x00320BC0  mUndef::rc_class() const [high]
 *   4: 0x00320BD0  mUndef::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x00320BD8  mUndef::execute(hThread*) [high]
 *   9: 0x00320C40  mUndef::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mUndef_H */
