/* gt4/mVariablePush.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mVariablePush : hInst
 * type_info 0x0088EC50, type_info function 0x005F09C0, structors 0x00321250, 0x003212A0
 * vtable 0x00676308: 11 slots
 * size: not known; the fields seen reach 0x1C
 * C++ (GT4_CXX): size 0x1C (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_mVariablePush_H
#define GT4_mVariablePush_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hInst.h"

class mVariablePush : public hInst {
public:
    char pad8[0x10];
    s32 unk18;
};
#else
struct mVariablePush {
    s32 unk0;
    union {
        s32 unk4;
        void *unk4_pvoid;
    };
    char pad8[0x10];
    s32 unk18;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mVariablePush__rc_class(struct mVariablePush *);
s32 mVariablePush__rc_size(struct mVariablePush *);
s32 mVariablePush__virtual_08(struct mVariablePush *, struct hThread *);
s32 mVariablePush__read(struct mVariablePush *, void *, u32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003212A0  mVariablePush::~mVariablePush() [high]
 *   1: 0x00328500
 *   2: 0x00328508
 *   3: 0x00320E28  mVariablePush::rc_class() const [high]
 *   4: 0x00320E38  mVariablePush::rc_size() const [high]
 *   5: 0x00328648
 *   6: 0x00328650
 *   7: 0x00328658
 *   8: 0x00320E40
 *   9: 0x00321210  mVariablePush::read(HIO&, unsigned int) [high]
 *  10: 0x005EE8A8
 */

#endif /* GT4_mVariablePush_H */
