/* gt4/MWidgetReader.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class MWidgetReader : MReaderBase
 * type_info 0x0088E3C0, type_info function 0x005DEC90, structors 0x00207590, 0x00218C00, 0x00218E10, 0x00269940, 0x005DEC28
 * vtable 0x00667528: 4 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_MWidgetReader_H
#define GT4_MWidgetReader_H

#include "types.h"

struct MWidgetReader {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DEC28
 *   1: 0x0024DB50
 *   2: 0x0024DB58
 *   3: 0x00269350
 */

#endif /* GT4_MWidgetReader_H */
