/* gt4/mWidget.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class mWidget : hModule
 * type_info 0x0088E3B0, type_info function 0x005DEA30, structors 0x00255298, 0x00255548
 * vtable 0x00667220: 95 slots
 * size: not known; the fields seen reach 0x94
 * C++ (GT4_CXX): size 0xA0 (rc_size), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4, 0x8
 */
#ifndef GT4_mWidget_H
#define GT4_mWidget_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/hModule.h"
class MColor;
class mButtonEvent;
class mCrossingEvent;
class mEvent;
class mKeyPressEvent;
class mKeyReleaseEvent;
class mMotionEvent;
class mRenderContext;

class mWidget : public hModule {
public:
    void *unk2C;
    char pad30[0x60];
    void *unk90;
    char pad94[0xC];
    virtual s32 virtual_51();  /* 51: GT HD (medium): mWidget::isRootWindow() const; parameters from the code */
    virtual s32 isClipBox() const;  /* 52: mWidget::isClipBox() const */
    virtual s32 isComposite() const;  /* 53: mWidget::isComposite() const */
    virtual s32 getProperSize(f32 *, f32 *) const;  /* 54: mWidget::getProperSize(float*, float*) const */
    virtual s32 getAlpha() const;  /* 55: mWidget::getAlpha() const */
    virtual s32 getAlpha(s32) const;  /* 56: mWidget::getAlpha(int) const */
    virtual s32 setAlpha(f32);  /* 57: mWidget::setAlpha(float) */
    virtual s32 setAlpha(f32, s32);  /* 58: mWidget::setAlpha(float, int) */
    virtual void setColor(const MColor &);  /* 59: mWidget::setColor(MColor const&) */
    virtual s32 virtual_60();  /* 60: parameters from the code */
    virtual s32 virtual_61(s32);  /* 61: parameters from the code */
    virtual s32 virtual_62(s32);  /* 62: parameters from the code */
    virtual void virtual_63(s32);  /* 63: parameters from the code */
    virtual s32 virtual_64(s32);  /* 64: parameters from the code */
    virtual s32 virtual_65(s32);  /* 65: parameters from the code */
    virtual s32 virtual_66(s32);  /* 66: parameters from the code */
    virtual s32 virtual_67(s32);  /* 67: parameters from the code */
    virtual s32 virtual_68(s32);  /* 68: parameters from the code */
    virtual s32 virtual_69(s32, s32);  /* 69: parameters from the code */
    virtual void virtual_70(s32, s32);  /* 70: parameters from the code */
    virtual s32 onKeyPress(mRenderContext *, mKeyPressEvent *);  /* 71: mWidget::onKeyPress(mRenderContext*, mKeyPressEvent*) */
    virtual void onKeyRelease(mRenderContext *, mKeyReleaseEvent *);  /* 72: mWidget::onKeyRelease(mRenderContext*, mKeyReleaseEvent*) */
    virtual s32 onButtonPress(mRenderContext *, mButtonEvent *);  /* 73: mWidget::onButtonPress(mRenderContext*, mButtonEvent*) */
    virtual s32 onButtonRelease(mRenderContext *, mButtonEvent *);  /* 74: mWidget::onButtonRelease(mRenderContext*, mButtonEvent*) */
    virtual s32 onEnter(mRenderContext *, mCrossingEvent *);  /* 75: mWidget::onEnter(mRenderContext*, mCrossingEvent*) */
    virtual s32 onLeave(mRenderContext *, mCrossingEvent *);  /* 76: mWidget::onLeave(mRenderContext*, mCrossingEvent*) */
    virtual s32 onMotion(mRenderContext *, mMotionEvent *);  /* 77: mWidget::onMotion(mRenderContext*, mMotionEvent*) */
    virtual s32 onActivate(mRenderContext *, mEvent *);  /* 78: mWidget::onActivate(mRenderContext*, mEvent*) */
    virtual s32 onCancel(mRenderContext *, mEvent *);  /* 79: mWidget::onCancel(mRenderContext*, mEvent*) */
    virtual s32 onFocusEnter(mRenderContext *, mEvent *);  /* 80: mWidget::onFocusEnter(mRenderContext*, mEvent*) */
    virtual s32 onFocusLeave(mRenderContext *, mEvent *);  /* 81: mWidget::onFocusLeave(mRenderContext*, mEvent*) */
    virtual s32 onDropPossible(mRenderContext *, f32, f32, const void *);  /* 82: mWidget::onDropPossible(mRenderContext*, float, float, std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&) */
    virtual void onDropReceived(mRenderContext *, f32, f32, const void *, void *);  /* 83: mWidget::onDropReceived(mRenderContext*, float, float, std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&, void*) */
    virtual s32 onEvent(mRenderContext *, mEvent *, bool);  /* 84: mWidget::onEvent(mRenderContext*, mEvent*, bool) */
    virtual s32 virtual_85(s32);  /* 85: parameters from the code */
    virtual s32 virtual_86(s32);  /* 86: parameters from the code */
    virtual s32 virtual_87(s32);  /* 87: parameters from the code */
    virtual s32 virtual_88(s32);  /* 88: parameters from the code */
    virtual s32 virtual_89(s32);  /* 89: parameters from the code */
    virtual s32 virtual_90(s32);  /* 90: parameters from the code */
    virtual s32 virtual_91(s32);  /* 91: GT HD (medium): mWidget::doUpdate(mRenderContext*); parameters from the code */
    virtual s32 virtual_92(s32);  /* 92: GT HD (medium): mWidget::doRender(mRenderContext*); parameters from the code */
    virtual s32 virtual_93();  /* 93: parameters from the code */
    virtual s32 virtual_94(s32);  /* 94: parameters from the code */
    static s32 GetClassID();  /* 0x00255260 */
    f32 getWindowX() const;  /* 0x0025B2B0 */
    void setWindowX(f32);  /* 0x0025B2E0 */
    f32 getWindowY() const;  /* 0x0025B310 */
    void setWindowY(f32);  /* 0x0025B340 */
    f32 getWindowW() const;  /* 0x0025B370 */
    void setWindowW(f32);  /* 0x0025B3A0 */
    f32 getWindowH() const;  /* 0x0025B3D0 */
    void setWindowH(f32);  /* 0x0025B400 */
    void setWindowPosition(f32, f32);  /* 0x0025B460 */
    void getWindowSize(f32 *, f32 *) const;  /* 0x0025B498 */
    s32 getRootWindow();  /* 0x0025C1E8 */
    s32 canDefault() const;  /* 0x00265FA8 */
    void setActive(bool);  /* 0x00265FF0 */
    void setScale(const void *);  /* 0x00267CE8 */
    void setRotate(f32);  /* 0x00267D18 */
    void setOpacity(f32);  /* 0x00267DB8 */
};
#else
struct mWidget {
    s32 unk0;
    union {
        void *unk4;
        s32 unk4_s32;
    };
    s32 unk8;
    s32 unkC;
    char pad10[0x4];
    void *unk14;
    char pad18[0x14];
    void *unk2C;
    char pad30[0x60];
    void *unk90;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 mWidget__rc_class(struct mWidget *);
s32 mWidget__rc_size(struct mWidget *);
s32 mWidget__GetClassID(void);
s32 mWidget__getClassID(struct mWidget *);
f32 mWidget__getWindowX(struct mWidget *);
void mWidget__setWindowX(struct mWidget *, f32);
f32 mWidget__getWindowY(struct mWidget *);
void mWidget__setWindowY(struct mWidget *, f32);
f32 mWidget__getWindowW(struct mWidget *);
void mWidget__setWindowW(struct mWidget *, f32);
f32 mWidget__getWindowH(struct mWidget *);
void mWidget__setWindowH(struct mWidget *, f32);
void mWidget__setWindowPosition(struct mWidget *, f32, f32);
void mWidget__getWindowSize(struct mWidget *, f32 *, f32 *);
s32 mWidget__getRootWindow(struct mWidget *);
s32 mWidget__canDefault(struct mWidget *);
void mWidget__setActive(struct mWidget *, s32);
void mWidget__setScale(struct mWidget *, const void *);
void mWidget__setRotate(struct mWidget *, f32);
void mWidget__setOpacity(struct mWidget *, f32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00255548  mWidget::~mWidget() [high]
 *   1: 0x00306F88
 *   2: 0x00305AE8
 *   3: 0x002551E8  mWidget::rc_class() const [high]
 *   4: 0x002551F8  mWidget::rc_size() const [high]
 *   5: 0x00305518
 *   6: 0x00305528
 *   7: 0x00305540
 *   8: 0x00262C78  mWidget::deepCopy(hObject const*) [high]
 *   9: 0x00255270  mWidget::getClassID() const [high]
 *  10: 0x0030B3F8
 *  11: 0x0030B400
 *  12: 0x0030ACC8
 *  13: 0x0030AD30
 *  14: 0x0030AD98
 *  15: 0x0030B2A0
 *  16: 0x0030B2D0
 *  17: 0x0030B348
 *  18: 0x0030B350
 *  19: 0x0030ABF8
 *  20: 0x0030ACC0
 *  21: 0x0030AE40
 *  22: 0x0030AE68
 *  23: 0x0030AE90
 *  24: 0x0030AEB8
 *  25: 0x0030AEE0
 *  26: 0x0030AF08
 *  27: 0x0030AF30
 *  28: 0x0030AF58
 *  29: 0x0030AF80
 *  30: 0x0030AFA8
 *  31: 0x0030AFD0
 *  32: 0x0030AFF8
 *  33: 0x0030B020
 *  34: 0x0030B048
 *  35: 0x0030B070
 *  36: 0x0030B098
 *  37: 0x0030B0C0
 *  38: 0x0030B0E8
 *  39: 0x0030B110
 *  40: 0x0030B138
 *  41: 0x0030B160
 *  42: 0x0030B188
 *  43: 0x0030B1B0
 *  44: 0x0030B1D8
 *  45: 0x0030B200
 *  46: 0x0030B228
 *  47: 0x0030B250
 *  48: 0x00304B18
 *  49: 0x0025AD20
 *  50: 0x0025C470
 *  51: 0x0025B2A0  mWidget::isRootWindow() const [medium]
 *  52: 0x0025B2A8  mWidget::isClipBox() const [high]
 *  53: 0x0025B298  mWidget::isComposite() const [high]
 *  54: 0x00266A18  mWidget::getProperSize(float*, float*) const [high]
 *  55: 0x00266A38  mWidget::getAlpha() const [high]
 *  56: 0x00266A48  mWidget::getAlpha(int) const [high]
 *  57: 0x00266A78  mWidget::setAlpha(float) [high]
 *  58: 0x00266A80  mWidget::setAlpha(float, int) [high]
 *  59: 0x00266AB0  mWidget::setColor(MColor const&) [high]
 *  60: 0x00267058
 *  61: 0x00261BC8
 *  62: 0x002633E8
 *  63: 0x00263420
 *  64: 0x00263428
 *  65: 0x002634E0
 *  66: 0x002636C8
 *  67: 0x002638B0
 *  68: 0x002638D0
 *  69: 0x002638D8
 *  70: 0x002638E0
 *  71: 0x00263D28  mWidget::onKeyPress(mRenderContext*, mKeyPressEvent*) [high]
 *  72: 0x00264030  mWidget::onKeyRelease(mRenderContext*, mKeyReleaseEvent*) [high]
 *  73: 0x00264338  mWidget::onButtonPress(mRenderContext*, mButtonEvent*) [high]
 *  74: 0x00264638  mWidget::onButtonRelease(mRenderContext*, mButtonEvent*) [high]
 *  75: 0x00264928  mWidget::onEnter(mRenderContext*, mCrossingEvent*) [high]
 *  76: 0x00264C48  mWidget::onLeave(mRenderContext*, mCrossingEvent*) [high]
 *  77: 0x00264920  mWidget::onMotion(mRenderContext*, mMotionEvent*) [high]
 *  78: 0x00264F60  mWidget::onActivate(mRenderContext*, mEvent*) [high]
 *  79: 0x002652B8  mWidget::onCancel(mRenderContext*, mEvent*) [high]
 *  80: 0x00265610  mWidget::onFocusEnter(mRenderContext*, mEvent*) [high]
 *  81: 0x00265960  mWidget::onFocusLeave(mRenderContext*, mEvent*) [high]
 *  82: 0x00265C70  mWidget::onDropPossible(mRenderContext*, float, float, std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&) [high]
 *  83: 0x00265C78  mWidget::onDropReceived(mRenderContext*, float, float, std::basic_string<char, std::char_traits<char>, std_allocator<char> > const&, void*) [high]
 *  84: 0x00265C80  mWidget::onEvent(mRenderContext*, mEvent*, bool) [high]
 *  85: 0x002638E8
 *  86: 0x00263918
 *  87: 0x00263948
 *  88: 0x00263978
 *  89: 0x002639A8
 *  90: 0x00263A08
 *  91: 0x00263A68  mWidget::doUpdate(mRenderContext*) [medium]
 *  92: 0x00263CB0  mWidget::doRender(mRenderContext*) [medium]
 *  93: 0x00268478
 *  94: 0x0025C2A8
 */

#endif /* GT4_mWidget_H */
