/* gt4/ostream.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ostream
 * type_info 0x008A1BF0, type_info function 0x00614108
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4_ostream_H
#define GT4_ostream_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class ostream {
public:
};
#else
struct ostream;
#endif

#endif /* GT4_ostream_H */
