/* gt4/PitmanCallback.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class PitmanCallback
 * type_info 0x0088F800, type_info function 0x005FDB40, structors 0x003D33E8, 0x005FDAD8, 0x005FDB90
 * vtable 0x006829D0: 5 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_PitmanCallback_H
#define GT4_PitmanCallback_H

#include "types.h"

struct PitmanCallback {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FDAD8  PitmanCallback::~PitmanCallback() [high]
 *   1: 0x004574D8  ModelSet2::Callback::callback(int) [high]
 *   2: 0x003C9EF8  PitmanCallback::LOD(float) [high]
 *   3: 0x004574F8  ModelSet2::Callback::usr(int, ModelSet2::RegisterVal*) [high]
 *   4: 0x00457500  ModelSet2::Callback::usrf(int, ModelSet2::RegisterVal*) [high]
 */

#endif /* GT4_PitmanCallback_H */
