/* gt4/PitmenData.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class PitmenData : ScenePack
 * type_info 0x0088F820, type_info function 0x005FDC60, structors 0x003D5848, 0x003D58C0
 * vtable 0x00682A08: 1 slots
 * size: not known; the fields seen reach 0x70
 * C++ (GT4_CXX): size 0x70 (not known: up to the last field seen), vptr at 0x6C (introduced here), fields left out (overlap, or in the base's part): 0x6C
 * base ScenePack has no known member: left out of the C++ form
 */
#ifndef GT4_PitmenData_H
#define GT4_PitmenData_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class PitmenData {
public:
    char pad0[0x8];
    s32 unk8;
    char padC[0x60];
    virtual ~PitmenData();  /* 0: PitmenData::~PitmenData() */
};
#else
struct PitmenData {
    char pad0[0x8];
    s32 unk8;
    char padC[0x60];
    s32 unk6C;
};
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003D58C0  PitmenData::~PitmenData() [high]
 */

#endif /* GT4_PitmenData_H */
