/* gt4/PropNameSearcher.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class PropNameSearcher
 * type_info 0x0088F810, type_info function 0x005FDBB0, structors 0x003CCA38, 0x005FDC00
 * vtable 0x006829B8: 1 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_PropNameSearcher_H
#define GT4_PropNameSearcher_H

#include "types.h"

struct PropNameSearcher {
    s32 unk0;
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003CC9E8  PropNameSearcher::setName(char const*) [high]
 */

#endif /* GT4_PropNameSearcher_H */
