/* gt4/RaceFreeRunInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceFreeRunInformation : RaceSolitaireInformation
 * type_info 0x0088F6E0, type_info function 0x005FB160, structors 0x003B98F8, 0x003B9928
 * vtable 0x00680640: 19 slots
 * size: not known; the fields seen reach 0x131
 * C++ (GT4_CXX): size 0x134 (not known: up to the last field seen), vptr at 0x12C, fields left out (overlap, or in the base's part): 0x12C
 */
#ifndef GT4_RaceFreeRunInformation_H
#define GT4_RaceFreeRunInformation_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceSolitaireInformation.h"

class RaceFreeRunInformation : public RaceSolitaireInformation {
public:
};
#else
struct RaceFreeRunInformation {
    char pad0[0x12C];
    union {
        char *unk12C;
        void *unk12C_pvoid;
        s32 unk12C_s32;
    };
    char unk130[1];
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceFreeRunInformation__getEntryCars(struct RaceFreeRunInformation *);
s32 RaceSolitaireInformation__createEntry(struct RaceFreeRunInformation *);
s32 RaceSolitaireInformation__updateEntryCar(struct RaceFreeRunInformation *, struct RaceEntryCar *);
void RaceSolitaireInformation__finishEntryCar(struct RaceFreeRunInformation *, void *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003B9928  RaceFreeRunInformation::~RaceFreeRunInformation() [high]
 *   1: 0x003BB4C8
 *   2: 0x003BB4D0
 *   3: 0x003BB4E8
 *   4: 0x003E9AB8
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003B9990  RaceFreeRunInformation::getEntryCars() [high]
 *  11: 0x003BB7E0
 *  12: 0x003E9AF8
 *  13: 0x003E9B70
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceFreeRunInformation_H */
