/* gt4/RaceBGMBase.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceBGMBase
 * type_info 0x006D5FA0, type_info function 0x005F6C50, structors 0x0038BFE0, 0x0038BFF0
 * vtable 0x0067D768: 9 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_RaceBGMBase_H
#define GT4_RaceBGMBase_H

#include "types.h"

struct RaceBGMBase {
    char pad0[0x4];
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0038BFF0  RaceBGMBase::~RaceBGMBase() [high]
 *   1: 0x0038C028  RaceBGMBase::update() [high]
 *   2: 0x0038C030  RaceBGMBase::nextTiming(int) [high]
 *   3: 0x0038C040  RaceBGMBase::checkTiming(int) [high]
 *   4: 0x0038C048  RaceBGMBase::play(int, bool) [high]
 *   5: 0x0038C050  RaceBGMBase::pause() [high]
 *   6: 0x0038C058  RaceBGMBase::resume() [high]
 *   7: 0x0038C060  RaceBGMBase::stop() [high]
 *   8: 0x0038C068  RaceBGMBase::getMusicInformation() [high]
 */

#endif /* GT4_RaceBGMBase_H */
