/* gt4/RaceTrainingInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceTrainingInformation : RaceSinglePlayerInformation
 * type_info 0x0088F950, type_info function 0x005FE908, structors 0x003ECAD0, 0x003ECB00
 * vtable 0x006845D0: 19 slots
 * size: not known; the fields seen reach 0x131
 * C++ (GT4_CXX): size 0x134 (not known: up to the last field seen), vptr at 0x12C, fields left out (overlap, or in the base's part): 0x12C
 */
#ifndef GT4_RaceTrainingInformation_H
#define GT4_RaceTrainingInformation_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceSinglePlayerInformation.h"

class RaceTrainingInformation : public RaceSinglePlayerInformation {
public:
};
#else
struct RaceTrainingInformation {
    char pad0[0x118];
    s32 unk118;
    char pad11C[0x10];
    union {
        char *unk12C;
        void *unk12C_pvoid;
        s32 unk12C_s32;
    };
    char unk130[1];
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceTrainingInformation__updateEntryCar(struct RaceTrainingInformation *, struct RaceEntryCar *);
s32 RaceTrainingInformation__finishEntryCar(struct RaceTrainingInformation *, void *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003ECB00  RaceTrainingInformation::~RaceTrainingInformation() [high]
 *   1: 0x003BB4C8
 *   2: 0x003D5B70
 *   3: 0x003D5B88
 *   4: 0x003D5BA8
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003BB568
 *  11: 0x003BB7E0
 *  12: 0x003ECB68  RaceTrainingInformation::updateEntryCar(RaceEntryCar&) [high]
 *  13: 0x003ECC70  RaceTrainingInformation::finishEntryCar(RaceOrganization&) [high]
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceTrainingInformation_H */
