/* gt4/RaceSpeedDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceSpeedDisplay : RaceValueDisplayBase
 * type_info 0x0088F630, type_info function 0x005F88A0, structors 0x003A6368
 * vtable 0x0067F688: 9 slots
 * size: not known; the fields seen reach 0x70
 * C++ (GT4_CXX): size 0x70 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceSpeedDisplay_H
#define GT4_RaceSpeedDisplay_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceValueDisplayBase.h"

class RaceSpeedDisplay : public RaceValueDisplayBase {
public:
    char pad18[0x50];
    f32 unk68;
    s32 unk6C;
};
#else
struct RaceSpeedDisplay {
    char pad0[0x14];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    char pad18[0x50];
    f32 unk68;
    s32 unk6C;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceSpeedDisplay__render_main(struct RaceSpeedDisplay *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F8838  RaceSpeedDisplay::~RaceSpeedDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003A4338
 *   4: 0x003A63A8  RaceSpeedDisplay::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 */

#endif /* GT4_RaceSpeedDisplay_H */
