/* gt4/RaceMTRGravityMeter.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMTRGravityMeter : RaceDisplayObjectBase
 * type_info 0x0088F510, type_info function 0x005F99D8, structors 0x003AC818, 0x003AC860
 * vtable 0x0067EEE0: 10 slots
 * size: not known; the fields seen reach 0x28
 */
#ifndef GT4_RaceMTRGravityMeter_H
#define GT4_RaceMTRGravityMeter_H

#include "types.h"

struct RaceMTRGravityMeter {
    char pad0[0x14];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    s32 unk18;
    s32 unk1C;
    s32 unk20;
    s32 unk24;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003AC860  RaceMTRGravityMeter::~RaceMTRGravityMeter() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003AC8E0  RaceMTRGravityMeter::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003AC8D8  RaceMTRGravityMeter::update(float) [high]
 */

#endif /* GT4_RaceMTRGravityMeter_H */
