/* gt4/RaceInput.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceInput
 * type_info 0x0088FB10, type_info function 0x005FFE18, structors 0x00426800, 0x00426880, 0x00426900
 * vtable 0x00686618: 8 slots
 * size: not known; the fields seen reach 0x1E0
 */
#ifndef GT4_RaceInput_H
#define GT4_RaceInput_H

#include "types.h"

struct RaceInput {
    char pad0[0xD0];
    union {
        void *unkD0;
        s32 unkD0_s32;
    };
    char padD4[0x70];
    void *unk144;
    void *unk148;
    void *unk14C;
    char pad150[0x44];
    void *unk194;
    char pad198[0x4];
    void *unk19C;
    char pad1A0[0x24];
    void *unk1C4;
    void *unk1C8;
    void *unk1CC;
    void *unk1D0;
    void *unk1D4;
    void *unk1D8;
    void *unk1DC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00426900  RaceInput::~RaceInput() [high]
 *   1: 0x00426F00  RaceInput::fetch() [high]
 *   2: 0x0055F948  PDISTD::ControlBase::feedback() [high]
 *   3: 0x00426CE0  RaceInput::getAutomobileConfig(AutomobileDeviceConfig&) [high]
 *   4: 0x00426D50  RaceInput::getAutomobileControl(_AutomobileControl&, _AutomobileControl*) [high]
 *   5: 0x00426EA0  RaceInput::setFeedback(AutomobileFeedback&) [high]
 *   6: 0x00426E58  RaceInput::replayControl(_AutomobileControl&) [high]
 *   7: 0x00426E80  RaceInput::recordControl(_AutomobileControl&) [high]
 */

#endif /* GT4_RaceInput_H */
