/* gt4/RaceDisplayDiffEvent.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDisplayDiffEvent : RaceDisplayEventBase
 * type_info 0x0088F390, type_info function 0x005F7BB0, structors 0x003A34E8
 * vtable 0x0067E780: 3 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_RaceDisplayDiffEvent_H
#define GT4_RaceDisplayDiffEvent_H

#include "types.h"

struct RaceDisplayDiffEvent {
    char pad0[0x4];
    void *unk4;
    s32 unk8;
    s32 unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005BC5C0
 *   1: 0x003A3520  RaceDisplayDiffEvent::encode() const [high]
 *   2: 0x003A35C8  RaceDisplayDiffEvent::decode(int) [high]
 */

#endif /* GT4_RaceDisplayDiffEvent_H */
