/* gt4/RaceSolitaireInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceSolitaireInformation : RaceInformation
 * type_info 0x0088F8D0, type_info function 0x005FE478, structors 0x003E9A08, 0x003E9A40
 * vtable 0x00683920: 19 slots
 * size: not known; the fields seen reach 0x131
 */
#ifndef GT4_RaceSolitaireInformation_H
#define GT4_RaceSolitaireInformation_H

#include "types.h"

struct RaceSolitaireInformation {
    char pad0[0x12C];
    union {
        void *unk12C;
        s32 unk12C_s32;
    };
    char unk130[1];
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003E9A40  RaceSolitaireInformation::~RaceSolitaireInformation() [high]
 *   1: 0x003BB4C8
 *   2: 0x003BB4D0
 *   3: 0x003BB4E8
 *   4: 0x003E9AB8  RaceSolitaireInformation::createEntry() [high]
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003E9AF0  RaceSolitaireInformation::getEntryCars() [high]
 *  11: 0x003BB7E0
 *  12: 0x003E9AF8  RaceSolitaireInformation::updateEntryCar(RaceEntryCar&) [high]
 *  13: 0x003E9B70  RaceSolitaireInformation::finishEntryCar(RaceOrganization&) [high]
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceSolitaireInformation_H */
