/* gt4/RaceDisplayMessageEvent.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDisplayMessageEvent : RaceDisplayEventBase
 * type_info 0x0088F3C0, type_info function 0x005F7E60, structors 0x003A3880
 * vtable 0x0067E690: 3 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_RaceDisplayMessageEvent_H
#define GT4_RaceDisplayMessageEvent_H

#include "types.h"

struct RaceDisplayMessageEvent {
    char pad0[0x4];
    void *unk4;
    s32 unk8;
    s32 unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003A38B8  RaceDisplayMessageEvent::getEventType() const [high]
 *   1: 0x003A38C0  RaceDisplayMessageEvent::encode() const [high]
 *   2: 0x003A38E8  RaceDisplayMessageEvent::decode(int) [high]
 */

#endif /* GT4_RaceDisplayMessageEvent_H */
