/* gt4/RaceMTRMultiFunctionDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMTRMultiFunctionDisplay : RaceDisplayObjectBase
 * type_info 0x0088F450, type_info function 0x005F9AA8, structors 0x003AD4D8, 0x003AD518
 * vtable 0x0067EE20: 10 slots
 * size: not known; the fields seen reach 0x18
 * C++ (GT4_CXX): size 0x18 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceMTRMultiFunctionDisplay_H
#define GT4_RaceMTRMultiFunctionDisplay_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceMTRMultiFunctionDisplay : public RaceDisplayObjectBase {
public:
    virtual s32 update(f32);  /* 9: RaceMTRMultiFunctionDisplay::update(float) */
    s32 update_auto_info(f32);  /* 0x003AD628 */
    s32 render_buffer(void *);  /* 0x003AD8E8 */
    s32 showInformation(s32, f32);  /* 0x003ADCE8 */
};
#else
struct RaceMTRMultiFunctionDisplay {
    char pad0[0x14];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceMTRMultiFunctionDisplay__update(struct RaceMTRMultiFunctionDisplay *, f32);
s32 RaceMTRMultiFunctionDisplay__update_auto_info(struct RaceMTRMultiFunctionDisplay *, f32);
s32 RaceMTRMultiFunctionDisplay__render_main(struct RaceMTRMultiFunctionDisplay *, void *);
s32 RaceMTRMultiFunctionDisplay__render_buffer(struct RaceMTRMultiFunctionDisplay *, void *);
s32 RaceMTRMultiFunctionDisplay__showInformation(struct RaceMTRMultiFunctionDisplay *, s32, f32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003AD518  RaceMTRMultiFunctionDisplay::~RaceMTRMultiFunctionDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003AD6F8  RaceMTRMultiFunctionDisplay::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003AD5E8  RaceMTRMultiFunctionDisplay::update(float) [high]
 */

#endif /* GT4_RaceMTRMultiFunctionDisplay_H */
