/* gt4/RaceSuggestedGearDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceSuggestedGearDisplay : RaceDisplayObjectBase
 * type_info 0x0088F540, type_info function 0x005F8D40, structors 0x0039AB68, 0x003A6FA8, 0x005F8CD8, 0x005F9E90, 0x005FA130
 * vtable 0x0067F4A0: 11 slots
 * size: not known; the fields seen reach 0x18
 * C++ (GT4_CXX): size 0x18 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceSuggestedGearDisplay_H
#define GT4_RaceSuggestedGearDisplay_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceSuggestedGearDisplay : public RaceDisplayObjectBase {
public:
    virtual void virtual_9();  /* 9: parameters from the code */
    virtual f32 virtual_10(f32);  /* 10: GT HD (medium): RaceSuggestedGearDisplay::update(float); parameters from the code */
};
#else
struct RaceSuggestedGearDisplay {
    char pad0[0x14];
    void *unk14;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
void RaceSuggestedGearDisplay__render_main(struct RaceSuggestedGearDisplay *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F8CD8  RaceSuggestedGearDisplay::~RaceSuggestedGearDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003A7108  RaceSuggestedGearDisplay::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003A7040
 *  10: 0x003A7048  RaceSuggestedGearDisplay::update(float) [medium]
 */

#endif /* GT4_RaceSuggestedGearDisplay_H */
