/* gt4/RacePhotoModeCameraManager.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RacePhotoModeCameraManager
 * type_info 0x0088F7C0, type_info function 0x005FD6B8, structors 0x003C6C98, 0x003C6E08, 0x005FD650, 0x005FD708
 * vtable 0x006820C8: 71 slots
 * size: not known; the fields seen reach 0xF88
 */
#ifndef GT4_RacePhotoModeCameraManager_H
#define GT4_RacePhotoModeCameraManager_H

#include "types.h"

struct RacePhotoModeCameraManager {
    char pad0[0x9C0];
    f32 unk9C0;
    char pad9C4[0x10];
    f32 unk9D4;
    char pad9D8[0x268];
    s32 unkC40;
    s32 unkC44;
    char padC48[0x240];
    f32 unkE88;
    f32 unkE8C;
    f32 unkE90;
    char padE94[0xF0];
    f32 unkF84;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FD650
 *   1: 0x003C80A0
 *   2: 0x003C8060
 *   3: 0x00373718
 *   4: 0x00373780
 *   5: 0x003737E8
 *   6: 0x0044F210
 *   7: 0x0044F280
 *   8: 0x0044F2F0
 *   9: 0x003C7F78
 *  10: 0x003C8008
 *  11: 0x00371C28
 *  12: 0x00371CA8
 *  13: 0x00371CF8
 *  14: 0x00371D18
 *  15: 0x00371DB8
 *  16: 0x00371E30
 *  17: 0x00371EA8
 *  18: 0x00373630
 *  19: 0x00373698
 *  20: 0x00377DE0
 *  21: 0x00372DF8
 *  22: 0x003780F8
 *  23: 0x00371F38
 *  24: 0x00377C60
 *  25: 0x00372018
 *  26: 0x00373700
 *  27: 0x00373850
 *  28: 0x003738C0
 *  29: 0x00373930
 *  30: 0x00378418
 *  31: 0x003739F0
 *  32: 0x00373AA0
 *  33: 0x00373AF8
 *  34: 0x00373B50
 *  35: 0x00373BA8
 *  36: 0x00373C00
 *  37: 0x00373C78
 *  38: 0x00373C68
 *  39: 0x00373C80
 *  40: 0x00373C88
 *  41: 0x00373D08
 *  42: 0x00373D38
 *  43: 0x00373DC0
 *  44: 0x00373DD8
 *  45: 0x00373E00
 *  46: 0x00373E08
 *  47: 0x00373E10
 *  48: 0x00373E18
 *  49: 0x00373E20
 *  50: 0x00373E28
 *  51: 0x00378478
 *  52: 0x00378480
 *  53: 0x00373EF8
 *  54: 0x00373F18
 *  55: 0x003785D0
 *  56: 0x00374E88
 *  57: 0x00377F10
 *  58: 0x00377F30
 *  59: 0x00377F60
 *  60: 0x00378400
 *  61: 0x00378410
 *  62: 0x00378408
 *  63: 0x00378220
 *  64: 0x00378298
 *  65: 0x00378328
 *  66: 0x003783A0
 *  67: 0x00378460
 *  68: 0x00378468
 *  69: 0x00378470
 *  70: 0x00378498
 */

#endif /* GT4_RacePhotoModeCameraManager_H */
