/* gt4/RaceLapTimesDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceLapTimesDisplay : RaceDisplayObjectBase
 * type_info 0x0088F5D0, type_info function 0x005F8340, structors 0x0039AB68, 0x003A4600, 0x005F82D8
 * vtable 0x0067F8A8: 9 slots
 * size: not known; the fields seen reach 0x18
 */
#ifndef GT4_RaceLapTimesDisplay_H
#define GT4_RaceLapTimesDisplay_H

#include "types.h"

struct RaceLapTimesDisplay {
    char pad0[0x14];
    void *unk14;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F82D8  RaceLapTimesDisplay::~RaceLapTimesDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003A4660  RaceLapTimesDisplay::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 */

#endif /* GT4_RaceLapTimesDisplay_H */
