/* gt4/RaceMachineTestInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMachineTestInformation : RaceInformation
 * type_info 0x0088F720, type_info function 0x005FB3E8, structors 0x003BDB98, 0x003BDBD8
 * vtable 0x006813E0: 19 slots
 * size: not known; the fields seen reach 0x131
 * C++ (GT4_CXX): size 0x134 (not known: up to the last field seen), vptr at 0x12C, fields left out (overlap, or in the base's part): 0x118, 0x12C
 */
#ifndef GT4_RaceMachineTestInformation_H
#define GT4_RaceMachineTestInformation_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceInformation.h"

class RaceMachineTestInformation : public RaceInformation {
public:
    char unk130[1];
    char pad131[0x3];
};
#else
struct RaceMachineTestInformation {
    char pad0[0x118];
    s32 unk118;
    char pad11C[0x10];
    union {
        s32 unk12C;
        void *unk12C_pvoid;
    };
    char unk130[1];
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceMachineTestInformation__createEntry(struct RaceMachineTestInformation *);
s32 RaceMachineTestInformation__updateEntryCar(struct RaceMachineTestInformation *, struct RaceEntryCar *);
void RaceMachineTestInformation__finishEntryCar(struct RaceMachineTestInformation *, void *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003BDBD8  RaceMachineTestInformation::~RaceMachineTestInformation() [high]
 *   1: 0x003BB4C8
 *   2: 0x003BB4D0
 *   3: 0x003BB4E8
 *   4: 0x003BDC50  RaceMachineTestInformation::createEntry() [high]
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003BB568
 *  11: 0x003BB7E0
 *  12: 0x003BDC88  RaceMachineTestInformation::updateEntryCar(RaceEntryCar&) [high]
 *  13: 0x003BDCE0  RaceMachineTestInformation::finishEntryCar(RaceOrganization&) [high]
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceMachineTestInformation_H */
