/* gt4/RaceMTRSpeedMeterPanel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMTRSpeedMeterPanel : RaceDisplayObjectBase
 * type_info 0x0088F550, type_info function 0x005F9A38, structors 0x003ACE18, 0x003ACE68
 * vtable 0x0067EE80: 10 slots
 * size: not known; the fields seen reach 0x34
 * C++ (GT4_CXX): size 0x34 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceMTRSpeedMeterPanel_H
#define GT4_RaceMTRSpeedMeterPanel_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceMTRSpeedMeterPanel : public RaceDisplayObjectBase {
public:
    s32 unk18;
    s32 unk1C;
    char pad20[0x4];
    s32 unk24;
    s32 unk28;
    s32 unk2C;
    s32 unk30;
    virtual void update(f32);  /* 9: RaceMTRSpeedMeterPanel::update(float) */
    s32 render_buffer(void *);  /* 0x003AD0D0 */
    s32 init_texset();  /* 0x003AD458 */
};
#else
struct RaceMTRSpeedMeterPanel {
    char pad0[0x14];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    s32 unk18;
    s32 unk1C;
    char pad20[0x4];
    s32 unk24;
    s32 unk28;
    s32 unk2C;
    s32 unk30;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
void RaceMTRSpeedMeterPanel__update(struct RaceMTRSpeedMeterPanel *, f32);
s32 RaceMTRSpeedMeterPanel__render_main(struct RaceMTRSpeedMeterPanel *, void *);
s32 RaceMTRSpeedMeterPanel__render_buffer(struct RaceMTRSpeedMeterPanel *, void *);
s32 RaceMTRSpeedMeterPanel__init_texset(struct RaceMTRSpeedMeterPanel *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003ACE68  RaceMTRSpeedMeterPanel::~RaceMTRSpeedMeterPanel() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003ACEE0  RaceMTRSpeedMeterPanel::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003ACED8  RaceMTRSpeedMeterPanel::update(float) [high]
 */

#endif /* GT4_RaceMTRSpeedMeterPanel_H */
