/* gt4/RaceMTRMeterPanel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMTRMeterPanel : RaceDisplayObjectBase
 * type_info 0x0088F480, type_info function 0x005F9950, structors 0x003AC3E8, 0x003AC4E8
 * vtable 0x0067EF40: 10 slots
 * size: not known; the fields seen reach 0x18
 * C++ (GT4_CXX): size 0x18 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceMTRMeterPanel_H
#define GT4_RaceMTRMeterPanel_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceMTRMeterPanel : public RaceDisplayObjectBase {
public:
    virtual s32 update(f32);  /* 9: RaceMTRMeterPanel::update(float) */
    s32 init_texset();  /* 0x003AC610 */
};
#else
struct RaceMTRMeterPanel {
    char pad0[0x14];
    void *unk14;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceMTRMeterPanel__update(struct RaceMTRMeterPanel *, f32);
s32 RaceMTRMeterPanel__init_texset(struct RaceMTRMeterPanel *);
s32 RaceMTRMeterPanel__render_main(struct RaceMTRMeterPanel *, void *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003AC4E8  RaceMTRMeterPanel::~RaceMTRMeterPanel() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003AC650  RaceMTRMeterPanel::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003AC5A8  RaceMTRMeterPanel::update(float) [high]
 */

#endif /* GT4_RaceMTRMeterPanel_H */
