/* gt4/RaceNetRallyBattleInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceNetRallyBattleInformation : RaceNetSinglePlayerInformation
 * type_info 0x0088EFF0, type_info function 0x005F35A0, structors 0x00339318, 0x00339348
 * vtable 0x00679218: 19 slots
 * size: not known; the fields seen reach 0x131
 */
#ifndef GT4_RaceNetRallyBattleInformation_H
#define GT4_RaceNetRallyBattleInformation_H

#include "types.h"

struct RaceNetRallyBattleInformation {
    char pad0[0x118];
    s32 unk118;
    char pad11C[0x10];
    union {
        char *unk12C;
        void *unk12C_pvoid;
        s32 unk12C_s32;
    };
    char unk130[1];
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00339348
 *   1: 0x003BB4C8
 *   2: 0x003D5B70
 *   3: 0x003D5B88
 *   4: 0x003D5BA8
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003BB568
 *  11: 0x003BB7E0
 *  12: 0x003D5BE0
 *  13: 0x003D5C10
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceNetRallyBattleInformation_H */
