/* gt4/RaceMTRMeter.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceMTRMeter : RaceDisplayObjectBase
 * type_info 0x0088F580, type_info function 0x005F98C0, structors 0x003ABA80, 0x003ABAD8
 * vtable 0x0067EFA0: 10 slots
 * size: not known; the fields seen reach 0x70
 */
#ifndef GT4_RaceMTRMeter_H
#define GT4_RaceMTRMeter_H

#include "types.h"

struct RaceMTRMeter {
    char pad0[0x14];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    s32 unk18;
    s32 unk1C;
    s32 unk20;
    s32 unk24;
    s32 unk28;
    s32 unk2C;
    char pad30[0x3C];
    s32 unk6C;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003ABAD8  RaceMTRMeter::~RaceMTRMeter() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003ABBF0  RaceMTRMeter::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003ABBD0  RaceMTRMeter::update(float) [medium]
 */

#endif /* GT4_RaceMTRMeter_H */
