/* gt4/RaceEventQueue.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceEventQueue
 * type_info 0x006D5FF8, type_info function 0x005FB040, structors 0x003B73D0, 0x003B7408
 * vtable 0x0067FC40: 1 slots
 * size: not known; the fields seen reach 0x82C
 */
#ifndef GT4_RaceEventQueue_H
#define GT4_RaceEventQueue_H

#include "types.h"

struct RaceEventQueue {
    char pad0[0x828];
    void *unk828;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003B7408  RaceEventQueue::~RaceEventQueue() [high]
 */

#endif /* GT4_RaceEventQueue_H */
