/* gt4/RaceInputLan.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceInputLan : RaceInput
 * type_info 0x0088EF80, type_info function 0x005F3368, structors 0x00335C80, 0x00335CB0
 * vtable 0x00678620: 8 slots
 * size: not known; the fields seen reach 0x1E0
 * C++ (GT4_CXX): size 0x1E0 (not known: up to the last field seen), vptr at 0xD0, fields left out (overlap, or in the base's part): 0xD0, 0x1D0
 */
#ifndef GT4_RaceInputLan_H
#define GT4_RaceInputLan_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceInput.h"

class RaceInputLan : public RaceInput {
public:
};
#else
struct RaceInputLan {
    char pad0[0xD0];
    union {
        void *unkD0;
        s32 unkD0_s32;
    };
    char padD4[0x70];
    void *unk144;
    void *unk148;
    void *unk14C;
    char pad150[0x44];
    void *unk194;
    char pad198[0x4];
    void *unk19C;
    char pad1A0[0x24];
    void *unk1C4;
    void *unk1C8;
    void *unk1CC;
    union {
        s32 unk1D0;
        void *unk1D0_pvoid;
    };
    void *unk1D4;
    void *unk1D8;
    void *unk1DC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceInputLan__virtual_04(struct RaceInputLan *, void *, void *);
s32 RaceInputLan__virtual_05(struct RaceInputLan *, void *);
s32 RaceInput__getAutomobileConfig(struct RaceInputLan *, void *);
s32 RaceInput__replayControl(struct RaceInputLan *, void *);
s32 RaceInput__recordControl(struct RaceInputLan *, void *);
s32 RaceInput__fetch(struct RaceInputLan *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00335CB0
 *   1: 0x00426F00
 *   2: 0x0055F948
 *   3: 0x00426CE0
 *   4: 0x00335D18
 *   5: 0x00335DB0
 *   6: 0x00426E58
 *   7: 0x00426E80
 */

#endif /* GT4_RaceInputLan_H */
