/* gt4/RaceOnboardSpeedmeter.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceOnboardSpeedmeter : RaceRoundMeterBase
 * type_info 0x0088F900, type_info function 0x005FE638, structors 0x003EB7A0
 * vtable 0x00683A08: 16 slots
 * size: not known; the fields seen reach 0x24
 */
#ifndef GT4_RaceOnboardSpeedmeter_H
#define GT4_RaceOnboardSpeedmeter_H

#include "types.h"

struct RaceOnboardSpeedmeter {
    s32 unk0;
    char pad4[0x10];
    union {
        s32 unk14;
        void *unk14_pvoid;
    };
    s32 unk18;
    s32 unk1C;
    s32 unk20;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FE5D0  RaceOnboardSpeedmeter::~RaceOnboardSpeedmeter() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003BE318
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003BE228
 *  10: 0x003BE3A0
 *  11: 0x003BE3A8
 *  12: 0x003BE3B8
 *  13: 0x003BE5F0
 *  14: 0x003BE5F8
 *  15: 0x003BE3C8
 */

#endif /* GT4_RaceOnboardSpeedmeter_H */
