/* gt4/RaceInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceInformation
 * type_info 0x006D6008, type_info function 0x005FB200, structors 0x003BB340, 0x003BB3D8
 * vtable 0x006806E8: 19 slots
 * size: not known; the fields seen reach 0x130
 */
#ifndef GT4_RaceInformation_H
#define GT4_RaceInformation_H

#include "types.h"

struct RaceInformation {
    char pad0[0x12C];
    s32 unk12C;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003BB3D8  RaceInformation::~RaceInformation() [high]
 *   1: 0x003BB4C8  RaceInformation::getRaceCode() [high]
 *   2: 0x003BB4D0  RaceInformation::getCourseCode() [high]
 *   3: 0x003BB4E8  RaceInformation::setCourseCode(unsigned long long) [high]
 *   4: 0x003BB508  RaceInformation::createEntry() [high]
 *   5: 0x003BB528  RaceInformation::getCountDown() [high]
 *   6: 0x003BB530  RaceInformation::getRaceLaps() [high]
 *   7: 0x003BB550  RaceInformation::getTimeLimit() [high]
 *   8: 0x003BB558  RaceInformation::getPauseTimeLimit() [high]
 *   9: 0x003BB560  RaceInformation::setEntryCars(int) [high]
 *  10: 0x003BB568  RaceInformation::getEntryCars() [high]
 *  11: 0x003BB7E0  RaceInformation::getDriversPoints(int) [high]
 *  12: 0x003BB570  RaceInformation::updateEntryCar(RaceEntryCar&) [high]
 *  13: 0x003BB578  RaceInformation::finishEntryCar(RaceOrganization&) [high]
 *  14: 0x003BB5A8  RaceInformation::randomEnemyPickup(RaceOrganization&, int*, int, int) [high]
 *  15: 0x003BB750  RaceInformation::randomEnemyPickup(RaceOrganization&, int, int, int) [high]
 *  16: 0x005FB268  RaceInformation::setCourseSection(int) [high]
 *  17: 0x005FB270  RaceInformation::getCourseSection() [high]
 *  18: 0x005FB278  RaceInformation::getRaceDB() [high]
 */

#endif /* GT4_RaceInformation_H */
