/* gt4/RaceShiftPositionDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceShiftPositionDisplay : RaceDisplayObjectBase
 * type_info 0x0088F560, type_info function 0x005F8C28, structors 0x0039AB68, 0x003A6CE0, 0x005F8BC0, 0x005F9E90, 0x005FA130
 * vtable 0x0067F508: 11 slots
 * size: not known; the fields seen reach 0x18
 * C++ (GT4_CXX): size 0x18 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x10, 0x14
 */
#ifndef GT4_RaceShiftPositionDisplay_H
#define GT4_RaceShiftPositionDisplay_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceShiftPositionDisplay : public RaceDisplayObjectBase {
public:
    virtual s32 init_texset();  /* 9: RaceShiftPositionDisplay::init_texset() */
    virtual f32 update(f32);  /* 10: RaceShiftPositionDisplay::update(float) */
};
#else
struct RaceShiftPositionDisplay {
    char pad0[0x10];
    s32 unk10;
    void *unk14;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceShiftPositionDisplay__init_texset(struct RaceShiftPositionDisplay *);
s32 RaceShiftPositionDisplay__update(struct RaceShiftPositionDisplay *, f32);
void RaceShiftPositionDisplay__render_main(struct RaceShiftPositionDisplay *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F8BC0  RaceShiftPositionDisplay::~RaceShiftPositionDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003A6DE0  RaceShiftPositionDisplay::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003A6D30  RaceShiftPositionDisplay::init_texset() [high]
 *  10: 0x003A6D60  RaceShiftPositionDisplay::update(float) [high]
 */

#endif /* GT4_RaceShiftPositionDisplay_H */
