/* gt4/RaceGTmode.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceGTmode : RaceSinglePlayer
 * type_info 0x0088F970, type_info function 0x005FEA58, structors 0x003EDE50, 0x003EDFC8
 * vtable 0x00684678: 152 slots
 * size: not known; the fields seen reach 0xE428
 */
#ifndef GT4_RaceGTmode_H
#define GT4_RaceGTmode_H

#include "types.h"

struct RaceGTmode {
    char pad0[0x64];
    union {
        s32 unk64;
        void *unk64_pvoid;
    };
    char pad68[0x4];
    union {
        s32 unk6C;
        void *unk6C_pvoid;
    };
    char pad70[0xC58];
    u32 unkCC8;
    char padCCC[0x50];
    s32 unkD1C;
    char padD20[0x18];
    s32 unkD38;
    f32 unkD3C;
    char padD40[0xC];
    s32 unkD4C;
    char padD50[0x8];
    s32 unkD58;
    s32 unkD5C;
    char padD60[0x8];
    s32 unkD68;
    char padD6C[0x14];
    s32 unkD80;
    s32 (*unkD84)(s32, s32);
    s32 unkD88;
    char padD8C[0xC1BC];
    f32 unkCF48;
    union {
        f32 unkCF4C;
        s32 unkCF4C_s32;
    };
    char padCF50[0x4];
    f32 unkCF54;
    char padCF58[0x8];
    s32 unkCF60;
    char padCF64[0x58];
    s32 unkCFBC;
    char padCFC0[0x1440];
    void *unkE400;
    void *unkE404;
    void *unkE408;
    void *unkE40C;
    void *unkE410;
    void *unkE414;
    void *unkE418;
    void *unkE41C;
    void *unkE420;
    void *unkE424;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003EDFC8  RaceGTmode::~RaceGTmode() [high]
 *   1: 0x001010E0
 *   2: 0x001097A8
 *   3: 0x001097E8
 *   4: 0x003EE108  RaceGTmode::controlFetch() [high]
 *   5: 0x00109868
 *   6: 0x0033C470
 *   7: 0x00101148
 *   8: 0x001012C8
 *   9: 0x001099A8
 *  10: 0x001099E8
 *  11: 0x00101308
 *  12: 0x001013D0
 *  13: 0x00101140
 *  14: 0x00101288
 *  15: 0x0033D970
 *  16: 0x0033CE40
 *  17: 0x00387DF8
 *  18: 0x003D5FC0
 *  19: 0x00387E10
 *  20: 0x00387ED0
 *  21: 0x00387E60
 *  22: 0x0038B778
 *  23: 0x00387EE0
 *  24: 0x00387EE8
 *  25: 0x00387E38
 *  26: 0x00388E38
 *  27: 0x0033C300
 *  28: 0x0033C358
 *  29: 0x0038A288
 *  30: 0x0038A2B0
 *  31: 0x0038A2C8
 *  32: 0x0033CEF0
 *  33: 0x0038B970
 *  34: 0x0038BA70
 *  35: 0x0038B980
 *  36: 0x0038BA80
 *  37: 0x003EE138  RaceGTmode::initialize(int) [high]
 *  38: 0x00388790
 *  39: 0x003EE390  RaceGTmode::postInitialize() [high]
 *  40: 0x0038A1A8
 *  41: 0x0038A1E8
 *  42: 0x0033CA98
 *  43: 0x0033CD20
 *  44: 0x003888E8
 *  45: 0x00388958
 *  46: 0x003889E0
 *  47: 0x00388B50
 *  48: 0x00388C00
 *  49: 0x00388C88
 *  50: 0x00388CC8
 *  51: 0x00388E00
 *  52: 0x00389130
 *  53: 0x00389230
 *  54: 0x00389268
 *  55: 0x003892C8
 *  56: 0x003D5F00
 *  57: 0x003D5F30
 *  58: 0x003D5F60
 *  59: 0x00389388
 *  60: 0x003893C0
 *  61: 0x00389420
 *  62: 0x003894C0
 *  63: 0x00389538
 *  64: 0x00389540
 *  65: 0x00389548
 *  66: 0x00387E08
 *  67: 0x003EDDD8  RaceGTmode::raceName() [high]
 *  68: 0x00389560
 *  69: 0x003D5EB0
 *  70: 0x003895F8
 *  71: 0x003D5EC0
 *  72: 0x0033C490
 *  73: 0x003D5FF8
 *  74: 0x0033C858
 *  75: 0x0033C9C8
 *  76: 0x0038B2B0
 *  77: 0x0033CA90
 *  78: 0x00389D48
 *  79: 0x0033CCF0
 *  80: 0x00389DE8
 *  81: 0x00389DF0
 *  82: 0x00389DF8
 *  83: 0x00389E00
 *  84: 0x00389E08
 *  85: 0x00389E88
 *  86: 0x0038AAB0
 *  87: 0x003EE330  RaceGTmode::cleanup() [high]
 *  88: 0x0033C3B0
 *  89: 0x0033C3E8
 *  90: 0x0033CE90
 *  91: 0x003EE3C8  RaceGTmode::changeEntryCarTire() [high]
 *  92: 0x0038A270
 *  93: 0x005F6978
 *  94: 0x005F6980
 *  95: 0x0038A2F0
 *  96: 0x0038A328
 *  97: 0x0038A3A8
 *  98: 0x0038A3B0
 *  99: 0x0033CED8
 * 100: 0x0033BBF8
 * 101: 0x0033BD00
 * 102: 0x0033C180
 * 103: 0x0033C278
 * 104: 0x0038B520
 * 105: 0x0033F890
 * 106: 0x0038B5A0
 * 107: 0x0038B6C8
 * 108: 0x0033FD88
 * 109: 0x003403B8
 * 110: 0x003411D0
 * 111: 0x00340950
 * 112: 0x00341710
 * 113: 0x00341A30
 * 114: 0x00340870
 * 115: 0x0033F880
 * 116: 0x003422B0
 * 117: 0x00341CC8
 * 118: 0x0038BCD8
 * 119: 0x00341E50
 * 120: 0x0038B728
 * 121: 0x0033E860
 * 122: 0x005F3B30
 * 123: 0x005F3B38
 * 124: 0x005F3B40
 * 125: 0x00342768
 * 126: 0x003428A8
 * 127: 0x0033C428
 * 128: 0x0033C438
 * 129: 0x0038BD78
 * 130: 0x0038BE10
 * 131: 0x0033C450
 * 132: 0x0038BD28
 * 133: 0x0033CB70
 * 134: 0x0033CB10
 * 135: 0x0033CB30
 * 136: 0x0033CB50
 * 137: 0x0033CCD8
 * 138: 0x0033CC80
 * 139: 0x003431B8
 * 140: 0x0033F888
 * 141: 0x0033CF08
 * 142: 0x0033FD50
 * 143: 0x0033C158
 * 144: 0x003411A8
 * 145: 0x00340690
 * 146: 0x00342EE0
 * 147: 0x003426A0
 * 148: 0x0038B0E0
 * 149: 0x0038B428
 * 150: 0x0038B4B8
 * 151: 0x0038B788
 */

#endif /* GT4_RaceGTmode_H */
