/* gt4/RaceNetBattle.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceNetBattle
 * type_info 0x0088EFD0, type_info function 0x005F3550, structors 0x003389F0, 0x00338B80
 * vtable 0x006787C0: 152 slots
 * size: not known; the fields seen reach 0xE428
 * C++ (GT4_CXX): size 0xE428 (not known: up to the last field seen), vptr at 0x64 (introduced here)
 */
#ifndef GT4_RaceNetBattle_H
#define GT4_RaceNetBattle_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

/* g++ 2.96 puts the vptr after the own fields of the class that introduces it; RaceNetBattle has fields after 0x64, so a base without RTTI introduced it */
class RaceNetBattle_vbase {
public:
    char pad0[0x64];
    virtual s32 virtual_0(s32);  /* 0: parameters from the code */
    virtual s32 virtual_1();  /* 1: parameters from the code */
    virtual s32 virtual_2();  /* 2: parameters from the code */
    virtual s32 virtual_3();  /* 3: parameters from the code */
    virtual s32 virtual_4();  /* 4: parameters from the code */
    virtual s32 virtual_5();  /* 5: parameters from the code */
    virtual s32 virtual_6();  /* 6: parameters from the code */
    virtual s32 virtual_7();  /* 7: parameters from the code */
    virtual s32 virtual_8();  /* 8: parameters from the code */
    virtual s32 virtual_9();  /* 9: parameters from the code */
    virtual s32 virtual_10();  /* 10: parameters from the code */
    virtual s32 virtual_11();  /* 11: parameters from the code */
    virtual s32 virtual_12();  /* 12: parameters from the code */
    virtual void virtual_13();  /* 13: parameters from the code */
    virtual s32 virtual_14();  /* 14: parameters from the code */
    virtual s32 virtual_15(s32);  /* 15: parameters from the code */
    virtual s32 virtual_16();  /* 16: parameters from the code */
    virtual s32 virtual_17();  /* 17: parameters from the code */
    virtual s32 virtual_18();  /* 18: parameters from the code */
    virtual f32 virtual_19();  /* 19: parameters from the code */
    virtual s32 virtual_20();  /* 20: parameters from the code */
    virtual s32 virtual_21(s32);  /* 21: parameters from the code */
    virtual s32 virtual_22();  /* 22: parameters from the code */
    virtual s32 virtual_23();  /* 23: parameters from the code */
    virtual s32 virtual_24();  /* 24: parameters from the code */
    virtual s32 virtual_25();  /* 25: parameters from the code */
    virtual s32 virtual_26(s32);  /* 26: parameters from the code */
    virtual s32 virtual_27(s32);  /* 27: parameters from the code */
    virtual s32 virtual_28(s32);  /* 28: parameters from the code */
    virtual s32 virtual_29(f32);  /* 29: parameters from the code */
    virtual s32 virtual_30();  /* 30: parameters from the code */
    virtual s32 virtual_31();  /* 31: parameters from the code */
    virtual s32 virtual_32();  /* 32: parameters from the code */
    virtual s32 virtual_33();  /* 33: parameters from the code */
    virtual s32 virtual_34();  /* 34: parameters from the code */
    virtual s32 virtual_35();  /* 35: parameters from the code */
    virtual s32 virtual_36();  /* 36: parameters from the code */
    virtual s32 virtual_37(s32);  /* 37: parameters from the code */
    virtual s32 virtual_38();  /* 38: parameters from the code */
    virtual s32 virtual_39();  /* 39: parameters from the code */
    virtual s32 virtual_40();  /* 40: parameters from the code */
    virtual s32 virtual_41();  /* 41: parameters from the code */
    virtual s32 virtual_42(f32);  /* 42: parameters from the code */
    virtual s32 virtual_43();  /* 43: parameters from the code */
    virtual s32 virtual_44();  /* 44: parameters from the code */
    virtual void virtual_45();  /* 45: parameters from the code */
    virtual s32 virtual_46();  /* 46: parameters from the code */
    virtual s32 virtual_47();  /* 47: parameters from the code */
    virtual s32 virtual_48();  /* 48: parameters from the code */
    virtual s32 virtual_49();  /* 49: parameters from the code */
    virtual s32 virtual_50();  /* 50: parameters from the code */
    virtual s32 virtual_51();  /* 51: parameters from the code */
    virtual s32 virtual_52(s32);  /* 52: parameters from the code */
    virtual s32 virtual_53();  /* 53: parameters from the code */
    virtual s32 virtual_54(s32);  /* 54: parameters from the code */
    virtual s32 virtual_55(s32);  /* 55: parameters from the code */
    virtual void virtual_56();  /* 56: parameters from the code */
    virtual void virtual_57();  /* 57: parameters from the code */
    virtual s32 virtual_58();  /* 58: parameters from the code */
    virtual s32 virtual_59();  /* 59: parameters from the code */
    virtual s32 virtual_60(s32);  /* 60: parameters from the code */
    virtual s32 virtual_61(s32);  /* 61: parameters from the code */
    virtual s32 virtual_62(s32);  /* 62: parameters from the code */
    virtual void virtual_63();  /* 63: parameters from the code */
    virtual void virtual_64();  /* 64: parameters from the code */
    virtual s32 virtual_65();  /* 65: parameters from the code */
    virtual void virtual_66();  /* 66: parameters from the code */
    virtual s32 virtual_67();  /* 67: parameters from the code */
    virtual s32 virtual_68();  /* 68: parameters from the code */
    virtual s32 virtual_69();  /* 69: parameters from the code */
    virtual s32 virtual_70();  /* 70: parameters from the code */
    virtual s32 virtual_71(s32);  /* 71: parameters from the code */
    virtual s32 virtual_72();  /* 72: parameters from the code */
    virtual s32 virtual_73(f32);  /* 73: parameters from the code */
    virtual s32 virtual_74();  /* 74: parameters from the code */
    virtual s32 virtual_75();  /* 75: parameters from the code */
    virtual s32 virtual_76();  /* 76: parameters from the code */
    virtual void virtual_77();  /* 77: parameters from the code */
    virtual s32 virtual_78();  /* 78: parameters from the code */
    virtual s32 virtual_79();  /* 79: parameters from the code */
    virtual s32 virtual_80();  /* 80: parameters from the code */
    virtual s32 virtual_81();  /* 81: parameters from the code */
    virtual s32 virtual_82();  /* 82: parameters from the code */
    virtual void virtual_83();  /* 83: parameters from the code */
    virtual s32 virtual_84(s32, s32);  /* 84: parameters from the code */
    virtual s32 virtual_85();  /* 85: parameters from the code */
    virtual s32 virtual_86(s32, f32, f32);  /* 86: parameters from the code */
    virtual s32 virtual_87();  /* 87: parameters from the code */
    virtual s32 virtual_88();  /* 88: parameters from the code */
    virtual s32 virtual_89();  /* 89: parameters from the code */
    virtual s32 virtual_90();  /* 90: parameters from the code */
    virtual void virtual_91();  /* 91: parameters from the code */
    virtual s32 virtual_92();  /* 92: parameters from the code */
    virtual void virtual_93(s32);  /* 93: parameters from the code */
    virtual s32 virtual_94();  /* 94: parameters from the code */
    virtual s32 virtual_95(s32);  /* 95: parameters from the code */
    virtual s32 virtual_96(s32);  /* 96: parameters from the code */
    virtual s32 virtual_97();  /* 97: parameters from the code */
    virtual s32 virtual_98();  /* 98: parameters from the code */
    virtual s32 virtual_99();  /* 99: parameters from the code */
    virtual s32 virtual_100(s32);  /* 100: parameters from the code */
    virtual s32 virtual_101();  /* 101: parameters from the code */
    virtual s32 virtual_102();  /* 102: parameters from the code */
    virtual s32 virtual_103();  /* 103: parameters from the code */
    virtual s32 virtual_104(s32, f32);  /* 104: parameters from the code */
    virtual s32 virtual_105(s32);  /* 105: parameters from the code */
    virtual s32 virtual_106(s32);  /* 106: parameters from the code */
    virtual s32 virtual_107(s32);  /* 107: parameters from the code */
    virtual s32 virtual_108(s32, s32, f32);  /* 108: parameters from the code */
    virtual s32 virtual_109(s32, s32);  /* 109: parameters from the code */
    virtual s32 virtual_110(s32, s32, s32, f32);  /* 110: parameters from the code */
    virtual s32 virtual_111(s32, s32, s32, s32, f32);  /* 111: parameters from the code */
    virtual s32 virtual_112(s32, f32);  /* 112: parameters from the code */
    virtual s32 virtual_113();  /* 113: parameters from the code */
    virtual s32 virtual_114(s32, s32);  /* 114: parameters from the code */
    virtual void virtual_115();  /* 115: parameters from the code */
    virtual s32 virtual_116(s32);  /* 116: parameters from the code */
    virtual s32 virtual_117();  /* 117: parameters from the code */
    virtual s32 virtual_118();  /* 118: parameters from the code */
    virtual s32 virtual_119(s32, s32);  /* 119: parameters from the code */
    virtual s32 virtual_120();  /* 120: parameters from the code */
    virtual s32 virtual_121();  /* 121: parameters from the code */
    virtual void virtual_122();  /* 122: parameters from the code */
    virtual void virtual_123();  /* 123: parameters from the code */
    virtual void virtual_124();  /* 124: parameters from the code */
    virtual s32 virtual_125(f32);  /* 125: parameters from the code */
    virtual s32 virtual_126();  /* 126: parameters from the code */
    virtual s32 virtual_127();  /* 127: parameters from the code */
    virtual s32 virtual_128();  /* 128: parameters from the code */
    virtual s32 virtual_129();  /* 129: parameters from the code */
    virtual s32 virtual_130();  /* 130: parameters from the code */
    virtual s32 virtual_131();  /* 131: parameters from the code */
    virtual s32 virtual_132();  /* 132: parameters from the code */
    virtual s32 virtual_133(s32, s32);  /* 133: parameters from the code */
    virtual s32 virtual_134();  /* 134: parameters from the code */
    virtual s32 virtual_135();  /* 135: parameters from the code */
    virtual s32 virtual_136();  /* 136: parameters from the code */
    virtual s32 virtual_137(s32, s32);  /* 137: parameters from the code */
    virtual s32 virtual_138();  /* 138: parameters from the code */
    virtual s32 virtual_139();  /* 139: parameters from the code */
    virtual s32 virtual_140();  /* 140: parameters from the code */
    virtual s32 virtual_141(s32);  /* 141: parameters from the code */
    virtual f32 virtual_142();  /* 142: parameters from the code */
    virtual s32 virtual_143();  /* 143: parameters from the code */
    virtual s32 virtual_144();  /* 144: parameters from the code */
    virtual s32 virtual_145(s32, s32);  /* 145: parameters from the code */
    virtual void virtual_146();  /* 146: parameters from the code */
    virtual void virtual_147();  /* 147: parameters from the code */
    virtual s32 virtual_148();  /* 148: parameters from the code */
    virtual s32 virtual_149(s32);  /* 149: parameters from the code */
    virtual s32 virtual_150();  /* 150: parameters from the code */
    virtual s32 virtual_151();  /* 151: parameters from the code */
};

class RaceNetBattle : public RaceNetBattle_vbase {
public:
    char pad68[0xC60];
    union {
        s32 unkCC8;
        u32 unkCC8_u32;
    };
    char padCCC[0xD73C];
    s32 unkE408;
    s32 unkE40C;
    s32 unkE410;
    s32 unkE414;
    char padE418[0xC];
    union {
        s32 unkE424;
        void *unkE424_pvoid;
    };
};
#else
struct RaceNetBattle {
    char pad0[0xCC8];
    union {
        s32 unkCC8;
        u32 unkCC8_u32;
    };
    char padCCC[0xD73C];
    s32 unkE408;
    s32 unkE40C;
    s32 unkE410;
    s32 unkE414;
    char padE418[0xC];
    union {
        s32 unkE424;
        void *unkE424_pvoid;
    };
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceBasic__terminate(struct RaceNetBattle *, s32, f32, f32);
void RaceBasic__notifyChangeSpecMode(struct RaceNetBattle *);
void RaceBasic__pauseStart(struct RaceNetBattle *, struct PauseBase *);
s32 RaceBasic__pauseEnd(struct RaceNetBattle *);
s32 RaceBasic__render_world(struct RaceNetBattle *, void *, f32);
s32 RaceBasic__render_panel(struct RaceNetBattle *, void *);
s32 RaceBasic__render_other(struct RaceNetBattle *, void *);
s32 RaceBasic__DMAsafe(struct RaceNetBattle *);
s32 RaceBasic__getReplayPauseExit(struct RaceNetBattle *);
s32 RaceBasic__getAutoDemoPauseExit(struct RaceNetBattle *);
s32 RaceBasic__getPitMenu(struct RaceNetBattle *);
s32 RaceBasic__getPitMenuObj(struct RaceNetBattle *);
s32 RaceBasic__getFuelDialog(struct RaceNetBattle *);
s32 RaceBasic__getFuelDialogObj(struct RaceNetBattle *);
s32 RaceBasic__get_back_mirror_rate(struct RaceNetBattle *);
s32 RaceBasic__isCrossFadeEnabled(struct RaceNetBattle *);
s32 RaceBasic__printSoundMode(struct RaceNetBattle *);
s32 RaceBasic__printAccelerateMode(struct RaceNetBattle *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00338B80
 *   1: 0x001010E0
 *   2: 0x001097A8
 *   3: 0x001097E8
 *   4: 0x00109830
 *   5: 0x00109868
 *   6: 0x0033C470
 *   7: 0x00101148
 *   8: 0x001012C8
 *   9: 0x001099A8
 *  10: 0x001099E8
 *  11: 0x00101308
 *  12: 0x001013D0
 *  13: 0x00101140
 *  14: 0x00101288
 *  15: 0x0033D970
 *  16: 0x0033CE40
 *  17: 0x00387DF8
 *  18: 0x0038AB40
 *  19: 0x00387E10
 *  20: 0x00387ED0
 *  21: 0x00387E60
 *  22: 0x0038B778
 *  23: 0x00338F50
 *  24: 0x00387EE8
 *  25: 0x00387E38
 *  26: 0x00388E38
 *  27: 0x0033C300
 *  28: 0x0033C358
 *  29: 0x0038A288
 *  30: 0x0038A2B0
 *  31: 0x0038A2C8
 *  32: 0x0033CEF0
 *  33: 0x0038B970
 *  34: 0x0038BA70
 *  35: 0x0038B980
 *  36: 0x0038BA80
 *  37: 0x00338D38
 *  38: 0x00388790
 *  39: 0x00338EB8
 *  40: 0x0038A1A8
 *  41: 0x0038A1E8
 *  42: 0x0033CA98
 *  43: 0x0033CD20
 *  44: 0x003888E8
 *  45: 0x00388958
 *  46: 0x00338E40
 *  47: 0x00388B50
 *  48: 0x00388C00
 *  49: 0x00388C88
 *  50: 0x00388CC8
 *  51: 0x00388E00
 *  52: 0x00389130
 *  53: 0x00389230
 *  54: 0x00389268
 *  55: 0x003892C8
 *  56: 0x00389370
 *  57: 0x00389378
 *  58: 0x00389380
 *  59: 0x00389388
 *  60: 0x003893C0
 *  61: 0x00389420
 *  62: 0x003894C0
 *  63: 0x00389538
 *  64: 0x00389540
 *  65: 0x00389548
 *  66: 0x00387E08
 *  67: 0x00338978
 *  68: 0x00338CD8
 *  69: 0x00338D08
 *  70: 0x003895F8
 *  71: 0x00338D18
 *  72: 0x00339010
 *  73: 0x003390B8
 *  74: 0x0033C858
 *  75: 0x0033C9C8
 *  76: 0x00339288
 *  77: 0x0033CA90
 *  78: 0x00389D48
 *  79: 0x0033CCF0
 *  80: 0x00338F60
 *  81: 0x00389DF0
 *  82: 0x00338F58
 *  83: 0x00338F80
 *  84: 0x00338FA0
 *  85: 0x00389E88
 *  86: 0x0038AAB0
 *  87: 0x00338F28
 *  88: 0x0033C3B0
 *  89: 0x0033C3E8
 *  90: 0x0033CE90
 *  91: 0x0038A268
 *  92: 0x0038A270
 *  93: 0x005F6978
 *  94: 0x005F6980
 *  95: 0x0038A2F0
 *  96: 0x0038A328
 *  97: 0x0038A3A8
 *  98: 0x0038A3B0
 *  99: 0x0033CED8
 * 100: 0x0033BBF8
 * 101: 0x0033BD00
 * 102: 0x0033C180
 * 103: 0x0033C278
 * 104: 0x0038B520
 * 105: 0x0033F890
 * 106: 0x0038B5A0
 * 107: 0x0038B6C8
 * 108: 0x0033FD88
 * 109: 0x003403B8
 * 110: 0x003411D0
 * 111: 0x00340950
 * 112: 0x00341710
 * 113: 0x00341A30
 * 114: 0x00340870
 * 115: 0x0033F880
 * 116: 0x003422B0
 * 117: 0x00341CC8
 * 118: 0x0038BCD8
 * 119: 0x00341E50
 * 120: 0x0038B728
 * 121: 0x0033E860
 * 122: 0x005F3B30
 * 123: 0x005F3B38
 * 124: 0x005F3B40
 * 125: 0x00342768
 * 126: 0x003428A8
 * 127: 0x0033C428
 * 128: 0x0033C438
 * 129: 0x0038BD78
 * 130: 0x0038BE10
 * 131: 0x0033C450
 * 132: 0x0038BD28
 * 133: 0x0033CB70
 * 134: 0x0033CB10
 * 135: 0x0033CB30
 * 136: 0x0033CB50
 * 137: 0x0033CCD8
 * 138: 0x0033CC80
 * 139: 0x003431B8
 * 140: 0x0033F888
 * 141: 0x0033CF08
 * 142: 0x0033FD50
 * 143: 0x0033C158
 * 144: 0x003411A8
 * 145: 0x00340690
 * 146: 0x00342EE0
 * 147: 0x003426A0
 * 148: 0x00339218
 * 149: 0x0038B428
 * 150: 0x0038B4B8
 * 151: 0x0038B788
 */

#endif /* GT4_RaceNetBattle_H */
