/* gt4/RaceRankDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceRankDisplay : RaceDisplayObjectBase
 * type_info 0x0088F530, type_info function 0x005F7F38, structors 0x0039AB68, 0x003A3AE0, 0x005F7ED0
 * vtable 0x0067FA60: 10 slots
 * size: not known; the fields seen reach 0x24
 * C++ (GT4_CXX): size 0x24 (not known: up to the last field seen), vptr at 0x14, fields left out (overlap, or in the base's part): 0x14
 */
#ifndef GT4_RaceRankDisplay_H
#define GT4_RaceRankDisplay_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayObjectBase.h"

class RaceRankDisplay : public RaceDisplayObjectBase {
public:
    void *unk18;
    void *unk1C;
    void *unk20;
    virtual f32 virtual_9();  /* 9: GT HD (medium): RaceRankDisplay::update(float); parameters from the code */
    void setRank(s32, bool);  /* 0x003A3EC8 */
};
#else
struct RaceRankDisplay {
    char pad0[0x14];
    void *unk14;
    void *unk18;
    void *unk1C;
    void *unk20;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceRankDisplay__render_main(struct RaceRankDisplay *, void *);
void RaceRankDisplay__setRank(struct RaceRankDisplay *, s32, s32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F7ED0  RaceRankDisplay::~RaceRankDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003A3B58  RaceRankDisplay::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003A3B38  RaceRankDisplay::update(float) [medium]
 */

#endif /* GT4_RaceRankDisplay_H */
