/* gt4/RaceRankDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceRankDisplay : RaceDisplayObjectBase
 * type_info 0x0088F530, type_info function 0x005F7F38, structors 0x0039AB68, 0x003A3AE0, 0x005F7ED0
 * vtable 0x0067FA60: 10 slots
 * size: not known; the fields seen reach 0x24
 */
#ifndef GT4_RaceRankDisplay_H
#define GT4_RaceRankDisplay_H

#include "types.h"

struct RaceRankDisplay {
    char pad0[0x14];
    void *unk14;
    void *unk18;
    void *unk1C;
    void *unk20;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F7ED0  RaceRankDisplay::~RaceRankDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x003A3B58  RaceRankDisplay::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x003A3B38  RaceRankDisplay::update(float) [medium]
 */

#endif /* GT4_RaceRankDisplay_H */
