/* gt4/RaceEntryCar.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceEntryCar
 * type_info 0x006D5FD8, type_info function 0x005FABB0, structors 0x003B4B38, 0x003B4CE0
 * vtable 0x0067FBF8: 1 slots
 * size: not known; the fields seen reach 0x35D0
 */
#ifndef GT4_RaceEntryCar_H
#define GT4_RaceEntryCar_H

#include "types.h"

struct RaceEntryCar {
    char pad0[0x2890];
    void *unk2890;
    char pad2894[0xD38];
    void *unk35CC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003B4CE0  RaceEntryCar::~RaceEntryCar() [high]
 */

#endif /* GT4_RaceEntryCar_H */
