/* gt4/RaceTimeDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceTimeDisplay : RaceValueDisplayBase
 * type_info 0x0088F400, type_info function 0x005F8270, structors 0x003A4360
 * vtable 0x0067F900: 9 slots
 * size: not known; the fields seen reach 0x18
 */
#ifndef GT4_RaceTimeDisplay_H
#define GT4_RaceTimeDisplay_H

#include "types.h"

struct RaceTimeDisplay {
    char pad0[0x14];
    void *unk14;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F8208  RaceTimeDisplay::~RaceTimeDisplay() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003A4338
 *   4: 0x003A43A8  RaceTimeDisplay::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 */

#endif /* GT4_RaceTimeDisplay_H */
