/* gt4/RaceLicenseBGM.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceLicenseBGM : RaceBGMPS2
 * type_info 0x0088F700, type_info function 0x005FB2E0, structors 0x003BBE18, 0x003BBE50
 * vtable 0x00680CA8: 9 slots
 * size: not known; the fields seen reach 0x11EC
 * C++ (GT4_CXX): size 0x11EC (not known: up to the last field seen), vptr at 0x4, fields left out (overlap, or in the base's part): 0x4
 */
#ifndef GT4_RaceLicenseBGM_H
#define GT4_RaceLicenseBGM_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceBGMPS2.h"

class RaceLicenseBGM : public RaceBGMPS2 {
public:
    char pad8[0x11E0];
    s32 unk11E8;
};
#else
struct RaceLicenseBGM {
    char pad0[0x4];
    union {
        void *unk4;
        s32 unk4_s32;
    };
    char pad8[0x11E0];
    s32 unk11E8;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceLicenseBGM__play(struct RaceLicenseBGM *, s32, s32);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003BBE50  RaceLicenseBGM::~RaceLicenseBGM() [high]
 *   1: 0x0033D170
 *   2: 0x0033D498
 *   3: 0x0033D4A8
 *   4: 0x003BBEB8  RaceLicenseBGM::play(int, bool) [high]
 *   5: 0x0033D890
 *   6: 0x0033D8B0
 *   7: 0x0033D8D0
 *   8: 0x0033D950
 */

#endif /* GT4_RaceLicenseBGM_H */
