/* gt4/RacePS2Base.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RacePS2Base : RaceBase
 * type_info 0x0088F020, type_info function 0x005F3AE0, structors 0x0033B8A8, 0x0033BA98
 * vtable 0x00679378: 148 slots
 * size: not known; the fields seen reach 0xCFC0
 * C++ (GT4_CXX): size 0xCFC0 (not known: up to the last field seen), vptr at 0x64, fields left out (overlap, or in the base's part): 0x6C
 */
#ifndef GT4_RacePS2Base_H
#define GT4_RacePS2Base_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceBase.h"
class CameraBase;
class RaceEntryCar;
class VehicleModel;

class RacePS2Base : public RaceBase {
public:
    char padD6C[0x14];
    s32 unkD80;
    s32 (*unkD84)(s32, s32);
    s32 unkD88;
    char padD8C[0xC1BC];
    f32 unkCF48;
    union {
        f32 unkCF4C;
        s32 unkCF4C_s32;
    };
    char padCF50[0x4];
    f32 unkCF54;
    char padCF58[0x8];
    s32 unkCF60;
    char padCF64[0x58];
    s32 unkCFBC;
    virtual s32 play(s32);  /* 100: RacePS3Base::play(int) */
    virtual s32 checkReplayLoop();  /* 101: RacePS3Base::checkReplayLoop() */
    virtual s32 virtual_102();  /* 102: GT HD (medium): RacePS3Base::initializePlayList(); parameters from the code */
    virtual s32 virtual_103();  /* 103: GT HD (medium): RacePS3Base::cleanupPlayList(); parameters from the code */
    virtual s32 render_world(void *, f32);  /* 104: RacePS3Base::render_world(GSBuffer&, float) */
    virtual s32 render_post_effect(void *);  /* 105: RacePS3Base::render_post_effect(GSBuffer&) */
    virtual s32 render_panel(void *);  /* 106: RacePS3Base::render_panel(GSBuffer&) */
    virtual s32 render_other(void *);  /* 107: RacePS3Base::render_other(GSBuffer&) */
    virtual s32 render_world_split(void *, bool, f32);  /* 108: RacePS3Base::render_world_split(GSBuffer&, bool, float) */
    virtual s32 render_course(CameraBase &, bool);  /* 109: RacePS3Base::render_course(CameraBase&, bool) */
    virtual s32 render_reflection(void *, void *, bool, f32);  /* 110: RacePS3Base::render_reflection(GSBuffer&, GSBuffer&, bool, float) */
    virtual s32 render_cars(void *, s32, f32, bool, s32);  /* 111: RacePS3Base::render_cars(GSBuffer&, int, float, bool, int) */
    virtual s32 render_reflection_cars(void *, f32);  /* 112: RacePS3Base::render_reflection_cars(GSBuffer&, float) */
    virtual s32 render_reflection_car_lights(f32);  /* 113: RacePS3Base::render_reflection_car_lights(float) */
    virtual s32 render_exchange_tire(s32, const VehicleModel &);  /* 114: RacePS3Base::render_exchange_tire(int, VehicleModel const&) */
    virtual void render_concourse(void *);  /* 115: RacePS3Base::render_concourse(GSBuffer&) */
    virtual s32 render_after(CameraBase &);  /* 116: RacePS3Base::render_after(CameraBase&) */
    virtual s32 render_use_back_mirror() const;  /* 117: RacePS3Base::render_use_back_mirror() const */
    virtual f32 get_back_mirror_rate() const;  /* 118: RacePS3Base::get_back_mirror_rate() const */
    virtual s32 render_back_mirror(void *, bool);  /* 119: RacePS3Base::render_back_mirror(GSBuffer&, bool) */
    virtual void DMAsafe();  /* 120: RacePS3Base::DMAsafe() */
    virtual s32 virtual_121();  /* 121: GT HD (medium): RacePS3Base::start_driver_computing(); parameters from the code */
    virtual void virtual_122();  /* 122: parameters from the code */
    virtual void virtual_123();  /* 123: parameters from the code */
    virtual void virtual_124();  /* 124: parameters from the code */
    virtual s32 virtual_125(f32);  /* 125: GT HD (medium): RacePS3Base::set_car_flares(bool, float); parameters from the code */
    virtual s32 virtual_126();  /* 126: GT HD (medium): RacePS3Base::set_course_flares(); parameters from the code */
    virtual s32 soundMute();  /* 127: RacePS3Base::soundMute() */
    virtual s32 soundToggle();  /* 128: RacePS3Base::soundToggle() */
    virtual void printSoundMode();  /* 129: RacePS3Base::printSoundMode() */
    virtual void printAccelerateMode();  /* 130: RacePS3Base::printAccelerateMode() */
    virtual s32 virtual_131();  /* 131: GT HD (medium): RacePS3Base::getCurrentMusicInformation(); parameters from the code */
    virtual s32 isCrossFadeEnabled() const;  /* 132: RacePS3Base::isCrossFadeEnabled() const */
    virtual s32 computePitCamera(s32, void *);  /* 133: RacePS3Base::computePitCamera(int, RacePS3Base::Motion_Camera&) */
    virtual s32 isPitCameraPeriod(s32) const;  /* 134: RacePS3Base::isPitCameraPeriod(int) const */
    virtual s32 isPitHandCameraPeriod(s32) const;  /* 135: RacePS3Base::isPitHandCameraPeriod(int) const */
    virtual s32 isExtensionPitCameraPeriod(s32) const;  /* 136: RacePS3Base::isExtensionPitCameraPeriod(int) const */
    virtual s32 computeInterruptMotionCamera(s32, void *);  /* 137: RacePS3Base::computeInterruptMotionCamera(int, RacePS3Base::Motion_Camera&) */
    virtual s32 isInterruptMotionCameraPeriod(s32) const;  /* 138: RacePS3Base::isInterruptMotionCameraPeriod(int) const */
    virtual s32 isUseDefocusEffect() const;  /* 139: RacePS3Base::isUseDefocusEffect() const */
    virtual s32 isRenderConcourse() const;  /* 140: RacePS3Base::isRenderConcourse() const */
    virtual s32 virtual_141(s32);  /* 141: parameters from the code */
    virtual f32 getMasterVolume() const;  /* 142: RacePS3Base::getMasterVolume() const */
    virtual s32 initializeReplayStyle();  /* 143: RacePS3Base::initializeReplayStyle() */
    virtual s32 isUseProjectionShadow();  /* 144: RacePS3Base::isUseProjectionShadow() */
    virtual s32 isRenderCar(RaceEntryCar *, void *, f32);  /* 145: RacePS3Base::isRenderCar(RaceEntryCar*, CameraSys::CameraManager&, float) */
    virtual void render_dash_panel(void *, f32);  /* 146: RacePS3Base::render_dash_panel(GSBuffer&, float) */
    virtual s32 is_able_to_render_this_car(RaceEntryCar &);  /* 147: RacePS3Base::is_able_to_render_this_car(RaceEntryCar&) */
    void updateVolume();  /* 0x0033FC60 */
    s32 is_render_pitin_car(RaceEntryCar &);  /* 0x003426B8 */
};
#else
struct RacePS2Base {
    char pad0[0x64];
    s32 unk64;
    char pad68[0x4];
    union {
        s32 unk6C;
        void *unk6C_pvoid;
    };
    char pad70[0xC58];
    u32 unkCC8;
    char padCCC[0x50];
    s32 unkD1C;
    char padD20[0x18];
    s32 unkD38;
    f32 unkD3C;
    char padD40[0xC];
    s32 unkD4C;
    char padD50[0x8];
    s32 unkD58;
    s32 unkD5C;
    char padD60[0x8];
    s32 unkD68;
    char padD6C[0x14];
    s32 unkD80;
    s32 (*unkD84)(s32, s32);
    s32 unkD88;
    char padD8C[0xC1BC];
    f32 unkCF48;
    union {
        f32 unkCF4C;
        s32 unkCF4C_s32;
    };
    char padCF50[0x4];
    f32 unkCF54;
    char padCF58[0x8];
    s32 unkCF60;
    char padCF64[0x58];
    s32 unkCFBC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RacePS2Base__play(struct RacePS2Base *, s32);
s32 RacePS2Base__checkReplayLoop(struct RacePS2Base *);
s32 RacePS2Base__initialize(struct RacePS2Base *, s32);
s32 RacePS2Base__initializeReplayStyle(struct RacePS2Base *);
s32 RacePS2Base__cleanup(struct RacePS2Base *);
s32 RacePS2Base__getReplayPlayList(struct RacePS2Base *, void *);
s32 RacePS2Base__setReplayPlayList(struct RacePS2Base *, void *);
s32 RacePS2Base__soundStart(struct RacePS2Base *);
s32 RacePS2Base__soundStop(struct RacePS2Base *);
s32 RacePS2Base__soundMute(struct RacePS2Base *);
void RacePS2Base__soundToggle(struct RacePS2Base *);
s32 RacePS2Base__update(struct RacePS2Base *);
s32 RacePS2Base__updateCommon(struct RacePS2Base *);
s32 RacePS2Base__updatePlay(struct RacePS2Base *, f32);
void RacePS2Base__updateRace(struct RacePS2Base *);
s32 RacePS2Base__virtual_75(struct RacePS2Base *);
void RacePS2Base__updateOther(struct RacePS2Base *);
s32 RacePS2Base__updatePitmen(struct RacePS2Base *, f32);
s32 RacePS2Base__isPitCameraPeriod(struct RacePS2Base *, s32);
s32 RacePS2Base__isPitHandCameraPeriod(struct RacePS2Base *, s32);
s32 RacePS2Base__isExtensionPitCameraPeriod(struct RacePS2Base *, s32);
s32 RacePS2Base__computePitCamera(struct RacePS2Base *, s32, void *);
s32 RacePS2Base__isInterruptMotionCameraPeriod(struct RacePS2Base *, s32);
s32 RacePS2Base__computeInterruptMotionCamera(struct RacePS2Base *, s32, void *);
void RacePS2Base__raceEnd(struct RacePS2Base *);
s32 RacePS2Base__replayStart(struct RacePS2Base *);
s32 RacePS2Base__DMAsafe(struct RacePS2Base *);
s32 RacePS2Base__idle(struct RacePS2Base *);
s32 RacePS2Base__signalHandler(struct RacePS2Base *);
s32 RacePS2Base__getLastKey(struct RacePS2Base *);
s32 RacePS2Base__getFrameInterval(struct RacePS2Base *);
void RacePS2Base__printSoundMode(struct RacePS2Base *);
void RacePS2Base__printAccelerateMode(struct RacePS2Base *);
s32 RacePS2Base__render(struct RacePS2Base *, void *);
s32 RacePS2Base__render_world(struct RacePS2Base *, void *, f32);
void RacePS2Base__render_concourse(struct RacePS2Base *, void *);
s32 RacePS2Base__isRenderConcourse(struct RacePS2Base *);
s32 RacePS2Base__render_post_effect(struct RacePS2Base *, void *);
s32 RacePS2Base__render_panel(struct RacePS2Base *, void *);
s32 RacePS2Base__render_other(struct RacePS2Base *, void *);
void RacePS2Base__updateVolume(struct RacePS2Base *);
s32 RacePS2Base__getMasterVolume(struct RacePS2Base *);
s32 RacePS2Base__render_world_split(struct RacePS2Base *, void *, s32, f32);
s32 RacePS2Base__render_course(struct RacePS2Base *, struct CameraBase *, s32);
s32 RacePS2Base__isRenderCar(struct RacePS2Base *, struct RaceEntryCar *, void *, f32);
s32 RacePS2Base__render_exchange_tire(struct RacePS2Base *, s32, const struct VehicleModel *);
s32 RacePS2Base__render_cars(struct RacePS2Base *, void *, s32, f32, s32, s32);
s32 RacePS2Base__isUseProjectionShadow(struct RacePS2Base *);
s32 RacePS2Base__render_reflection(struct RacePS2Base *, void *, void *, s32, f32);
s32 RacePS2Base__render_reflection_cars(struct RacePS2Base *, void *, f32);
s32 RacePS2Base__render_reflection_car_lights(struct RacePS2Base *, f32);
s32 RacePS2Base__render_use_back_mirror(struct RacePS2Base *);
f32 RacePS2Base__get_back_mirror_rate(struct RacePS2Base *);
s32 RacePS2Base__render_back_mirror(struct RacePS2Base *, void *, s32);
s32 RacePS2Base__render_after(struct RacePS2Base *, struct CameraBase *);
void RacePS2Base__is_able_to_render_this_car(struct RacePS2Base *, struct RaceEntryCar *);
s32 RacePS2Base__is_render_pitin_car(struct RacePS2Base *, struct RaceEntryCar *);
s32 RacePS2Base__isCrossFadeEnabled(struct RacePS2Base *);
void RacePS2Base__render_dash_panel(struct RacePS2Base *, void *, f32);
s32 RacePS2Base__isUseDefocusEffect(struct RacePS2Base *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0033BA98  RacePS3Base::~RacePS3Base() [high]
 *   1: 0x001010E0
 *   2: 0x001097A8
 *   3: 0x001097E8
 *   4: 0x00109830
 *   5: 0x00109868
 *   6: 0x0033C470  RacePS3Base::update() [high]
 *   7: 0x00101148
 *   8: 0x001012C8
 *   9: 0x001099A8
 *  10: 0x001099E8
 *  11: 0x00101308
 *  12: 0x001013D0
 *  13: 0x00101140
 *  14: 0x00101288
 *  15: 0x0033D970  RacePS3Base::render(GSBuffer&) [high]
 *  16: 0x0033CE40  RacePS3Base::idle() [high]
 *  17: 0x00387DF8
 *  18: 0x00387DF0
 *  19: 0x00387E10
 *  20: 0x00387ED0
 *  21: 0x00387E60
 *  22: 0x00387ED8
 *  23: 0x00387EE0
 *  24: 0x00387EE8
 *  25: 0x00387E38
 *  26: 0x00388E38
 *  27: 0x0033C300  RacePS3Base::getReplayPlayList(GranTurismo4::BGMPlayList&) [high]
 *  28: 0x0033C358  RacePS3Base::setReplayPlayList(GranTurismo4::BGMPlayList&) [high]
 *  29: 0x0038A288
 *  30: 0x0038A2B0
 *  31: 0x0038A2C8
 *  32: 0x0033CEF0  RacePS3Base::getFrameInterval() [high]
 *  33: 0x0038A368
 *  34: 0x0038A370
 *  35: 0x0038A378
 *  36: 0x0038A380
 *  37: 0x0033BDB0  RacePS3Base::initialize(int) [high]
 *  38: 0x00388790
 *  39: 0x00388880
 *  40: 0x0038A1A8
 *  41: 0x0038A1E8
 *  42: 0x0033CA98  RacePS3Base::updatePitmen(float) [high]
 *  43: 0x0033CD20  RacePS3Base::replayStart() [high]
 *  44: 0x003888E8
 *  45: 0x00388958
 *  46: 0x003889E0
 *  47: 0x00388B50
 *  48: 0x00388C00
 *  49: 0x00388C88
 *  50: 0x00388CC8
 *  51: 0x00388E00
 *  52: 0x00389130
 *  53: 0x00389230
 *  54: 0x00389268
 *  55: 0x003892C8
 *  56: 0x00389370
 *  57: 0x00389378
 *  58: 0x00389380
 *  59: 0x00389388
 *  60: 0x003893C0
 *  61: 0x00389420
 *  62: 0x003894C0
 *  63: 0x00389538
 *  64: 0x00389540
 *  65: 0x00389548
 *  66: 0x00387E08
 *  67: 0x00389550
 *  68: 0x00389560
 *  69: 0x00389590
 *  70: 0x003895F8
 *  71: 0x00389628
 *  72: 0x0033C490  RacePS3Base::updateCommon() [high]
 *  73: 0x0033C4F0  RacePS3Base::updatePlay(float) [high]
 *  74: 0x0033C858  RacePS3Base::updateRace() [high]
 *  75: 0x0033C9C8
 *  76: 0x00389D38
 *  77: 0x0033CA90  RacePS3Base::updateOther() [high]
 *  78: 0x00389D48
 *  79: 0x0033CCF0  RacePS3Base::raceEnd() [high]
 *  80: 0x00389DE8
 *  81: 0x00389DF0
 *  82: 0x00389DF8
 *  83: 0x00389E00
 *  84: 0x00389E08
 *  85: 0x00389E88
 *  86: 0x00389ED8
 *  87: 0x0033C210  RacePS3Base::cleanup() [high]
 *  88: 0x0033C3B0  RacePS3Base::soundStart() [high]
 *  89: 0x0033C3E8  RacePS3Base::soundStop() [high]
 *  90: 0x0033CE90  RacePS3Base::signalHandler() [high]
 *  91: 0x0038A268
 *  92: 0x0038A270
 *  93: 0x005F6978
 *  94: 0x005F6980
 *  95: 0x0038A2F0
 *  96: 0x0038A328
 *  97: 0x0038A3A8
 *  98: 0x0038A3B0
 *  99: 0x0033CED8  RacePS3Base::getLastKey() [high]
 * 100: 0x0033BBF8  RacePS3Base::play(int) [high]
 * 101: 0x0033BD00  RacePS3Base::checkReplayLoop() [high]
 * 102: 0x0033C180  RacePS3Base::initializePlayList() [medium]
 * 103: 0x0033C278  RacePS3Base::cleanupPlayList() [medium]
 * 104: 0x0033DEA8  RacePS3Base::render_world(GSBuffer&, float) [high]
 * 105: 0x0033F890  RacePS3Base::render_post_effect(GSBuffer&) [high]
 * 106: 0x0033FA40  RacePS3Base::render_panel(GSBuffer&) [high]
 * 107: 0x0033FA98  RacePS3Base::render_other(GSBuffer&) [high]
 * 108: 0x0033FD88  RacePS3Base::render_world_split(GSBuffer&, bool, float) [high]
 * 109: 0x003403B8  RacePS3Base::render_course(CameraBase&, bool) [high]
 * 110: 0x003411D0  RacePS3Base::render_reflection(GSBuffer&, GSBuffer&, bool, float) [high]
 * 111: 0x00340950  RacePS3Base::render_cars(GSBuffer&, int, float, bool, int) [high]
 * 112: 0x00341710  RacePS3Base::render_reflection_cars(GSBuffer&, float) [high]
 * 113: 0x00341A30  RacePS3Base::render_reflection_car_lights(float) [high]
 * 114: 0x00340870  RacePS3Base::render_exchange_tire(int, VehicleModel const&) [high]
 * 115: 0x0033F880  RacePS3Base::render_concourse(GSBuffer&) [high]
 * 116: 0x003422B0  RacePS3Base::render_after(CameraBase&) [high]
 * 117: 0x00341CC8  RacePS3Base::render_use_back_mirror() const [high]
 * 118: 0x00341D78  RacePS3Base::get_back_mirror_rate() const [high]
 * 119: 0x00341E50  RacePS3Base::render_back_mirror(GSBuffer&, bool) [high]
 * 120: 0x0033CD78  RacePS3Base::DMAsafe() [high]
 * 121: 0x0033E860  RacePS3Base::start_driver_computing() [medium]
 * 122: 0x005F3B30
 * 123: 0x005F3B38
 * 124: 0x005F3B40
 * 125: 0x00342768  RacePS3Base::set_car_flares(bool, float) [medium]
 * 126: 0x003428A8  RacePS3Base::set_course_flares() [medium]
 * 127: 0x0033C428  RacePS3Base::soundMute() [high]
 * 128: 0x0033C438  RacePS3Base::soundToggle() [high]
 * 129: 0x0033CF28  RacePS3Base::printSoundMode() [high]
 * 130: 0x0033CF30  RacePS3Base::printAccelerateMode() [high]
 * 131: 0x0033C450  RacePS3Base::getCurrentMusicInformation() [medium]
 * 132: 0x003429D8  RacePS3Base::isCrossFadeEnabled() const [high]
 * 133: 0x0033CB70  RacePS3Base::computePitCamera(int, RacePS3Base::Motion_Camera&) [high]
 * 134: 0x0033CB10  RacePS3Base::isPitCameraPeriod(int) const [high]
 * 135: 0x0033CB30  RacePS3Base::isPitHandCameraPeriod(int) const [high]
 * 136: 0x0033CB50  RacePS3Base::isExtensionPitCameraPeriod(int) const [high]
 * 137: 0x0033CCD8  RacePS3Base::computeInterruptMotionCamera(int, RacePS3Base::Motion_Camera&) [high]
 * 138: 0x0033CC80  RacePS3Base::isInterruptMotionCameraPeriod(int) const [high]
 * 139: 0x003431B8  RacePS3Base::isUseDefocusEffect() const [high]
 * 140: 0x0033F888  RacePS3Base::isRenderConcourse() const [high]
 * 141: 0x0033CF08
 * 142: 0x0033FD50  RacePS3Base::getMasterVolume() const [high]
 * 143: 0x0033C158  RacePS3Base::initializeReplayStyle() [high]
 * 144: 0x003411A8  RacePS3Base::isUseProjectionShadow() [high]
 * 145: 0x00340690  RacePS3Base::isRenderCar(RaceEntryCar*, CameraSys::CameraManager&, float) [high]
 * 146: 0x00342EE0  RacePS3Base::render_dash_panel(GSBuffer&, float) [high]
 * 147: 0x003426A0  RacePS3Base::is_able_to_render_this_car(RaceEntryCar&) [high]
 */

#endif /* GT4_RacePS2Base_H */
