/* gt4/RaceDisplayLapDiffEvent.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDisplayLapDiffEvent : RaceDisplayDiffEvent
 * type_info 0x0088F3E0, type_info function 0x005F7C90, structors 0x0035E8E8, 0x003A0308, 0x003C0310, 0x005F7CE0
 * vtable 0x0067E730: 3 slots
 * size: not known; the fields seen reach 0x10
 * C++ (GT4_CXX): size 0x10 (not known: up to the last field seen), vptr at 0x4
 */
#ifndef GT4_RaceDisplayLapDiffEvent_H
#define GT4_RaceDisplayLapDiffEvent_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/RaceDisplayDiffEvent.h"

class RaceDisplayLapDiffEvent : public RaceDisplayDiffEvent {
public:
};
#else
struct RaceDisplayLapDiffEvent {
    char pad0[0x4];
    void *unk4;
    s32 unk8;
    s32 unkC;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 RaceDisplayLapDiffEvent__structor_0(struct RaceDisplayLapDiffEvent *, s32, s32);
s32 RaceDisplayLapDiffEvent__getEventType(struct RaceDisplayLapDiffEvent *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003A3650  RaceDisplayLapDiffEvent::getEventType() const [high]
 *   1: 0x003A3520
 *   2: 0x003A35C8
 */

#endif /* GT4_RaceDisplayLapDiffEvent_H */
