/* gt4/RaceChampionshipInformation.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceChampionshipInformation : RaceInformation
 * type_info 0x0088F990, type_info function 0x005FEAA8, structors 0x003EE590, 0x003EE640
 * vtable 0x006850C0: 19 slots
 * size: not known; the fields seen reach 0x174
 */
#ifndef GT4_RaceChampionshipInformation_H
#define GT4_RaceChampionshipInformation_H

#include "types.h"

struct RaceChampionshipInformation {
    char pad0[0x12C];
    union {
        void *unk12C;
        s32 unk12C_s32;
    };
    char pad130[0x40];
    s32 unk170;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003EE640  RaceChampionshipInformation::~RaceChampionshipInformation() [high]
 *   1: 0x003BB4C8
 *   2: 0x003BB4D0
 *   3: 0x003BB4E8
 *   4: 0x003EE6F0  RaceChampionshipInformation::createEntry() [high]
 *   5: 0x003BB528
 *   6: 0x003BB530
 *   7: 0x003BB550
 *   8: 0x003BB558
 *   9: 0x003BB560
 *  10: 0x003BB568
 *  11: 0x003EF1C8  RaceChampionshipInformation::getDriversPoints(int) [high]
 *  12: 0x003EE728  RaceChampionshipInformation::updateEntryCar(RaceEntryCar&) [high]
 *  13: 0x003EE788  RaceChampionshipInformation::finishEntryCar(RaceOrganization&) [high]
 *  14: 0x003BB5A8
 *  15: 0x003BB750
 *  16: 0x005FB268
 *  17: 0x005FB270
 *  18: 0x005FB278
 */

#endif /* GT4_RaceChampionshipInformation_H */
