/* gt4/RacePhotoModeCameraManager.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RacePhotoModeCameraManager
 * type_info 0x0088F7C0, type_info function 0x005FD6B8, structors 0x003C6C98, 0x003C6E08, 0x005FD650, 0x005FD708
 * vtable 0x006820C8: 71 slots
 * size: not known; the fields seen reach 0xF88
 * C++ (GT4_CXX): size 0xF88 (not known: up to the last field seen), vptr at 0x0 (introduced here)
 */
#ifndef GT4_RacePhotoModeCameraManager_H
#define GT4_RacePhotoModeCameraManager_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

/* g++ 2.96 puts the vptr after the own fields of the class that introduces it; RacePhotoModeCameraManager has fields after 0x0, so a base without RTTI introduced it */
class RacePhotoModeCameraManager_vbase {
public:
    virtual s32 virtual_0(s32);  /* 0: parameters from the code */
    virtual s32 virtual_1(f32);  /* 1: parameters from the code */
    virtual s32 virtual_2(f32);  /* 2: parameters from the code */
    virtual s32 virtual_3(f32);  /* 3: parameters from the code */
    virtual s32 virtual_4(f32);  /* 4: parameters from the code */
    virtual s32 virtual_5(f32);  /* 5: parameters from the code */
    virtual s32 virtual_6(s32, f32);  /* 6: parameters from the code */
    virtual s32 virtual_7(s32, f32);  /* 7: parameters from the code */
    virtual f32 virtual_8(s32);  /* 8: parameters from the code */
    virtual s32 virtual_9();  /* 9: parameters from the code */
    virtual s32 virtual_10();  /* 10: parameters from the code */
    virtual s32 virtual_11();  /* 11: parameters from the code */
    virtual f32 virtual_12();  /* 12: parameters from the code */
    virtual f32 virtual_13();  /* 13: parameters from the code */
    virtual f32 virtual_14();  /* 14: parameters from the code */
    virtual s32 virtual_15();  /* 15: parameters from the code */
    virtual s32 virtual_16();  /* 16: parameters from the code */
    virtual s32 virtual_17();  /* 17: parameters from the code */
    virtual s32 virtual_18();  /* 18: parameters from the code */
    virtual s32 virtual_19();  /* 19: parameters from the code */
    virtual s32 virtual_20(s32);  /* 20: parameters from the code */
    virtual s32 virtual_21(s32, s32, s32);  /* 21: parameters from the code */
    virtual void virtual_22();  /* 22: parameters from the code */
    virtual s32 virtual_23(s32, f32);  /* 23: parameters from the code */
    virtual void virtual_24();  /* 24: parameters from the code */
    virtual s32 virtual_25(f32);  /* 25: parameters from the code */
    virtual s32 virtual_26(s32);  /* 26: parameters from the code */
    virtual s32 virtual_27(s32);  /* 27: parameters from the code */
    virtual s32 virtual_28(s32);  /* 28: parameters from the code */
    virtual s32 virtual_29(s32);  /* 29: parameters from the code */
    virtual s32 virtual_30();  /* 30: parameters from the code */
    virtual s32 virtual_31();  /* 31: parameters from the code */
    virtual s32 virtual_32();  /* 32: parameters from the code */
    virtual s32 virtual_33();  /* 33: parameters from the code */
    virtual s32 virtual_34();  /* 34: parameters from the code */
    virtual s32 virtual_35();  /* 35: parameters from the code */
    virtual s32 virtual_36();  /* 36: parameters from the code */
    virtual s32 virtual_37();  /* 37: parameters from the code */
    virtual s32 virtual_38(s32);  /* 38: parameters from the code */
    virtual s32 virtual_39();  /* 39: parameters from the code */
    virtual s32 virtual_40();  /* 40: parameters from the code */
    virtual s32 virtual_41(s32);  /* 41: parameters from the code */
    virtual s32 virtual_42();  /* 42: parameters from the code */
    virtual s32 virtual_43(s32);  /* 43: parameters from the code */
    virtual s32 virtual_44(s32, s32);  /* 44: parameters from the code */
    virtual s32 virtual_45();  /* 45: parameters from the code */
    virtual f32 virtual_46();  /* 46: parameters from the code */
    virtual s32 virtual_47();  /* 47: parameters from the code */
    virtual f32 virtual_48();  /* 48: parameters from the code */
    virtual s32 virtual_49();  /* 49: parameters from the code */
    virtual s32 virtual_50();  /* 50: parameters from the code */
    virtual s32 virtual_51();  /* 51: parameters from the code */
    virtual s32 virtual_52();  /* 52: parameters from the code */
    virtual s32 virtual_53(s32);  /* 53: parameters from the code */
    virtual s32 virtual_54();  /* 54: parameters from the code */
    virtual s32 virtual_55();  /* 55: parameters from the code */
    virtual void virtual_56();  /* 56: parameters from the code */
    virtual s32 virtual_57();  /* 57: parameters from the code */
    virtual f32 virtual_58();  /* 58: parameters from the code */
    virtual s32 virtual_59(s32, s32, s32);  /* 59: parameters from the code */
    virtual s32 virtual_60();  /* 60: parameters from the code */
    virtual s32 virtual_61();  /* 61: parameters from the code */
    virtual s32 virtual_62();  /* 62: parameters from the code */
    virtual s32 virtual_63();  /* 63: parameters from the code */
    virtual s32 virtual_64();  /* 64: parameters from the code */
    virtual s32 virtual_65();  /* 65: parameters from the code */
    virtual s32 virtual_66();  /* 66: parameters from the code */
    virtual f32 virtual_67();  /* 67: parameters from the code */
    virtual f32 virtual_68();  /* 68: parameters from the code */
    virtual f32 virtual_69();  /* 69: parameters from the code */
    virtual s32 virtual_70();  /* 70: parameters from the code */
};

class RacePhotoModeCameraManager : public RacePhotoModeCameraManager_vbase {
public:
    char pad4[0x9BC];
    f32 unk9C0;
    char pad9C4[0x10];
    f32 unk9D4;
    char pad9D8[0x268];
    s32 unkC40;
    s32 unkC44;
    char padC48[0x240];
    f32 unkE88;
    f32 unkE8C;
    f32 unkE90;
    char padE94[0xF0];
    f32 unkF84;
};
#else
struct RacePhotoModeCameraManager {
    char pad0[0x9C0];
    f32 unk9C0;
    char pad9C4[0x10];
    f32 unk9D4;
    char pad9D8[0x268];
    s32 unkC40;
    s32 unkC44;
    char padC48[0x240];
    f32 unkE88;
    f32 unkE8C;
    f32 unkE90;
    char padE94[0xF0];
    f32 unkF84;
};
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FD650
 *   1: 0x003C80A0
 *   2: 0x003C8060
 *   3: 0x00373718
 *   4: 0x00373780
 *   5: 0x003737E8
 *   6: 0x0044F210
 *   7: 0x0044F280
 *   8: 0x0044F2F0
 *   9: 0x003C7F78
 *  10: 0x003C8008
 *  11: 0x00371C28
 *  12: 0x00371CA8
 *  13: 0x00371CF8
 *  14: 0x00371D18
 *  15: 0x00371DB8
 *  16: 0x00371E30
 *  17: 0x00371EA8
 *  18: 0x00373630
 *  19: 0x00373698
 *  20: 0x00377DE0
 *  21: 0x00372DF8
 *  22: 0x003780F8
 *  23: 0x00371F38
 *  24: 0x00377C60
 *  25: 0x00372018
 *  26: 0x00373700
 *  27: 0x00373850
 *  28: 0x003738C0
 *  29: 0x00373930
 *  30: 0x00378418
 *  31: 0x003739F0
 *  32: 0x00373AA0
 *  33: 0x00373AF8
 *  34: 0x00373B50
 *  35: 0x00373BA8
 *  36: 0x00373C00
 *  37: 0x00373C78
 *  38: 0x00373C68
 *  39: 0x00373C80
 *  40: 0x00373C88
 *  41: 0x00373D08
 *  42: 0x00373D38
 *  43: 0x00373DC0
 *  44: 0x00373DD8
 *  45: 0x00373E00
 *  46: 0x00373E08
 *  47: 0x00373E10
 *  48: 0x00373E18
 *  49: 0x00373E20
 *  50: 0x00373E28
 *  51: 0x00378478
 *  52: 0x00378480
 *  53: 0x00373EF8
 *  54: 0x00373F18
 *  55: 0x003785D0
 *  56: 0x00374E88
 *  57: 0x00377F10
 *  58: 0x00377F30
 *  59: 0x00377F60
 *  60: 0x00378400
 *  61: 0x00378410
 *  62: 0x00378408
 *  63: 0x00378220
 *  64: 0x00378298
 *  65: 0x00378328
 *  66: 0x003783A0
 *  67: 0x00378460
 *  68: 0x00378468
 *  69: 0x00378470
 *  70: 0x00378498
 */

#endif /* GT4_RacePhotoModeCameraManager_H */
