/* gt4/RaceLapTime.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceLapTime
 * type_info 0x006D6010, type_info function 0x005FB280, structors 0x003BB9A0, 0x003BB9F8
 * vtable 0x00680790: 1 slots
 * C++ (GT4_CXX): size 0xFB8 (not known: up to the last field seen), vptr at 0xFB4 (introduced here)
 */
#ifndef GT4_RaceLapTime_H
#define GT4_RaceLapTime_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class RaceLapTime {
public:
    char pad0[0xFB4];
    virtual ~RaceLapTime();  /* 0: RaceLapTime::~RaceLapTime() */
};
#else
struct RaceLapTime;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003BB9F8  RaceLapTime::~RaceLapTime() [high]
 */

#endif /* GT4_RaceLapTime_H */
