/* gt4/RaceDisplayObjectBase.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDisplayObjectBase
 * type_info 0x006D5FC8, type_info function 0x005FA678, structors 0x003AEBA8, 0x003AEBF8
 * vtable 0x0067FAC0: 9 slots
 * C++ (GT4_CXX): size 0x18 (not known: up to the last field seen), vptr at 0x14 (introduced here)
 */
#ifndef GT4_RaceDisplayObjectBase_H
#define GT4_RaceDisplayObjectBase_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class RaceDisplayObjectBase {
public:
    char pad0[0x14];
    virtual ~RaceDisplayObjectBase();  /* 0: RaceDisplayObjectBase::~RaceDisplayObjectBase() */
    virtual s32 load();  /* 1: RaceDisplayObjectBase::load() */
    virtual void unload();  /* 2: RaceDisplayObjectBase::unload() */
    virtual f32 update();  /* 3: RaceDisplayObjectBase::update() */
    virtual s32 render_main();  /* 4: RaceDisplayObjectBase::render_main() */
    virtual s32 render_main(void *);  /* 5: RaceDisplayObjectBase::render_main(GSBuffer&) */
    virtual void setLocation(s32, s32);  /* 6: RaceDisplayObjectBase::setLocation(int, int) */
    virtual void virtual_7(s32, s32);  /* 7: parameters from the code */
    virtual void virtual_8(s32, s32);  /* 8: parameters from the code */
    void selectTexture(const char *);  /* 0x003AECB0 */
};
#else
struct RaceDisplayObjectBase;
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
void RaceDisplayObjectBase__selectTexture(struct RaceDisplayObjectBase *, const char *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003AEBF8  RaceDisplayObjectBase::~RaceDisplayObjectBase() [high]
 *   1: 0x003AEC58  RaceDisplayObjectBase::load() [high]
 *   2: 0x003AEC60  RaceDisplayObjectBase::unload() [high]
 *   3: 0x003AEC68  RaceDisplayObjectBase::update() [high]
 *   4: 0x003AEC70  RaceDisplayObjectBase::render_main() [high]
 *   5: 0x003AEC78  RaceDisplayObjectBase::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80  RaceDisplayObjectBase::setLocation(int, int) [high]
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 */

#endif /* GT4_RaceDisplayObjectBase_H */
