/* gt4/RaceDriverModel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDriverModel : HumanModel
 * type_info 0x0088F690, type_info function 0x005FA9D0, structors 0x003B1858, 0x003B1890
 * vtable 0x0067FB50: 5 slots
 * size: not known; the fields seen reach 0x7E0
 */
#ifndef GT4_RaceDriverModel_H
#define GT4_RaceDriverModel_H

#include "types.h"

struct RaceDriverModel {
    s32 unk0;
    char pad4[0x6AC];
    union {
        s32 *unk6B0;
        s32 unk6B0_s32;
    };
    char pad6B4[0x128];
    s32 unk7DC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003B1890
 *   1: 0x003B0FF0
 *   2: 0x003B1028
 *   3: 0x003B1030
 *   4: 0x003B1B60
 */

#endif /* GT4_RaceDriverModel_H */
