/* gt4/RacePanel.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RacePanel : RaceDisplayObjectBase
 * type_info 0x0088F5F0, type_info function 0x005F9D50, structors 0x0039AB68, 0x003A73F8, 0x005F9CE8, 0x005F9E90, 0x005FA130, 0x005FA350
 * vtable 0x0067EC88: 37 slots
 * size: not known; the fields seen reach 0x18
 */
#ifndef GT4_RacePanel_H
#define GT4_RacePanel_H

#include "types.h"

struct RacePanel {
    char pad0[0x14];
    void *unk14;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F9CE8  RacePanel::~RacePanel() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003AEC68
 *   4: 0x003AEC70
 *   5: 0x005BC5C0  RacePriusPanel::render_main(GSBuffer&) [high]
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 *   9: 0x005BC5C0  RacePriusPanel::update(float) [high]
 *  10: 0x003A7460  RacePanel::DMAsafe() [high]
 *  11: 0x003A7468  RacePanel::reset() [high]
 *  12: 0x003A7470  RacePanel::setSpeed(float) [high]
 *  13: 0x003A7478  RacePanel::setSpeedmeterScale(bool, float) [high]
 *  14: 0x003A7480  RacePanel::setTachometerRPM(float) [high]
 *  15: 0x003A7488  RacePanel::setTachometerScale(float, float) [high]
 *  16: 0x003A7490  RacePanel::setTachometerRedZone(int) [high]
 *  17: 0x003A7498  RacePanel::setBoostPressure(float) [high]
 *  18: 0x003A74A0  RacePanel::setGear(int) [high]
 *  19: 0x003A74A8  RacePanel::setClutch(bool) [high]
 *  20: 0x003A74B0  RacePanel::setAutomaticTransmission(bool) [high]
 *  21: 0x003A74B8  RacePanel::setShiftTimingLamp(bool) [high]
 *  22: 0x003A74C0  RacePanel::showSuggestedGear(bool) [high]
 *  23: 0x003A74C8  RacePanel::setSuggestedGear(int) [high]
 *  24: 0x003A74D0  RacePanel::setBrakingSign(bool) [high]
 *  25: 0x003A74D8  RacePanel::showSideGravity(bool) [high]
 *  26: 0x003A74E0  RacePanel::setSideGravity(float) [high]
 *  27: 0x003A74E8  RacePanel::setOdometer(int) [high]
 *  28: 0x003A74F0  RacePanel::showTireWear(bool) [high]
 *  29: 0x003A74F8  RacePanel::setTireWearColor(int, int, int, int) [high]
 *  30: 0x003A7500  RacePanel::setFuelAmount(float) [high]
 *  31: 0x003A7508  RacePanel::setFuelTankCapacity(float) [high]
 *  32: 0x003A7510  RacePanel::setNosAmount(float) [high]
 *  33: 0x003A7518  RacePanel::setNosTankCapacity(float) [high]
 *  34: 0x003A7520  RacePanel::setGasMileage(float) [high]
 *  35: 0x003A7528  RacePanel::setGasConsumption(float) [high]
 *  36: 0x003A7530  RacePanel::setGasUnit(int) [high]
 */

#endif /* GT4_RacePanel_H */
