/* gt4/RaceDisplay.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceDisplay : RaceDisplayBase
 * type_info 0x0088F330, type_info function 0x005F76F8, structors 0x0039A908, 0x0039AB68
 * vtable 0x0067E278: 56 slots
 * size: not known; the fields seen reach 0xC0
 */
#ifndef GT4_RaceDisplay_H
#define GT4_RaceDisplay_H

#include "types.h"

struct RaceDisplay {
    char pad0[0xC];
    s32 unkC;
    char pad10[0x14];
    s32 unk24;
    char pad28[0x7];
    s8 unk2F;
    s32 unk30;
    char pad34[0x88];
    f32 unkBC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0039B290  RaceDisplay::cleanup() [high]
 *   1: 0x0039DBB8  RaceDisplay::update(float) [high]
 *   2: 0x0039F498  RaceDisplay::render(GSBuffer&) [high]
 *   3: 0x003A01F0  RaceDisplay::DMAsafe() [high]
 *   4: 0x0039B390  RaceDisplay::setOrganization(RaceOrganization&) [high]
 *   5: 0x0039B398  RaceDisplay::setRaceMonitor(RaceMonitor*) [high]
 *   6: 0x0039B3A0  RaceDisplay::setRaceMode(int) [medium]
 *   7: 0x0039B3C0  RaceDisplay::setRunMode(int) [medium]
 *   8: 0x0039B3E8  RaceDisplay::initialize() [high]
 *   9: 0x005F77D8  RaceDisplay::setPlayerCarNumber(int) [high]
 *  10: 0x0039CDF0  RaceDisplay::setTargetCarNumber(int) [medium]
 *  11: 0x0039CE60  RaceDisplay::setViewMode(int) [high]
 *  12: 0x0039CEE8  RaceDisplay::setCameraViewMode(CameraSys::CameraManager&) [high]
 *  13: 0x0039CF60  RaceDisplay::setDiveReplayMode(bool) [high]
 *  14: 0x003A2008  RaceDisplay::setDisplayEnableInReplay(bool) [high]
 *  15: 0x005F78C0  RaceDisplay::getBackMirrorRate() const [high]
 *  16: 0x0039CE38  RaceDisplay::setGuideMode(bool) [medium]
 *  17: 0x005F7850  RaceDisplay::setMinilogo(bool) [medium]
 *  18: 0x003A2198  RaceDisplay::printMessage(char const*, float, unsigned int) [high]
 *  19: 0x0039D138  RaceDisplay::printGeneralInformation(char const*, float) [high]
 *  20: 0x0039EFE0  RaceDisplay::printReplayMode(char const*, unsigned int, unsigned int) [high]
 *  21: 0x003A2248  RaceDisplay::setExternalConstToolTip(char const*) [high]
 *  22: 0x003A2298  RaceDisplay::setExternalStartLogo(PGLUtexSet*) [high]
 *  23: 0x003A22A0
 *  24: 0x0039FDA8  RaceDisplay::render_time() [high]
 *  25: 0x0039EE10  RaceDisplay::update_rank(float, RaceOrganization&) [high]
 *  26: 0x0039D6D8  RaceDisplay::update_automobile_message(Automobile&) [high]
 *  27: 0x0039D7C8  RaceDisplay::set_automobile_message(int) [high]
 *  28: 0x0039BE08  RaceDisplay::init_starting_style_for_play() [high]
 *  29: 0x0039BEC8  RaceDisplay::init_starting_style_for_replay() [high]
 *  30: 0x0039BEA8  RaceDisplay::init_starting_style_for_spectator() [medium]
 *  31: 0x0039C028  RaceDisplay::init_starting_style_for_autodemo() [high]
 *  32: 0x0039CCF0  RaceDisplay::init_display_switch_by_run_mode(int) [high]
 *  33: 0x003A2360  RaceDisplay::init_display_config(int, int, int) [medium]
 *  34: 0x003A16A8  RaceDisplay::disable_all() [medium]
 *  35: 0x003A0228
 *  36: 0x003A02C8  RaceDisplay::onLicenseFailedEvent() [high]
 *  37: 0x003A02D0
 *  38: 0x0039CC98  RaceDisplay::put_initial_display() [medium]
 *  39: 0x003A1488  RaceDisplay::put_start_display() [high]
 *  40: 0x003A1568  RaceDisplay::put_finish_display() [high]
 *  41: 0x0039C4C8  RaceDisplay::get_aspec_point_available() const [high]
 *  42: 0x0039C570  RaceDisplay::put_aspec_race_information(float, float, float, float) [high]
 *  43: 0x0039C6D0  RaceDisplay::put_aspec_race_result() [high]
 *  44: 0x0039C838  RaceDisplay::put_replay_race_information(float, float, float, float) [medium]
 *  45: 0x0039CB38  RaceDisplay::put_replay_race_result(unsigned int) [medium]
 *  46: 0x003A0A78  RaceDisplay::put_laptime_display(int, unsigned int) [medium]
 *  47: 0x003A0C30  RaceDisplay::put_sectiontime_display(int, unsigned int) [high]
 *  48: 0x003A0D78  RaceDisplay::put_record_times_display(float) [high]
 *  49: 0x003A0D10  RaceDisplay::put_position_display(float) [high]
 *  50: 0x003A1030  RaceDisplay::get_time_diff_target_car(int) [medium]
 *  51: 0x0039F160  RaceDisplay::get_session_best_time(RaceEntryCar&) const [high]
 *  52: 0x0039AB68  RaceDisplay::~RaceDisplay() [high]
 *  53: 0x0039CD70  RaceDisplay::clear() [high]
 *  54: 0x003A1FA8  RaceDisplay::changeDisplayInReplay() [high]
 *  55: 0x003A2040  RaceDisplay::setDisplayTypeInReplay(int) [high]
 */

#endif /* GT4_RaceDisplay_H */
