/* gt4/RaceABMonitor.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RaceABMonitor : RaceDisplayObjectBase
 * type_info 0x0088F470, type_info function 0x005F9130, structors 0x0039AB68, 0x003A53F0, 0x005F9070, 0x005F9E90
 * vtable 0x0067F328: 9 slots
 * size: not known; the fields seen reach 0x18
 */
#ifndef GT4_RaceABMonitor_H
#define GT4_RaceABMonitor_H

#include "types.h"

struct RaceABMonitor {
    char pad0[0x14];
    void *unk14;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F9070  RaceABMonitor::~RaceABMonitor() [high]
 *   1: 0x003AEC58
 *   2: 0x003AEC60
 *   3: 0x003A54F8  RaceABMonitor::update() [high]
 *   4: 0x003A5648  RaceABMonitor::render_main() [high]
 *   5: 0x003AEC78
 *   6: 0x003AEC80
 *   7: 0x003AEC90
 *   8: 0x003AECA0
 */

#endif /* GT4_RaceABMonitor_H */
