/* gt4/rbuf.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class rbuf
 * type_info 0x006D6240, type_info function 0x00610D68, structors 0x00554668, 0x00554758
 * vtable 0x00689958: 1 slots
 * size: not known; the fields seen reach 0x44
 */
#ifndef GT4_rbuf_H
#define GT4_rbuf_H

#include "types.h"

struct rbuf {
    char pad0[0x1C];
    void *unk1C;
    char pad20[0x20];
    void *unk40;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00554758
 */

#endif /* GT4_rbuf_H */
