/* gt4/RebuildPropagate.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RebuildPropagate : MAction
 * type_info 0x0088E250, type_info function 0x005DBCC0, structors 0x002355E0
 * vtable 0x006653F8: 2 slots
 * size: not known; the fields seen reach 0x8
 */
#ifndef GT4_RebuildPropagate_H
#define GT4_RebuildPropagate_H

#include "types.h"

struct RebuildPropagate {
    char pad0[0x4];
    s32 unk4;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005DBD10  RebuildPropagate::~RebuildPropagate() [high]
 *   1: 0x005DBD48  RebuildPropagate::doAction(hObject*) [high]
 */

#endif /* GT4_RebuildPropagate_H */
