/* gt4/RefPointer.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RefPointer
 * type_info 0x006D5E20, type_info function 0x005CA408
 * C++ (GT4_CXX): size 0x0 (not known: up to the last field seen)
 */
#ifndef GT4_RefPointer_H
#define GT4_RefPointer_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)

class RefPointer {
public:
};
#else
struct RefPointer;
#endif

#endif /* GT4_RefPointer_H */
