/* gt4/RelocatorBase.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class RelocatorBase
 * type_info 0x006D62C0, type_info function 0x00613AE8, structors 0x0057A070
 * vtable 0x00689EC8: 1 slots
 * size: not known; the fields seen reach 0x14
 */
#ifndef GT4_RelocatorBase_H
#define GT4_RelocatorBase_H

#include "types.h"

struct RelocatorBase {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    s32 unkC;
    void *unk10;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x0057A120  RelocatorBase::readUserChunks(unsigned char*, unsigned int, unsigned int) [high]
 */

#endif /* GT4_RelocatorBase_H */
