/* gt4/ResultLinkBattle.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ResultLinkBattle : ResultArcade
 * type_info 0x0088F050, type_info function 0x005F48C0, structors 0x00336448, 0x00336718, 0x003389F0, 0x00338B80, 0x005F4858
 * vtable 0x006798C0: 17 slots
 * size: not known; the fields seen reach 0x50C
 */
#ifndef GT4_ResultLinkBattle_H
#define GT4_ResultLinkBattle_H

#include "types.h"

struct ResultLinkBattle {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    void *unkC;
    s32 unk10;
    char pad14[0x40];
    s32 unk54;
    char pad58[0x4];
    s32 unk5C;
    char pad60[0x4A0];
    f32 unk500;
    s32 unk504;
    s32 unk508;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F4858
 *   1: 0x00343220
 *   2: 0x003DF210
 *   3: 0x00343270
 *   4: 0x003DFC70
 *   5: 0x00343318
 *   6: 0x003DFE20
 *   7: 0x003DF1B8
 *   8: 0x003DFEB0
 *   9: 0x003433C8
 *  10: 0x003DFE88
 *  11: 0x003DF940
 *  12: 0x005FE170
 *  13: 0x003DF950
 *  14: 0x003DF960
 *  15: 0x005FE178
 *  16: 0x003DF7C8
 */

#endif /* GT4_ResultLinkBattle_H */
