/* gt4/ResultArcade.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ResultArcade : RaceResultBase
 * type_info 0x0088F8B0, type_info function 0x005FE0E8, structors 0x003DEE70, 0x003DEEA0
 * vtable 0x00683288: 17 slots
 * size: not known; the fields seen reach 0x10
 */
#ifndef GT4_ResultArcade_H
#define GT4_ResultArcade_H

#include "types.h"

struct ResultArcade {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    void *unkC;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003DEEA0  ResultArcade::~ResultArcade() [high]
 *   1: 0x003DF050  ResultArcade::init(RaceOrganization&, int) [high]
 *   2: 0x003DF210  ResultArcade::cleanup() [high]
 *   3: 0x003DF978  ResultArcade::update(RaceOrganization&, RaceInput&) [high]
 *   4: 0x003DFC70  ResultArcade::render(GSBuffer&, RaceOrganization&) [high]
 *   5: 0x003DFCC8  ResultArcade::goal(RaceOrganization&, int) [high]
 *   6: 0x003DFE20  ResultArcade::startResultSequence(RaceOrganization&) [high]
 *   7: 0x003DF1B8  ResultArcade::isResultStarting(int) [high]
 *   8: 0x003DFEB0  ResultArcade::setData(int, RaceEntryCar*) [high]
 *   9: 0x003DFC50  ResultArcade::setCarName(char*, RaceEntryCar*) [high]
 *  10: 0x003DFE88  ResultArcade::postStartResultSequence(RaceOrganization&) [high]
 *  11: 0x003DF940  ResultArcade::getStrobeFilename() const [high]
 *  12: 0x005FE170  ResultArcade::isStrobeFileCommonDir() const [high]
 *  13: 0x003DF950  ResultArcade::getStrobeActionCallback() const [high]
 *  14: 0x003DF960  ResultArcade::getStrobeRenderCallback() const [high]
 *  15: 0x005FE178  ResultArcade::isChampionship() const [high]
 *  16: 0x003DF7C8  ResultArcade::subCallFunction(std::basic_string<char, std::char_traits<char>, PDISTD::stl_allocator<char, 16u> > const&, unsigned int, strobe::ActionStack&) [high]
 */

#endif /* GT4_ResultArcade_H */
