/* gt4/ResultChampionship.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ResultChampionship : ResultArcade
 * type_info 0x0088FA90, type_info function 0x005FF560, structors 0x003EF498, 0x003EF620, 0x005FF4F8, 0x005FF5B0
 * vtable 0x006863E0: 17 slots
 * size: not known; the fields seen reach 0x564
 */
#ifndef GT4_ResultChampionship_H
#define GT4_ResultChampionship_H

#include "types.h"

struct ResultChampionship {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    union {
        s32 unkC;
        void *unkC_pvoid;
    };
    char pad10[0x550];
    s32 unk560;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FF4F8  ResultChampionship::~ResultChampionship() [high]
 *   1: 0x0040C4A0  ResultChampionship::init(RaceOrganization&, int) [high]
 *   2: 0x003DF210
 *   3: 0x003DF978
 *   4: 0x003DFC70
 *   5: 0x003DFCC8
 *   6: 0x003DFE20
 *   7: 0x003DF1B8
 *   8: 0x003DFEB0
 *   9: 0x003DFC50
 *  10: 0x003DFE88
 *  11: 0x003DF940
 *  12: 0x005FE170
 *  13: 0x003DF950
 *  14: 0x003DF960
 *  15: 0x005FF5E8  ResultChampionship::isChampionship() const [high]
 *  16: 0x0040C638  ResultChampionship::subCallFunction(std::basic_string<char, std::char_traits<char>, PDISTD::stl_allocator<char, 16u> > const&, unsigned int, strobe::ActionStack&) [high]
 */

#endif /* GT4_ResultChampionship_H */
