/* gt4/ResultLicense.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ResultLicense : ResultArcade
 * type_info 0x0088F8C0, type_info function 0x005FE258, structors 0x003E0768, 0x003E0860
 * vtable 0x00683370: 17 slots
 * size: not known; the fields seen reach 0x584
 * C++ (GT4_CXX): size 0x584 (not known: up to the last field seen), vptr at 0xC, fields left out (overlap, or in the base's part): 0xC
 */
#ifndef GT4_ResultLicense_H
#define GT4_ResultLicense_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/ResultArcade.h"

class ResultLicense : public ResultArcade {
public:
    char pad10[0x570];
    f32 unk580;
    s32 disableEffect();  /* 0x003E09A8 */
};
#else
struct ResultLicense {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    union {
        s32 unkC;
        void *unkC_pvoid;
    };
    char pad10[0x570];
    f32 unk580;
};
#endif

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 ResultLicense__init(struct ResultLicense *, void *, s32);
s32 ResultLicense__disableEffect(struct ResultLicense *);
s32 ResultLicense__cleanup(struct ResultLicense *);
s32 ResultLicense__getStrobeFilename(struct ResultLicense *);
s32 ResultLicense__getStrobeActionCallback(struct ResultLicense *);
s32 ResultLicense__getStrobeRenderCallback(struct ResultLicense *);
f32 ResultLicense__update(struct ResultLicense *, void *, struct RaceInput *);
void ResultLicense__postStartResultSequence(struct ResultLicense *, void *);
s32 ResultLicense__isStrobeFileCommonDir(struct ResultLicense *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003E0860  ResultLicense::~ResultLicense() [high]
 *   1: 0x003E08D0  ResultLicense::init(RaceOrganization&, int) [high]
 *   2: 0x003E09F8  ResultLicense::cleanup() [high]
 *   3: 0x003E1C28  ResultLicense::update(RaceOrganization&, RaceInput&) [high]
 *   4: 0x003DFC70
 *   5: 0x003DFCC8
 *   6: 0x003DFE20
 *   7: 0x003DF1B8
 *   8: 0x003DFEB0
 *   9: 0x003DFC50
 *  10: 0x003E20A0  ResultLicense::postStartResultSequence(RaceOrganization&) [high]
 *  11: 0x003E1BF8  ResultLicense::getStrobeFilename() const [high]
 *  12: 0x005FE2A8  ResultLicense::isStrobeFileCommonDir() const [high]
 *  13: 0x003E1C08  ResultLicense::getStrobeActionCallback() const [high]
 *  14: 0x003E1C18  ResultLicense::getStrobeRenderCallback() const [high]
 *  15: 0x005FE178
 *  16: 0x003DF7C8
 */

#endif /* GT4_ResultLicense_H */
