/* gt4/ShowRoomCar.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class ShowRoomCar
 * type_info 0x006D5F88, type_info function 0x005F4FD0, structors 0x00364760, 0x003647A0
 * vtable 0x0067A048: 1 slots
 * size: not known; the fields seen reach 0xC
 */
#ifndef GT4_ShowRoomCar_H
#define GT4_ShowRoomCar_H

#include "types.h"

struct ShowRoomCar {
    s32 unk0;
    s8 unk4;
    char pad5[0x3];
    s32 unk8;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x003647A0  ShowRoomCar::~ShowRoomCar() [high]
 */

#endif /* GT4_ShowRoomCar_H */
