/* gt4/SingleHandedHandleSolver.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class SingleHandedHandleSolver : HandleSolverBase
 * type_info 0x0088FAC0, type_info function 0x005FF878, structors 0x00415CD8
 * vtable 0x00686478: 2 slots
 * C++ (GT4_CXX): size 0x50 (not known: up to the last field seen), vptr at 0x4C
 */
#ifndef GT4_SingleHandedHandleSolver_H
#define GT4_SingleHandedHandleSolver_H

#include "types.h"

#if defined(__cplusplus) && defined(GT4_CXX)
#include "gt4/HandleSolverBase.h"

class SingleHandedHandleSolver : public HandleSolverBase {
public:
};
#else
struct SingleHandedHandleSolver;
#endif

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FF840  SingleHandedHandleSolver::~SingleHandedHandleSolver() [high]
 *   1: 0x00415D38  SingleHandedHandleSolver::solve(Numerical_Math::Radian, Numerical_Math::Radian, float, float, pdiRiderman::Car const&) [high]
 */

#endif /* GT4_SingleHandedHandleSolver_H */
