/* gt4/SparkParticle.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class SparkParticle : Particle
 * type_info 0x0088F780, type_info function 0x005FBC78, structors 0x003C26C8
 * vtable 0x00681AE8: 6 slots
 * size: not known; the fields seen reach 0x58
 */
#ifndef GT4_SparkParticle_H
#define GT4_SparkParticle_H

#include "types.h"

struct SparkParticle {
    char pad0[0x4];
    void *unk4;
    union {
        s16 unk8;
        u16 unk8_u16;
    };
    s16 unkA;
    f32 unkC;
    f32 unk10;
    f32 unk14;
    f32 unk18;
    f32 unk1C;
    f32 unk20;
    f32 unk24;
    f32 unk28;
    f32 unk2C;
    s32 unk30;
    f32 unk34;
    s32 unk38;
    s32 unk3C;
    f32 unk40;
    f32 unk44;
    s32 unk48;
    s32 unk4C;
    s32 unk50;
    s32 unk54;
};

#ifdef GT4_DECLS
#ifdef __cplusplus
extern "C" {
#endif
s32 SparkParticle__Update(struct SparkParticle *, f32, s32);
s32 SparkParticle__Render(struct SparkParticle *);
s32 SparkParticle__getColor(struct SparkParticle *);
s32 SparkParticle__Init(struct SparkParticle *);
s32 SparkParticle__write(struct SparkParticle *, void *, const struct ParticleManager *);
f32 SparkParticle__read(struct SparkParticle *, void *, const struct ParticleManager *);
s32 SparkParticle__getClassID(struct SparkParticle *);
#ifdef __cplusplus
}
#endif
#endif /* GT4_DECLS */

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005FBCC8  SparkParticle::getClassID() [high]
 *   1: 0x003C1430  SparkParticle::Update(float, bool) [high]
 *   2: 0x003C1900  SparkParticle::Render() [high]
 *   3: 0x003C1B40  SparkParticle::Init() [high]
 *   4: 0x003C1B50  SparkParticle::write(GT4Model::BinStreamWriter&, ParticleManager const&) [high]
 *   5: 0x003C1D78  SparkParticle::read(GT4Model::BinStreamReader&, ParticleManager const&) [high]
 */

#endif /* GT4_SparkParticle_H */
