/* gt4/StandardComputeDriverPostureCaller.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class StandardComputeDriverPostureCaller : ComputeDriverPostureCaller
 * type_info 0x0088F290, type_info function 0x005F7058, structors 0x00391830
 * vtable 0x0067E108: 1 slots
 */
#ifndef GT4_StandardComputeDriverPostureCaller_H
#define GT4_StandardComputeDriverPostureCaller_H

#include "types.h"

struct StandardComputeDriverPostureCaller;

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x005F70A8  StandardComputeDriverPostureCaller::getPosition(HumanModel const&, int) [medium]
 */

#endif /* GT4_StandardComputeDriverPostureCaller_H */
