/* gt4/streambuf.h: generated by tools/gen_headers.py from config/classes.json and the fields the
 * class's functions use (tools/cleanup.py fields). Do not edit: change the inputs and regenerate.
 * class streambuf : _IO_FILE
 * type_info 0x008A1C30, type_info function 0x00615388, structors 0x00594120, 0x00594140
 * vtable 0x0068A0B0: 17 slots
 * size: not known; the fields seen reach 0x54
 */
#ifndef GT4_streambuf_H
#define GT4_streambuf_H

#include "types.h"

struct streambuf {
    char pad0[0x50];
    void *unk50;
};

/* virtual functions (slot: address; the GT HD name when tools/gthd_names.py found it)
 *   0: 0x00594140
 *   1: 0x00593E88
 *   2: 0x00593E68
 *   3: 0x00593E70
 *   4: 0x00593F80
 *   5: 0x00593E90
 *   6: 0x00593EC0
 *   7: 0x005941A8
 *   8: 0x00594078
 *   9: 0x00593F98
 *  10: 0x00593F78
 *  11: 0x005940E8
 *  12: 0x005942B0
 *  13: 0x005942B8
 *  14: 0x005942C0
 *  15: 0x005942C8
 *  16: 0x00594288
 */

#endif /* GT4_streambuf_H */
