/* compiler: ee-gcc2.96-no-strict-aliasing */
/* Looks up 9 settings by name in the table a1 (func_0020FD38(a1, &name, &cb)), each with a callback
   object (vtable + target pointer: a field of a0, or a local copied to a0 + 0x20 on success; its
   destructor resets the vtable and calls the base dtor MReaderBase__structor_0(&cb, 0)); returns 1 at the
   first success, else 0. A default-constructed string lives across the whole function. Each block's
   locals are one struct of a union laid out as in the original frame; bastring.h's (const char *)
   ctor and dtor as inline helpers. Generated by build/auto/str_mid2/chain.py (style c). */
typedef unsigned int u32;
typedef int s32;

struct Rep { u32 len; u32 res; u32 ref; u32 selfish; };
struct Str { char *dat; };
struct Heap { const char *name; };
extern Rep D_00659FA8;
extern "C" char *func_005C2560(Rep *r);
extern "C" u32 func_0057F260(const char *s);
extern "C" Heap *func_005C11A8(void);
extern "C" void func_00326798(void *p, u32 n, u32 align, const char *name);
extern "C" Str *func_005C2630(Str *self, u32 pos, u32 n1, const char *s, u32 n2);

static inline char *grab(Rep *r) {
    if (r->selfish)
        return func_005C2560(r);
    ++r->ref;
    return (char *)(r + 1);
}
static inline Str &assign(Str *str, const char *s, u32 n) { return *func_005C2630(str, 0, (u32)-1, s, n); }
static inline Str &assign(Str *str, const char *s) { return assign(str, s, func_0057F260(s)); }
static inline void construct(Str *str, const char *s) { str->dat = grab(&D_00659FA8); assign(str, s); }
static inline void construct(Str *str) { str->dat = grab(&D_00659FA8); }
static inline Rep *rep(const Str *str) { return (Rep *)str->dat - 1; }
static inline void deallocate(void *p, u32 n) { func_00326798(p, n, 4, func_005C11A8()->name); }
static inline void rep_delete(void *ptr) { deallocate(ptr, sizeof(Rep) + ((Rep *)ptr)->res); }
static inline void release(Rep *r) { if (--r->ref == 0) rep_delete(r); }
static inline void destroy(Str *str) { release(rep(str)); }

struct Cb { void **vtbl; void *p; };
extern "C" s32 func_0020FD38(void *a, Str *s, void *cb);
extern "C" void MReaderBase__structor_0(Cb *cb, s32 flags);
struct L0 { Str t; s32 pad0[3]; Cb cb; };
struct L1 { Str t; s32 pad0[7]; Cb cb; };
struct L2 { Str t; s32 pad0[11]; Cb cb; };
struct L3 { Str t; s32 pad0[15]; Cb cb; };
struct L4 { Str t; s32 pad0[3]; Cb cb; s32 pad1[14]; s32 v; };
extern char D_00698060[];
extern char D_00698070[];
extern char D_00698080[];
extern char D_00698090[];
extern char D_006980A0[];
extern char D_006980A8[];
extern char D_006980B0[];
extern char D_006980B8[];
extern char D_006980C0[];
extern void *MstringReader__vtable[];
extern void *MboolReader__vtable[];
extern void *MintReader__vtable[];

struct MboolReader__structor_4_pcb {
    char pad0[0x4];
    char *unk4;
};

extern "C" s32 MboolReader__structor_4(char *a0, void *a1)
{
    Str s;
    union { L0 l0; L1 l1; L2 l2; L3 l3; L4 l4; } u;
    construct(&s);
    {
        construct(&u.l0.t, D_00698060);
        char *p = (char *)(a0);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MstringReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MstringReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l1.t, D_00698070);
        char *p = (char *)(a0 + 0x4);
        Cb *pcb = &u.l1.cb;
        pcb->vtbl = MintReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l1.t, pcb);
        pcb->vtbl = MintReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l1.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l2.t, D_00698080);
        char *p = (char *)(a0 + 0x8);
        Cb *pcb = &u.l2.cb;
        pcb->vtbl = MintReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l2.t, pcb);
        pcb->vtbl = MintReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l2.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l3.t, D_00698090);
        char *p = (char *)(a0 + 0xC);
        Cb *pcb = &u.l3.cb;
        pcb->vtbl = MboolReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l3.t, pcb);
        pcb->vtbl = MboolReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l3.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l0.t, D_006980A0);
        char *p = (char *)(a0 + 0x10);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MboolReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MboolReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l0.t, D_006980A8);
        char *p = (char *)(a0 + 0x14);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MboolReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MboolReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l4.t, D_006980B0);
        char *p = (char *)(&u.l4.v);
        Cb *pcb = &u.l4.cb;
        pcb->vtbl = MintReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l4.t, pcb);
        pcb->vtbl = MintReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l4.t);
        if (r) {
            *(s32 *)(a0 + 0x20) = u.l4.v;
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l0.t, D_006980B8);
        char *p = (char *)(a0 + 0x18);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MboolReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MboolReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    {
        construct(&u.l0.t, D_006980C0);
        char *p = (char *)(a0 + 0x1C);
        Cb *pcb = &u.l0.cb;
        pcb->vtbl = MintReader__vtable;
        ((struct MboolReader__structor_4_pcb *)pcb)->unk4 = p;
        s32 r = func_0020FD38(a1, &u.l0.t, pcb);
        pcb->vtbl = MintReader__vtable;
        MReaderBase__structor_0(pcb, 0);
        destroy(&u.l0.t);
        if (r) {
            destroy(&s);
            return 1;
        }
    }
    destroy(&s);
    return 0;
}
