/* compiler: ee-gcc2.96-stl */
/* Fills a map<basic_string<char>, Pod8_005DEB18> (the tree of func_005DDD30, an 8-byte member
   function pointer per name) in place: the map constructed, then 49 `m[name] = value` with
   stl_map.h's operator[] inline (lower_bound func_005DDCB0, insert_unique(position) func_005DDD30)
   and bastring.h's (const char *) constructor inline. Generated by build/auto/str_mid/gen25b.py. */
#include <stl_tree.h>
#include <stl_map.h>

extern "C" void *func_00326750(int size, int align, const char *name);

extern "C" void *func_005DEB18(void);

struct Rep {
    int len;
    int cap;
    int ref;
    int sel;
};

struct HeapName {
    const char *name;
};

extern "C" int func_005C2A50(const void *self, const void *other, unsigned int pos, unsigned int n);
extern "C" char *func_005C2560(Rep *rep);
extern "C" HeapName *func_005C11A8(void);
extern "C" void func_00326798(void *p, int size, int align, const char *name);

/* the game's reference-counted string (knowledge/runtime-types.md): the pointer is read and
   written as an int so the representation's counters can alias it */
struct Str {
    char *p;
    inline Str(const char *s);
    Str(const Str &o) {
        int q = *(int *)&o.p;
        Rep *r = (Rep *)(q - 0x10);
        int d = q;
        if (r->sel != 0) {
            d = (int)func_005C2560(r);
        } else {
            r->ref = r->ref + 1;
        }
        *(int *)&p = d;
    }
    ~Str() {
        Rep *r = (Rep *)(*(int *)&p - 0x10);
        if (--r->ref == 0) {
            int size = r->cap + 0x10;
            func_00326798(r, size, 4, func_005C11A8()->name);
        }
    }
    bool operator<(const Str &o) const { return func_005C2A50(this, &o, 0, (unsigned int)-1) < 0; }
};

struct Pod8_005DEB18 {
    int w[2];
};

/* gcc 2.96's type_info: the name first, the vtable pointer after it */
struct TypeInfo {
    const char *name;
};

/* typeid(T).name() of the types this source allocates, without typeid: the game's own __tf getter */
template <class T> struct TypeTag;

/* the game's allocator: every block is tagged with the name of its type */
template <class T>
class GameAlloc {
public:
    typedef size_t size_type;
    typedef ptrdiff_t difference_type;
    typedef T *pointer;
    typedef const T *const_pointer;
    typedef T &reference;
    typedef const T &const_reference;
    typedef T value_type;
    template <class U> struct rebind { typedef GameAlloc<U> other; };
    GameAlloc() throw() {}
    GameAlloc(const GameAlloc &) throw() {}
    template <class U> GameAlloc(const GameAlloc<U> &) throw() {}
    ~GameAlloc() throw() {}
    T *allocate(size_type n, const void * = 0) {
        return (T *)func_00326750(n * sizeof(T), 4, ((TypeInfo *)TypeTag<T>::tf())->name);
    }
    void deallocate(T *p, size_type n) {
        func_00326798(p, n * sizeof(T), 4, ((TypeInfo *)TypeTag<T>::tf())->name);
    }
    size_type max_size() const throw() { return size_t(-1) / sizeof(T); }
    void construct(T *p, const T &v) { new (p) T(v); }
    void destroy(T *p) { p->~T(); }
};

typedef Str Key;
typedef pair<const Str, Pod8_005DEB18> Value;
typedef _Rb_tree_node<Value> Node;
template <> struct TypeTag<Node> { static void *tf() { return func_005DEB18(); } };

typedef _Rb_tree<Key, Value, _Select1st<Value>, less<Key>, GameAlloc<Value> > Tree;

/* bastring.h's (const char *) constructor: nilRep.grab() + assign(s) = assign(s, strlen(s))
   = replace(0, npos, s, n) */
extern Rep D_00659FA8;
extern "C" unsigned int func_0057F260(const char *s);
extern "C" Str *func_005C2630(Str *self, unsigned int pos, unsigned int n1, const char *s, unsigned int n2);

static inline char *grab(Rep *r)
{
    if (r->sel)
        return func_005C2560(r);
    ++r->ref;
    return (char *)(r + 1);
}

static inline Str &assign(Str *str, const char *s, unsigned int n)
{
    return *func_005C2630(str, 0, (unsigned int)-1, s, n);
}

static inline Str &assign(Str *str, const char *s)
{
    return assign(str, s, func_0057F260(s));
}

inline Str::Str(const char *s)
{
    p = grab(&D_00659FA8);
    assign(this, s);
}

typedef map<Key, Pod8_005DEB18, less<Key>, GameAlloc<Value> > Map;

/* placement new without the null check of <new>'s throw() version */
struct InPlace {};
inline void *operator new(size_t, void *p, InPlace) { return p; }

extern char D_00699A00[];
extern char D_006999F0[];
extern char D_006999E0[];
extern char D_00699C28[];
extern char D_00699C40[];
extern char D_00699C58[];
extern char D_00699C78[];
extern char D_00699C90[];
extern char D_00699CA8[];
extern char D_00699CC0[];
extern char D_00699CD8[];
extern char D_00699CE8[];
extern char D_00699D00[];
extern char D_00699D18[];
extern char D_00699A08[];
extern char D_006999C0[];
extern char D_00699B50[];
extern char D_00699B40[];
extern char D_00699D48[];
extern char D_00699AA0[];
extern char D_00699A80[];
extern char D_00699A90[];
extern char D_00699A78[];
extern char D_00699AD0[];
extern char D_00699AE0[];
extern char D_00699D88[];
extern char D_00699B00[];
extern char D_00699B10[];
extern char D_00699B20[];
extern char D_00699B30[];
extern char D_00699AF0[];
extern char D_00699AC8[];
extern char D_00699DD0[];
extern char D_00699A58[];
extern char D_00699A50[];
extern char D_00699A70[];
extern char D_00699AC0[];
extern char D_00699AB0[];
extern char D_00699A60[];
extern char D_006999D8[];
extern char D_00699E20[];
extern char D_00699E38[];
extern char D_00699E58[];
extern char D_00699A18[];
extern char D_00699E70[];
extern char D_00699E88[];
extern char D_00699A20[];
extern char D_00699EA0[];
extern char D_00699EB8[];
extern const Pod8_005DEB18 D_00699C10;
extern const Pod8_005DEB18 D_00699C18;
extern const Pod8_005DEB18 D_00699C20;
extern const Pod8_005DEB18 D_00699C38;
extern const Pod8_005DEB18 D_00699C50;
extern const Pod8_005DEB18 D_00699C70;
extern const Pod8_005DEB18 D_00699C88;
extern const Pod8_005DEB18 D_00699CA0;
extern const Pod8_005DEB18 D_00699CB8;
extern const Pod8_005DEB18 D_00699CD0;
extern const Pod8_005DEB18 D_00699CE0;
extern const Pod8_005DEB18 D_00699CF8;
extern const Pod8_005DEB18 D_00699D10;
extern const Pod8_005DEB18 D_00699D20;
extern const Pod8_005DEB18 D_00699D28;
extern const Pod8_005DEB18 D_00699D30;
extern const Pod8_005DEB18 D_00699D38;
extern const Pod8_005DEB18 D_00699D40;
extern const Pod8_005DEB18 D_00699D50;
extern const Pod8_005DEB18 D_00699D58;
extern const Pod8_005DEB18 D_00699D60;
extern const Pod8_005DEB18 D_00699D68;
extern const Pod8_005DEB18 D_00699D70;
extern const Pod8_005DEB18 D_00699D78;
extern const Pod8_005DEB18 D_00699D80;
extern const Pod8_005DEB18 D_00699D98;
extern const Pod8_005DEB18 D_00699DA0;
extern const Pod8_005DEB18 D_00699DA8;
extern const Pod8_005DEB18 D_00699DB0;
extern const Pod8_005DEB18 D_00699DB8;
extern const Pod8_005DEB18 D_00699DC0;
extern const Pod8_005DEB18 D_00699DC8;
extern const Pod8_005DEB18 D_00699DE0;
extern const Pod8_005DEB18 D_00699DE8;
extern const Pod8_005DEB18 D_00699DF0;
extern const Pod8_005DEB18 D_00699DF8;
extern const Pod8_005DEB18 D_00699E00;
extern const Pod8_005DEB18 D_00699E08;
extern const Pod8_005DEB18 D_00699E10;
extern const Pod8_005DEB18 D_00699E18;
extern const Pod8_005DEB18 D_00699E30;
extern const Pod8_005DEB18 D_00699E50;
extern const Pod8_005DEB18 D_00699E60;
extern const Pod8_005DEB18 D_00699E68;
extern const Pod8_005DEB18 D_00699E80;
extern const Pod8_005DEB18 D_00699E90;
extern const Pod8_005DEB18 D_00699E98;
extern const Pod8_005DEB18 D_00699EB0;
extern const Pod8_005DEB18 D_00699EC0;

extern "C" void func_0025C560(Map *m)
{
    new (m, InPlace()) Map;
    (*m)[Str(D_00699A00)] = D_00699C10;
    (*m)[Str(D_006999F0)] = D_00699C18;
    (*m)[Str(D_006999E0)] = D_00699C20;
    (*m)[Str(D_00699C28)] = D_00699C38;
    (*m)[Str(D_00699C40)] = D_00699C50;
    (*m)[Str(D_00699C58)] = D_00699C70;
    (*m)[Str(D_00699C78)] = D_00699C88;
    (*m)[Str(D_00699C90)] = D_00699CA0;
    (*m)[Str(D_00699CA8)] = D_00699CB8;
    (*m)[Str(D_00699CC0)] = D_00699CD0;
    (*m)[Str(D_00699CD8)] = D_00699CE0;
    (*m)[Str(D_00699CE8)] = D_00699CF8;
    (*m)[Str(D_00699D00)] = D_00699D10;
    (*m)[Str(D_00699D18)] = D_00699D20;
    (*m)[Str(D_00699A08)] = D_00699D28;
    (*m)[Str(D_006999C0)] = D_00699D30;
    (*m)[Str(D_00699B50)] = D_00699D38;
    (*m)[Str(D_00699B40)] = D_00699D40;
    (*m)[Str(D_00699D48)] = D_00699D50;
    (*m)[Str(D_00699AA0)] = D_00699D58;
    (*m)[Str(D_00699A80)] = D_00699D60;
    (*m)[Str(D_00699A90)] = D_00699D68;
    (*m)[Str(D_00699A78)] = D_00699D70;
    (*m)[Str(D_00699AD0)] = D_00699D78;
    (*m)[Str(D_00699AE0)] = D_00699D80;
    (*m)[Str(D_00699D88)] = D_00699D98;
    (*m)[Str(D_00699B00)] = D_00699DA0;
    (*m)[Str(D_00699B10)] = D_00699DA8;
    (*m)[Str(D_00699B20)] = D_00699DB0;
    (*m)[Str(D_00699B30)] = D_00699DB8;
    (*m)[Str(D_00699AF0)] = D_00699DC0;
    (*m)[Str(D_00699AC8)] = D_00699DC8;
    (*m)[Str(D_00699DD0)] = D_00699DE0;
    (*m)[Str(D_00699A58)] = D_00699DE8;
    (*m)[Str(D_00699A50)] = D_00699DF0;
    (*m)[Str(D_00699A70)] = D_00699DF8;
    (*m)[Str(D_00699AC0)] = D_00699E00;
    (*m)[Str(D_00699AB0)] = D_00699E08;
    (*m)[Str(D_00699A60)] = D_00699E10;
    (*m)[Str(D_006999D8)] = D_00699E18;
    (*m)[Str(D_00699E20)] = D_00699E30;
    (*m)[Str(D_00699E38)] = D_00699E50;
    (*m)[Str(D_00699E58)] = D_00699E60;
    (*m)[Str(D_00699A18)] = D_00699E68;
    (*m)[Str(D_00699E70)] = D_00699E80;
    (*m)[Str(D_00699E88)] = D_00699E90;
    (*m)[Str(D_00699A20)] = D_00699E98;
    (*m)[Str(D_00699EA0)] = D_00699EB0;
    (*m)[Str(D_00699EB8)] = D_00699EC0;
}
