struct Obj {
    char pad[4];
    virtual void v000(int, int);
    virtual void v001(int, int);
    virtual void v002(int, int);
    virtual void v003(int, int);
    virtual void v004(int, int);
    virtual void v005(int, int);
    virtual void v006(int, int);
    virtual void v007(int, int);
    virtual void v008(int, int);
    virtual void v009(int, int);
    virtual void v010(int, int);
    virtual void v011(int, int);
    virtual void v012(int, int);
    virtual void v013(int, int);
    virtual void v014(int, int);
    virtual void v015(int, int);
    virtual void v016(int, int);
    virtual void v017(int, int);
    virtual void v018(int, int);
    virtual void v019(int, int);
    virtual void v020(int, int);
    virtual void v021(int, int);
    virtual void v022(int, int);
    virtual void v023(int, int);
    virtual void v024(int, int);
    virtual void v025(int, int);
    virtual void v026(int, int);
    virtual void v027(int, int);
    virtual void v028(int, int);
    virtual void v029(int, int);
    virtual void v030(int, int);
    virtual void v031(int, int);
    virtual void v032(int, int);
    virtual void v033(int, int);
    virtual void v034(int, int);
    virtual void v035(int, int);
    virtual void v036(int, int);
    virtual void v037(int, int);
    virtual void v038(int, int);
    virtual void v039(int, int);
    virtual void v040(int, int);
    virtual void v041(int, int);
    virtual void v042(int, int);
    virtual void v043(int, int);
    virtual void v044(int, int);
    virtual void v045(int, int);
    virtual void v046(int, int);
    virtual void v047(int, int);
    virtual void v048(int, int);
    virtual void v049(int, int);
    virtual void v050(int, int);
    virtual void v051(int, int);
    virtual void v052(int, int);
    virtual void v053(int, int);
    virtual void v054(int, int);
    virtual void v055(int, int);
    virtual void v056(int, int);
    virtual void v057(int, int);
    virtual void v058(int, int);
    virtual void v059(int, int);
};
extern "C" void func_005DD6C8(Obj *arg0, int a1, int a2) {
    arg0->v059(a1, a2);
}
